Repository woocommerce/woocommerce-ios, pull requests merged in 2019-10, with the labels that each got.

#1285 Polish footer spinner view for `plain` table view style
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/ShipmentProvidersViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/FooterSpinnerView.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
Labels: Product List

#1311 Refunds Step 2 - Networking layer, Mark I
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/OrderRefundMapper.swift
  Networking/Networking/Mapper/OrderRefundsMapper.swift
  Networking/Networking/Model/Order.swift
  Networking/Networking/Model/OrderRefund.swift
  Networking/Networking/Model/OrderRefundCondensed.swift
  Networking/Networking/Model/Refund/LineItemRefund.swift
  Networking/Networking/Model/Refund/Refund.swift
  Networking/Networking/Model/Refund/TaxRefund.swift
  Networking/Networking/Remote/RefundsRemote.swift
  Networking/NetworkingTests/Mapper/OrderMapperTests.swift
  Networking/NetworkingTests/Mapper/OrderRefundsMapperTests.swift
  Networking/NetworkingTests/Models/RefundTests.swift
  Networking/NetworkingTests/Remote/RefundsRemoteTests.swift
  Networking/NetworkingTests/Responses/create-manual-order-refund-response.json
  Networking/NetworkingTests/Responses/create-order-refund-response.json
  Networking/NetworkingTests/Responses/order-details-partially-refunded.json
  Networking/NetworkingTests/Responses/order-fully-refunded.json
  Networking/NetworkingTests/Responses/order-refunds-list.json
  WooCommerce/Classes/System/FeatureFlag.swift
Labels: Order Details, Refunds

#1312 Refunds Step 2: Storage - Mark I
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Order+CoreDataProperties.swift
  Storage/Storage/Model/OrderRefundCondensed+CoreDataClass.swift
  Storage/Storage/Model/OrderRefundCondensed+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 20.xcdatamodel/contents
Labels: Order Details, Refunds

#1313 Refunds Step 2: Yosemite layer - Mark I
  WooCommerce/WooCommerceTests/Tools/MockOrders.swift
  WooCommerce/WooCommerceTests/ViewRelated/SummaryTableViewCellTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/Order+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/OrderRefundCondensed+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/OrderNoteStoreTests.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: Order Details, Refunds

#1327 Stats v4: fix currency stuck in USD
  WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
Labels: Store Stats, [Type] Bug

#1315 Product List: product search from Products tab
  WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchCellViewModel.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Product List

#1330 Update Order Details to match i3 designs
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsDataSource.swift
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/Billing Information/BillingInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/Billing Information/BillingInformationViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/Billing Information/Cells/BillingAddressTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/Billing Information/Cells/BillingAddressTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerInfoTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerInfoTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerNoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerNoteTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/Add Order Note/NewNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/Add Order Note/NewNoteViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/OrderNoteHeaderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/OrderNoteHeaderTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/OrderNoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/OrderNoteTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Summary Section/Edit Order Status/OrderStatusListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Summary Section/Edit Order Status/OrderStatusListViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Summary Section/SummaryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Summary Section/SummaryTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderLoaderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Payment Section/PaymentTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Payment Section/PaymentTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/FulfillButtonTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/FulfillButtonTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/Cells/PickListTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/Cells/PickListTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/FulfillViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Product Details/ProductListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/ProductDetailsTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/ProductDetailsTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ManualTrackingViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ManualTrackingViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ShipmentProvidersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ShipmentProvidersViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/EditableOrderTrackingTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/EditableOrderTrackingTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/OrderTrackingTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/OrderTrackingTableViewCell.xib
  WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnHeadlineFootnoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnHeadlineFootnoteTableViewCell.xib
  WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnTitleFootnoteTableViewCell.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/PaymentTableViewCellTests.swift
Labels: Order Details, Refunds, [Status] Needs Design Review

#1333 Order Details: Icon on "Details" cell for fulfilled order can be wrong
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsDataSource.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/WooBasicTableViewCell.swift
Labels: Order Details, [Type] Bug

#1321 Update anonymous author name to “Someone”
  WooCommerce/Classes/ViewRelated/Notifications/ReviewViewModel.swift
  WooCommerce/WooCommerceTests/Reviews/ReviewViewModelTests.swift
Labels: Notifications, Product Reviews, [Type] Enhancement

#1323 Set background colour of notifications/review cells.
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteTableViewCell.xib
Labels: Notifications, Product Reviews, [Type] Bug

#1326 Set a background color to OrderTableViewCell
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
Labels: Dark Mode, [Type] Bug

#1336 Xcode 11 + Dark mode: temporarily disable Dark mode for login UI
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: Dark Mode, [Type] Bug

#1329 Update background colors of all cells in OrderDetails screen
  WooCommerce/Classes/Extensions/UITableViewCell+Helpers.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/CustomerInfoTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/CustomerNoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/FulfillButtonTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/WooBasicTableViewCell.swift
Labels: Dark Mode, [Type] Bug

#1337 Set background colour of cells used in Settings
  WooCommerce/Classes/Authentication/Epilogue/EmptyStoresTableViewCell.swift
  WooCommerce/Classes/Authentication/Epilogue/StoreTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/BasicTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/HeadlineLabelTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwitchTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TopLeftImageTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/ValueOneTableViewCell.swift
Labels: Dark Mode, [Type] Bug

#1339 Set background colour of cells when adding shipment tracking
  WooCommerce/Classes/ViewRelated/ReusableViews/StatusListTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TitleAndEditableValueTableViewCell.swift
Labels: Dark Mode, [Type] Bug

#1341 Configure backgrounds for add note view
  WooCommerce/Classes/ViewRelated/ReusableViews/TextViewTableViewCell.swift
Labels: Dark Mode, [Type] Bug

#1343 Xcode 11 + Dark mode: fix Order Details product SKU label
  WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
Labels: Dark Mode, [Type] Bug

#1345 Xcode 11 + Dark mode: Order details > Product details
  WooCommerce/Classes/ViewRelated/Products/Cells/ProductReviewsTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/TitleBodyTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnTableViewCell.swift
Labels: Dark Mode, [Type] Bug

#1352 Update Zendesk to version 3.0.2
  Podfile
  Podfile.lock
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Tooling

#1356 Merge 2.8 into develop
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1365 Use Fastlane Match for AppStore code signing
  .configure
  .configure-files/google_cloud_keys.json.enc
  .gitignore
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/Matchfile
Labels: Tooling

#1371 Use CocoaPods CDN specs repo for faster pod installs
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
Labels: Tooling

#1367 Orders: fix status filter being reset after changing the status of an Order
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Labels: Order List, [Type] Bug

#1369 Order Details > Edit Order Status: the current order status should be preselected in the list
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Summary Section/Edit Order Status/OrderStatusListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/StatusListTableViewCell.swift
Labels: Order Details

#1370 Xcode 11 + dark mode: fix new stats top performers ghost header view
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
Labels: Dark Mode, [Type] Bug

#1364 Refunds - Yosemite layer
  WooCommerce/Classes/ViewModels/OrderItemViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/SummaryTableViewCellTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/OrderItem+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/OrderItemRefund+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/OrderItemTax+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/OrderItemTaxRefund+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/Refund+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: Refunds, Yosemite

#1374 Update how credentials are managed so that CI builds will be possible
  .configure
  .configure-files/project.env.enc
  .configure-files/woo_app_credentials.json.enc
  Rakefile
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/env.example
  fastlane/env/project.env.example
  fastlane/env/user.env.example
Labels: Tooling

#1378 Update remaining paths to woo_app_credentials.json
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Tooling

#1366 Orders: Update Orders tab badge size
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UIView+SubviewsAxis.swift
  WooCommerce/Classes/Styles/Style.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/UIView+SubviewsAxisTests.swift
Labels: Order List, [Type] Bug

#1382 Reviews tab: Update Tracks events
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewModel.swift
Labels: Notifications, Product Reviews, [Type] Enhancement

#1384 Present review details when a notification is opened
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Notifications/Cells/ProductReviewTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Notifications/DefaultReviewsDataSource.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsDataSource.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewModel.swift
  WooCommerce/WooCommerceTests/Reviews/ReviewsViewModelTests.swift
Labels: Notifications, Product Reviews, [Type] Enhancement

#1392 Orders Badge: fix truncated "9+" label with bold text or on iOS 12
  WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift
Labels: Order List, [Type] Bug

#1379 Optionally provide installable build on Pull Requests
  .circleci/config.yml
  .configure
  .configure-files/project.env.enc
  Networking/Networking.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  Storage/Storage.xcodeproj/project.pbxproj
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce Alpha.xcscheme
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: Tooling

#1395 Product list & search: analytics
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
Labels: Product List, Tracks Events

#1401 Merge/2.9 into develop
  .gitignore
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1402 Merge 2.9 into develop
  WooCommerce/Resources/AppStoreStrings.pot
  config/Version.Public.xcconfig
Labels: Releases

#1393 Add pagination to review list
  WooCommerce/Classes/ViewRelated/Notifications/DefaultReviewsDataSource.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsDataSource.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewModel.swift
  WooCommerce/WooCommerceTests/Reviews/ReviewsViewModelTests.swift
  WooCommerce/WooCommerceTests/Tools/ReviewAgeTests.swift
  Yosemite/Yosemite/Stores/ProductReviewStore.swift
Labels: Notifications, Product Reviews, [Type] Enhancement

#1377 Stats v4: fix incorrect stats interval boundaries without using GMT dates + site time zone
  Networking/Networking/Extensions/DateFormatter+Woo.swift
  Networking/Networking/Model/Stats/OrderStatsV4Interval.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  Yosemite/Yosemite/Model/Extensions/OrderStatsV4Interval+Date.swift
  Yosemite/Yosemite/Stores/StatsStoreV4.swift
  Yosemite/YosemiteTests/Model/Extensions/OrderStatsV4Interval+DateTests.swift
Labels: Store Stats, [Type] Bug

#1403 Updated the README with steps for configuring app with API credentials
  README.md
Labels: Documentation

#1404 Fix a failing Currency Settings unit test
  WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
  WooCommerce/WooCommerceTests/Tools/CurrencySettingsTests.swift
Labels: Unit Tests, [Type] Bug

#1405 Fixed navigation bar appearance of MFMailComposeViewController on iOS 13
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UINavigationBar+Appearance.swift
Labels: Order Details, [Type] Bug

#1407 Fixed content mode of product's images in Fulfill order
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/ProductDetailsTableViewCell.swift
Labels: Basic Fulfillment, Low hanging fruit, [Type] Bug

#1406 UI fixes to review details screen.
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsCommentTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsCommentTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsHeaderPlainTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsHeaderPlainTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Notifications/ReviewDetailsViewController.swift
Labels: Notifications, Product Reviews, [Type] Enhancement
