Repository woocommerce/woocommerce-ios, pull requests merged in 2019-06, with the labels that each got.

#1011 Merge Release/2.0 into develop
  RELEASE-NOTES.txt
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1009 Purchase Details Mark I: Shipping & Download cells
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductDownload.swift
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Product+CoreDataProperties.swift
  Storage/Storage/Model/ProductDownload+CoreDataClass.swift
  Storage/Storage/Model/ProductDownload+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 16.xcdatamodel/contents
  WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductDownload+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: Product Details, [Type] Enhancement

#1012 Prevent tests for AppRatingManager from logging out inadvertedly
  WooCommerce/WooCommerceTests/Tools/AppRatingManagerTests.swift
Labels: [Type] Bug

#1015 Release notes for 2.0
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#1014 Submit tracks event when loading list of shipment providers from the API
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/ShipmentProvidersViewController.swift
Labels: Order Details, Woo Extensions, [Type] Enhancement

#1016 Purchase Details Mark II: Purchase Note cell
  WooCommerce/Classes/Extensions/String+Helpers.swift
  WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertController+PurchaseNote.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/ReadMoreTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/ReadMoreTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Product Details

#1018 Product Details: bug fix for product image
  WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
Labels: Product Details, [Type] Bug

#1022 Order details: Center “Show billing” and icon horizontally
  WooCommerce/Classes/ViewRelated/Orders/Views/ShowHideSectionFooter.swift
  WooCommerce/Classes/ViewRelated/Orders/Views/ShowHideSectionFooter.xib
Labels: Order Details, [Type] Bug

#1028 Bump Charts to 3.2.0
  Podfile
  Podfile.lock
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
Labels: Tech Debt

#1029 Stats: Tabs are ordered backwards in RTL languages
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/StoreStatsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
Labels: Localization, Store Stats, [Type] Bug

#1023 Settings: Update the store switcher presentation to be a modal overlay
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
Labels: App Settings, [Type] Enhancement

#1032 Download product images and display them everywhere
  Networking/Networking/Remote/ProductsRemote.swift
  WooCommerce/Classes/Extensions/Array+Helpers.swift
  WooCommerce/Classes/ViewModels/OrderItemViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Fulfillment/Cells/PickListTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Fulfillment/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderLoaderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/ProductListViewController.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Internal/Array+Helpers.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
Labels: Basic Fulfillment, Order Details, [Status] Needs Design Review

#1027 Bump WordPressAuthenticator to 1.5.2
  Podfile
  Podfile.lock
Labels: Tech Debt

#1024 Gridicons: All gridicons should be stored in the `UIImage+Woo` extension
  WooCommerce/Classes/Authentication/Epilogue/StoreTableViewCell.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsCommentTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Notifications/NotificationDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/CustomerNoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Fulfillment/Cells/PickListTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/ProductReviewsTableViewCell.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: Architecture, Tech Debt

#1036 Remove feature flag for products
  RELEASE-NOTES.txt
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Fulfillment/Cells/PickListTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Fulfillment/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/ProductListViewController.swift
Labels: Product Details

#1033 Merge release/2.0 into develop
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1039 Merge Release/2.1 into develop
  RELEASE-NOTES.txt
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1042 Merge Release/2.1 into develop
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#1041 Settings: Sync Tracks Opt Out setting
  Networking/Networking/Remote/AccountRemote.swift
  Networking/NetworkingTests/Remote/AccountRemoteTests.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
  WooCommerce/Classes/Yosemite/StoresManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/AccountAction.swift
  Yosemite/Yosemite/Stores/AccountStore.swift
  Yosemite/YosemiteTests/Stores/AccountStoreTests.swift
Labels: App Settings, [Type] Enhancement

#1043 Zendesk: show alert if email is a8c.com/automattic.com
  WooCommerce/Classes/Tools/Developer/DeveloperEmailChecker.swift
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/DeveloperEmailCheckerTests.swift
Labels: [Type] Bug, good first issue

#1051 Dashboard: expose `You have X orders to fulfill` section to VoiceOver
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
Labels: Accessibility, Dashboard, [Type] Bug, good first issue

#1050 Custom shipping provider: fix clipped action button text when no shipping provider search results
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptyListMessageWithActionView.xib
Labels: Accessibility, Basic Fulfillment, [Type] Bug, good first issue

#1045 Notifications: support multiple lines of Share Store button in case of large text
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/OverlayMessageView.xib
Labels: Accessibility, Notifications, [Type] Bug, good first issue

#1053 Merge Release/2.1 into develop
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1048 Settings: fix footer covered for larger font sizes
  WooCommerce/Classes/Extensions/UITableView+FooterHelpers.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TableFooterView.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Accessibility, App Settings, [Type] Bug, good first issue
