Repository woocommerce/woocommerce-ios, pull requests merged in 2019-03, with the labels that each got.

#727 Settings: Change text from "Log out account" to "Log Out"
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
Labels: Enhancement, Low hanging fruit

#730 Update hound to allow 160 characters for a line length, instead of 120.
  .swiftlint.yml
Labels: Tooling

#726 Switch Add button to a spinner in notes editor screen
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
Labels: Bug, Low hanging fruit

#735 Present a Notice after switching a store, informing users that they will only receive notifications from the active store
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
Labels: Enhancement

#734 Hide the keyboard when attempting to commit a note to the backend.
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
Labels: Bug, Epic: Order Details

#737 Set the chevron image to flip upon changing to a RTL language
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
Labels: Bug, Localization

#739 Swift linting
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/AuthenticationConstants.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/Extensions/String+HTML.swift
  WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift
  WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
  WooCommerce/Classes/Tools/Logging/Logging.swift
  WooCommerce/Classes/Tools/Notices/Notice.swift
  WooCommerce/Classes/Tools/StringFormatter/StringStyles.swift
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/NoPeriodDataTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/StoreStatsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+SwitchStore.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+Upgrade.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Notifications/NotificationDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/ProductListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/StarRatingView.swift
  WooCommerce/WooCommerceTests/Extensions/NSDecimalNumberWooTests.swift
Labels: Tech Debt, Tooling

#743 Update copy of Clear Log Button
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogViewController.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
Labels: Low hanging fruit

#732 Order Status Mark III
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Order.swift
  Networking/Networking/Model/OrderStatus.swift
  Networking/Networking/Model/OrderStatusEnum.swift
  Networking/Networking/Remote/ReportRemote.swift
  Networking/NetworkingTests/Mapper/OrderListMapperTests.swift
  Networking/NetworkingTests/Mapper/OrderMapperTests.swift
  Networking/NetworkingTests/Mapper/ReportOrderMapperTests.swift
  Networking/NetworkingTests/Remote/ReportRemoteTests.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UILabel+OrderStatus.swift
  WooCommerce/Classes/Model/OrderStatusKey+Woo.swift
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderSearchViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/Classes/Yosemite/StoresManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/OrderAction.swift
  Yosemite/Yosemite/Actions/OrderStatusAction.swift
  Yosemite/Yosemite/Actions/StatsAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/ReadOnly/OrderStatus+ReadOnlyType.swift
  Yosemite/Yosemite/Model/Storage/Order+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/OrderStatusStore.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
  Yosemite/Yosemite/Stores/StatsStore.swift
  Yosemite/YosemiteTests/Stores/OrderNoteStoreTests.swift
  Yosemite/YosemiteTests/Stores/OrderStatusStoreTests.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: Enhancement

#741 Store picker updates
  RELEASE-NOTES.txt
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Tools/Coordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderLoaderViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Tech Debt, [Type] Bug

#721 Shipment Tracking Mark 4: UI
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Extensions/String+Woo.swift
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/StringWooTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/OrderTrackingTableViewCellTests.swift
Labels: Order Details

#742 Order status Mark IV: manual status change
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderStatusListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderStatusListViewController.xib
  WooCommerce/Classes/ViewRelated/ReusableViews/StatusListTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/StatusListTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Views/StatusListTableViewCellTests.swift
  WooCommerce/WooCommerceTests/Views/SummaryTableViewCellTests.swift
Labels: [Type] Enhancement

#748 Shipment Tracking UI. Enhanced layout of tracking cell
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.xib
Labels: [Status] Needs Design Review, [Type] Enhancement

#750 Fulfill Order: Shipping address is blank
  WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
Labels: [Type] Bug

#754 Issue/751 crash on log out
  RELEASE-NOTES.txt
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/Yosemite/StoresManager.swift
Labels: Priority: HIGH, [Type] Crash

#755 Create a temporary fix: display slugs for unsupported order statuses
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/WooCommerceTests/Views/SummaryTableViewCellTests.swift
Labels: [Type] Bug

#766 Fixed CocoaLumberjack preventing an archive from being created
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Network/Tools/Loader.swift
  Networking/Networking/Remote/Remote.swift
  Podfile
  Podfile.lock
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/CoreData/CoreDataManager.swift
  Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift
  WooCommerce/Classes/Analytics/TracksProvider.swift
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/Tools/Fabric/FabricManager.swift
  WooCommerce/Classes/Tools/ResultsController+UIKit.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/StoreStatsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Stores/OrderNoteStore.swift
  Yosemite/Yosemite/Stores/OrderStatusStore.swift
  Yosemite/Yosemite/Stores/SettingStore.swift
  Yosemite/Yosemite/Stores/ShipmentStore.swift
  Yosemite/Yosemite/Tools/ResultsController.swift
Labels: [Type] Bug

#762 Re-mock commented out unit test in summarytableviewcell tests
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/StatusListTableViewCellTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/SummaryTableViewCellTests.swift
  WooCommerce/WooCommerceTests/Views/SummaryTableViewCellTests.swift
Labels: [Type] Task

#769 Run SwiftLint on sub projects
  .swiftlint.yml
  Networking/Networking/Extensions/KeyedDecodingContainer+Woo.swift
  Networking/Networking/Logging.swift
  Networking/Networking/Mapper/CommentResultMapper.swift
  Networking/Networking/Model/Address.swift
  Networking/Networking/Model/Order.swift
  Networking/Networking/Model/OrderItem.swift
  Networking/Networking/Model/Stats/MIContainer.swift
  Networking/Networking/Model/Stats/OrderStats.swift
  Networking/Networking/Model/Stats/StatGranularity.swift
  Networking/Networking/Network/Tools/AnyCodable.swift
  Networking/Networking/Network/Tools/AnyDecodable.swift
  Networking/Networking/Network/Tools/AnyEncodable.swift
  Networking/Networking/Remote/DevicesRemote.swift
  Networking/Networking/Remote/OrderStatsRemote.swift
  Networking/Networking/Remote/OrdersRemote.swift
  Networking/Networking/Remote/SiteVisitStatsRemote.swift
  Networking/Networking/Remote/TopEarnersStatsRemote.swift
  Networking/Networking/Requests/JetpackRequest.swift
  Networking/NetworkingTests/Mapper/SiteSettingsMapperTests.swift
  Storage/Storage/CoreData/CoreDataIterativeMigrator.swift
  Storage/Storage/CoreData/CoreDataManager.swift
  Storage/Storage/Logging.swift
  Storage/StorageTests/CoreData/CoreDataIterativeMigratorTests.swift
  Yosemite/Yosemite/Actions/NotificationAction.swift
  Yosemite/Yosemite/Internal/Logging.swift
  Yosemite/Yosemite/Model/Storage/Order+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/OrderStatus+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/NotificationStore.swift
  Yosemite/Yosemite/Stores/SettingStore.swift
  Yosemite/Yosemite/Stores/StatsStore.swift
  Yosemite/Yosemite/Tools/EntityListener.swift
  Yosemite/Yosemite/Tools/Internal/FetchedResultsControllerDelegateWrapper.swift
  Yosemite/YosemiteTests/Stores/NotificationStoreTests.swift
  Yosemite/YosemiteTests/Stores/OrderNoteStoreTests.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
  Yosemite/YosemiteTests/Stores/ShipmentStoreTests.swift
  Yosemite/YosemiteTests/Stores/StatsStoreTests.swift
  Yosemite/YosemiteTests/Tools/ResultsControllerTests.swift
Labels: Tech Debt, Tooling

#771 Update SwiftLint to 0.27.0
  Rakefile
Labels: Tooling

#779 Networking: Added the _fields param to orders
  Networking/Networking/Remote/OrdersRemote.swift
  Networking/NetworkingTests/Responses/order.json
  Networking/NetworkingTests/Responses/orders-load-all.json
  WooCommerce.xcworkspace/contents.xcworkspacedata
Labels: [Type] Task

#778 Networking: Added the _fields param to order stats
  Networking/Networking/Remote/OrderStatsRemote.swift
  Networking/NetworkingTests/Responses/order-stats-alt.json
  Networking/NetworkingTests/Responses/order-stats-day.json
  Networking/NetworkingTests/Responses/order-stats-month.json
  Networking/NetworkingTests/Responses/order-stats-week.json
  Networking/NetworkingTests/Responses/order-stats-year.json
  Networking/NetworkingTests/Responses/order-stats.json
Labels: [Type] Task

#777 Networking: Added the _fields param to WC version check
  Networking/Networking/Remote/SiteAPIRemote.swift
  Networking/NetworkingTests/Mapper/SiteAPIMapperTests.swift
  Networking/NetworkingTests/Responses/site-api-no-woo.json
  Networking/NetworkingTests/Responses/site-api.json
  Yosemite/YosemiteTests/Stores/SettingStoreTests.swift
Labels: [Type] Task

#768 Allow the user to enter package tracking details. Mark 1: Networking + Tests
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/NewShipmentTrackingMapper.swift
  Networking/Networking/Mapper/ShipmentTrackingProviderListMapper.swift
  Networking/Networking/Model/ShipmentTrackingProvider.swift
  Networking/Networking/Model/ShipmentTrackingProviderGroup.swift
  Networking/Networking/Remote/ShipmentsRemote.swift
  Networking/NetworkingTests/Remote/ShipmentsRemoteTests.swift
  Networking/NetworkingTests/Responses/shipment_tracking_delete.json
  Networking/NetworkingTests/Responses/shipment_tracking_new.json
  Networking/NetworkingTests/Responses/shipment_tracking_new_custom_provider.json
  Networking/NetworkingTests/Responses/shipment_tracking_providers.json
Labels: Basic Fulfillment, Woo Extensions

#782 Lint fixes (primarily line length violations)
  Networking/Networking/Model/NoteBlock.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+Upgrade.swift
  WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/WooCommerceTests/Tools/StringFormatterTests.swift
  Yosemite/Yosemite/Stores/ShipmentStore.swift
  Yosemite/Yosemite/Stores/StatsStore.swift
Labels: [Type] Task

#783 Fix missing payments status border issue
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Labels: [Status] Needs Design Review, [Type] Bug

#787 Change text from "Total Product Order" to "Total orders"
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.swift
Labels: [Type] Enhancement

#793 Bugfix: background color appears outside of payment status labels
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UILabel+OrderStatus.swift
Labels: [Type] Bug

#792 OrderStatus refresh not implemented on pull-to-refresh
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Labels: [Type] Bug

#788 Add prepareForReuse to Basic cell
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/ReusableViews/BasicTableViewCell.swift
Labels: [Type] Bug

#794 Shipment tracking: dateFormat fix
  Networking/Networking/Extensions/DateFormatter+Woo.swift
  RELEASE-NOTES.txt
Labels: Order Details, [Type] Bug

#796 Fixed DateFormatter dateFormat string typo.
  Networking/Networking/Extensions/DateFormatter+Woo.swift
  RELEASE-NOTES.txt
Labels: [Type] Bug

#780 Allow the user to enter package tracking details. Mark II: Storage
  Networking/Networking/Mapper/ShipmentTrackingProviderListMapper.swift
  Networking/Networking/Model/ShipmentTrackingProvider.swift
  Networking/Networking/Model/ShipmentTrackingProviderGroup.swift
  Networking/Networking/Remote/ShipmentsRemote.swift
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/ShipmentTrackingProvider+CoreDataClass.swift
  Storage/Storage/Model/ShipmentTrackingProvider+CoreDataProperties.swift
  Storage/Storage/Model/ShipmentTrackingProviderGroup+CoreDataClass.swift
  Storage/Storage/Model/ShipmentTrackingProviderGroup+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 12.xcdatamodel/contents
  Storage/Storage/Tools/StorageType+Extensions.swift
  Yosemite/Yosemite/Model/Model.swift
Labels: Basic Fulfillment, Woo Extensions

#772 Networking: Product details
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductListMapper.swift
  Networking/Networking/Mapper/ProductMapper.swift
  Networking/Networking/Model/Dimensions.swift
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductAttributes.swift
  Networking/Networking/Model/Product/ProductCategory.swift
  Networking/Networking/Model/Product/ProductDefaultAttributes.swift
  Networking/Networking/Model/Product/ProductImage.swift
  Networking/Networking/Model/Product/ProductTag.swift
  Networking/Networking/Model/Product/ProductType.swift
  Networking/Networking/Remote/ProductsRemote.swift
  Networking/NetworkingTests/Mapper/ProductListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/product.json
  Networking/NetworkingTests/Responses/products-load-all.json
  WooCommerce/Classes/ViewRelated/ReusableViews/BasicTableViewCell.swift
Labels: [Type] Enhancement

#801 Update comment for translators
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
Labels: Localization

#797 Allow the user to enter package tracking details. Mark III: Yosemite
  Networking/Networking/Model/ShipmentTrackingProvider.swift
  Networking/Networking/Model/ShipmentTrackingProviderGroup.swift
  Networking/Networking/Remote/ShipmentsRemote.swift
  Networking/NetworkingTests/Remote/ShipmentsRemoteTests.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 12.xcdatamodel/contents
  Storage/Storage/Tools/StorageType+Extensions.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/ShipmentAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/ShipmentTrackingProvider+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ShipmentTrackingProviderGroup+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/ShipmentStore.swift
  Yosemite/YosemiteTests/Stores/ShipmentStoreTests.swift
Labels: Basic Fulfillment, Woo Extensions

#803 Update configure to the latest version of the credential files
  .configure
Labels: Tooling

#805 Storage: Product details
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductAttribute.swift
  Networking/Networking/Model/Product/ProductDimension.swift
  Networking/NetworkingTests/Mapper/ProductListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Product+CoreDataClass.swift
  Storage/Storage/Model/Product+CoreDataProperties.swift
  Storage/Storage/Model/ProductAttribute+CoreDataClass.swift
  Storage/Storage/Model/ProductAttribute+CoreDataProperties.swift
  Storage/Storage/Model/ProductCategory+CoreDataClass.swift
  Storage/Storage/Model/ProductCategory+CoreDataProperties.swift
  Storage/Storage/Model/ProductDefaultAttribute+CoreDataClass.swift
  Storage/Storage/Model/ProductDefaultAttribute+CoreDataProperties.swift
  Storage/Storage/Model/ProductDimensions+CoreDataClass.swift
  Storage/Storage/Model/ProductDimensions+CoreDataProperties.swift
  Storage/Storage/Model/ProductImage+CoreDataClass.swift
  Storage/Storage/Model/ProductImage+CoreDataProperties.swift
  Storage/Storage/Model/ProductTag+CoreDataClass.swift
  Storage/Storage/Model/ProductTag+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 12.xcdatamodel/contents
  Storage/Storage/Tools/StorageType+Extensions.swift
Labels: Product Details

#804 Changes to support the latest authenticator pod version.
  Networking/Networking/Settings/Credentials.swift
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/Classes/Yosemite/StoresManager.swift
Labels: Login

#808 Fix some strings that break genstrings
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
Labels: [Type] Bug

#814 Fixed deprecation warnings in PeriodDataVC
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
Labels: [Type] Task

#816 Fix genstrings issues
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Labels: Localization

#802 Feature/add release tooling
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#821 Product details — the Yosemite edition
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductAttribute.swift
  Networking/Networking/Model/Product/ProductDefaultAttribute.swift
  Networking/Networking/Model/Product/ProductDimensions.swift
  Networking/NetworkingTests/Mapper/ProductListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Responses/product.json
  Networking/NetworkingTests/Responses/products-load-all.json
  Storage/Storage/Tools/StorageType+Extensions.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/ReadOnly/Product+ReadOnlyType.swift
  Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductAttribute+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductCategory+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductDefaultAttribute+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductDimensions+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductImage+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductTag+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: Product Details

#824 Make Tracks a lazy init rather than an implied dispatch once
  WooCommerce/Classes/Analytics/TracksProvider.swift
Labels: [Type] Crash
