Repository woocommerce/woocommerce-ios, pull requests merged in 2019-02, with the labels that each got.

#646 Help & Support: Add the app log feature
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/SharingHelper.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Dashboard.storyboard
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogDetailViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Enhancement, Epic: App Settings

#652 Update "friendly string" logic
  WooCommerce/Classes/Extensions/Double+Woo.swift
  WooCommerce/Classes/Extensions/NSDecimalNumber+Helpers.swift
  WooCommerce/Classes/Model/TopEarnerStatsItem+Woo.swift
  WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/DoubleWooTests.swift
  WooCommerce/WooCommerceTests/Extensions/NSDecimalNumberWooTests.swift
  WooCommerce/WooCommerceTests/Tools/CurrencyFormatterTests.swift
Labels: Tech Debt

#654 Dashboard: total sales fixes
  WooCommerce/Classes/Model/OrderStats+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
Labels: Bug

#656 Update comments into Localizable.strings
  WooCommerce/Resources/en.lproj/Localizable.strings
Labels: Tooling

#657 Merge release 1.1 into develop
  WooCommerce/Classes/Model/OrderStats+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
  WooCommerce/Resources/Info.plist
  WooCommerce/Resources/en.lproj/Localizable.strings
Labels: Enhancement

#658 Update localize.py script to handle multiple comments
  Scripts/localize.py
Labels: Tooling

#663 Add translations for promo text
  fastlane/download_metadata.swift
  fastlane/metadata/de-DE/promotional_text.txt
  fastlane/metadata/default/promotional_text.txt
  fastlane/metadata/en-US/promotional_text.txt
  fastlane/metadata/es-ES/promotional_text.txt
  fastlane/metadata/fr-FR/promotional_text.txt
  fastlane/metadata/id/promotional_text.txt
  fastlane/metadata/it/promotional_text.txt
  fastlane/metadata/ja/promotional_text.txt
  fastlane/metadata/ko/promotional_text.txt
  fastlane/metadata/nl-NL/promotional_text.txt
  fastlane/metadata/pt-BR/promotional_text.txt
  fastlane/metadata/ru/promotional_text.txt
  fastlane/metadata/sv/promotional_text.txt
  fastlane/metadata/tr/promotional_text.txt
  fastlane/metadata/zh-Hans/promotional_text.txt
  fastlane/metadata/zh-Hant/promotional_text.txt
Labels: Tooling

#665 Move app version handling to xcconfig files
  WooCommerce/Resources/Info.plist
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  config/Version.Public.xcconfig
  config/WooCommerce.debug.xcconfig
  config/WooCommerce.release.xcconfig
Labels: Tooling

#664 Update secrets placeholders so that build & tests can pass without credentials
  WooCommerce/Credentials/Templates/ApiCredentials-Template.swift
  WooCommerce/Credentials/Templates/InfoPlist-Template.h
Labels: Tooling

#666 Add CircleCI config
  .circleci/config.yml
Labels: Tooling

#668 Notifications: Gridicon update .menus to .filter
  WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
Labels: Bug

#660 Quick site select
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/Yosemite/StoresManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift
  Yosemite/Yosemite/Actions/StatsAction.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
  Yosemite/Yosemite/Stores/StatsStore.swift
Labels: Enhancement, Epic: App Settings

#671 Changes OrderItem.quantity from Int to Decimal
  Networking/Networking/Model/OrderItem.swift
  Networking/NetworkingTests/Mapper/OrderMapperTests.swift
  Networking/NetworkingTests/Responses/order.json
  Networking/NetworkingTests/Responses/orders-load-all.json
  RELEASE-NOTES.txt
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/CoreData/CoreDataIterativeMigrator.swift
  Storage/Storage/CoreData/CoreDataManager.swift
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Model 9 to Model 10.xcmappingmodel/xcmapping.xml
  Storage/Storage/Model/OrderItem+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 10.xcdatamodel/contents
  Storage/StorageTests/CoreData/CoreDataIterativeMigratorTests.swift
  WooCommerce/Classes/ViewModels/OrderItemViewModel.swift
  Yosemite/Yosemite/Model/Storage/OrderItem+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: Bug

#675 Localise tests covering number abbreviations
  WooCommerce/WooCommerceTests/Extensions/DoubleWooTests.swift
  WooCommerce/WooCommerceTests/Extensions/NSDecimalNumberWooTests.swift
  WooCommerce/WooCommerceTests/Tools/CurrencyFormatterTests.swift
Labels: Bug, Tooling

#673 Add ellipsis to notifications when the content is truncated
  WooCommerce/Classes/Extensions/NSParagraphStyle+Woo.swift
  WooCommerce/Classes/Tools/StringFormatter/StringStyles.swift
  WooCommerce/WooCommerceTests/Tools/StringFormatterTests.swift
Labels: Bug

#680 Change selected bar color in charts
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
Labels: Enhancement, Epic: Dashboard, Low hanging fruit

#681 Present a notice when loading the dashboard data fails
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/StoreStatsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
Labels: Epic: Dashboard, Low hanging fruit

#683 Tracks event name changed from `store` to `site`
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
Labels: Bug

#685 Force a logout when users tap “Try another account” in the store picker
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
Labels: Bug, Low hanging fruit

#687 Add Retry functionality to failed order fulfilment and failed adding notes
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
Labels: Epic: Basic Fulfillment, Epic: Order Details, Low hanging fruit

#691 Replace BuddyBuild status badge with CircleCI badge
  README.md
Labels: Documentation

#692 Shipment Tracking Mark 1: Networking framework + tests
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Extensions/CodingUserInfoKey+Woo.swift
  Networking/Networking/Extensions/DateFormatter+Woo.swift
  Networking/Networking/Mapper/ShipmentTrackingListMapper.swift
  Networking/Networking/Model/DotcomError.swift
  Networking/Networking/Model/ShipmentTracking.swift
  Networking/Networking/Remote/ShipmentsRemote.swift
  Networking/NetworkingTests/Mapper/ShipmentTrackingListMapperTests.swift
  Networking/NetworkingTests/Remote/ShipmentsRemoteTests.swift
  Networking/NetworkingTests/Remote/SiteAPIRemoteTests.swift
  Networking/NetworkingTests/Responses/restnoroute_error.json
  Networking/NetworkingTests/Responses/shipment_tracking_empty.json
  Networking/NetworkingTests/Responses/shipment_tracking_multiple.json
  Networking/NetworkingTests/Responses/shipment_tracking_plugin_not_active.json
  Networking/NetworkingTests/Responses/shipment_tracking_single.json
  Networking/NetworkingTests/Validators/DotcomValidatorTests.swift
Labels: Epic: Order Details

#695 Site picker fix for inadvertent logout
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
Labels: Bug

#690 Present Fancy alert informing of store switcher and name of store in My Store tab
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Extensions/UIFont+Helpers.swift
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+SwitchStore.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Resources/Images.xcassets/woo-store-switcher.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-store-switcher.imageset/iOS-store-switcher.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Low hanging fruit, Task

#694 Add version to release-notes.txt
  RELEASE-NOTES.txt
Labels: Tooling

#696 Order Details: Display Address unless every field is empty
  Networking/Networking/Model/Address.swift
  RELEASE-NOTES.txt
Labels: Bug, Epic: Order Details, Low hanging fruit

#697 Remove feature flag for app ratings
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/Tools/AppRatings/AppRatingManager.swift
  WooCommerce/WooCommerceTests/System/FeatureFlagTests.swift
Labels: Low hanging fruit

#702 Default Dashboard title to "My Store" when the view controller is loaded without an available store
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: Bug

#701 Shipment Tracking Mark 2: Storage framework updates
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/CoreData/CoreDataIterativeMigrator.swift
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Model 9 to Model 10.xcmappingmodel/xcmapping.xml
  Storage/Storage/Model/ShipmentTracking+CoreDataClass.swift
  Storage/Storage/Model/ShipmentTracking+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 10.xcdatamodel/contents
  Storage/Storage/Model/WooCommerceModelV9toV10.xcmappingmodel/xcmapping.xml
  Storage/Storage/Tools/StorageType+Extensions.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/ReadOnly/ShipmentTracking+ReadOnlyType.swift
  Yosemite/Yosemite/Model/Storage/ShipmentTracking+ReadOnlyConvertible.swift
Labels: Epic: Order Details

#704 Order Status Mark 1: Add new entity and change attribute name
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ReportOrderTotalsMapper.swift
  Networking/Networking/Model/Order.swift
  Networking/Networking/Model/OrderStatusKey.swift
  Networking/Networking/Remote/OrdersRemote.swift
  Networking/Networking/Remote/ReportRemote.swift
  Networking/NetworkingTests/Mapper/OrderListMapperTests.swift
  Networking/NetworkingTests/Mapper/OrderMapperTests.swift
  Networking/NetworkingTests/Mapper/ReportOrderMapperTests.swift
  Networking/NetworkingTests/Remote/OrdersRemoteTests.swift
  Networking/NetworkingTests/Remote/ReportRemoteTests.swift
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Order+CoreDataProperties.swift
  Storage/Storage/Model/OrderStatus+CoreDataClass.swift
  Storage/Storage/Model/OrderStatus+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 10.xcdatamodel/contents
  Storage/Storage/Model/WooCommerceModelV9toV10.xcmappingmodel/xcmapping.xml
  WooCommerce/Classes/Extensions/UILabel+OrderStatus.swift
  WooCommerce/Classes/Model/OrderStatusKey+Woo.swift
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/OrderAction.swift
  Yosemite/Yosemite/Actions/StatsAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/Order+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
  Yosemite/Yosemite/Stores/StatsStore.swift
  Yosemite/YosemiteTests/Stores/OrderNoteStoreTests.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: Enhancement

#711 Switch to CocoaLumberjack/Swift pod to get all the logging
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Logging.swift
  Podfile
  Podfile.lock
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Logging.swift
  WooCommerce/Classes/Tools/Logging/CocoaLumberjack.swift
  WooCommerce/Classes/Tools/Logging/Logging.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Internal/Logging.swift
Labels: Tech Debt

#710 Shipment Tracking Mark 3: Yosemite updates + tests
  Storage/Storage/Tools/StorageType+Extensions.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/ShipmentAction.swift
  Yosemite/Yosemite/Stores/ShipmentStore.swift
  Yosemite/YosemiteTests/Stores/ShipmentStoreTests.swift
Labels: Epic: Order Details

#716 Fix threading issue causing crash
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: Crasher

#720 Fix lint errors
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderLoaderViewController.swift
Labels: Tooling

#723 Remove Danger: Dangerfile, gem and CircleCI job
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  README.md
  buddybuild_postbuild.sh
Labels: Tooling

#725 Lint config updated for vertical_whitespace
  .swiftlint.yml
Labels: Tooling
