Repository woocommerce/woocommerce-ios, pull requests merged in 2019-01, with the labels that each got.

#609 Change right nav bar button from .menu to .filter grid icon.
  Podfile
  Podfile.lock
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Labels: Bug

#622 Add the Promotional Text field to AppStoreStrings.pot
  WooCommerce/Resources/AppStoreStrings.pot
Labels: Tooling

#624 Mark the app as only using exempt encryption
  WooCommerce/Resources/Info.plist
Labels: Tooling

#623 Ship 1.0.1
  WooCommerce/Resources/Info.plist
  fastlane/Deliverfile
Labels: Tooling

#610 Settings > Help: row titles and version number alignment
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
Labels: Bug

#608 Add a secrets Swift Template
  Scripts/build-phases/generate-credentials.sh
  WooCommerce/Credentials/Templates/ApiCredentials-Template.swift
  WooCommerce/Credentials/Templates/InfoPlist-Template.h
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/ZendeskManagerTests.swift
Labels: Tooling

#628 Feature/add release notes
  .github/PULL_REQUEST_TEMPLATE.md
  RELEASE-NOTES.txt
  WooCommerce/RELEASE-NOTES.md
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Tooling

#629 Add source files for app store metadata and related lane
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
  fastlane/Fastfile
  fastlane/actions/ios_update_metadata_source.rb
  fastlane/appstoreres/metadata/source/app_store_promo_text.txt
  fastlane/appstoreres/metadata/source/description.txt
  fastlane/appstoreres/metadata/source/keywords.txt
  fastlane/appstoreres/metadata/source/subtitle.txt
Labels: Tooling

#616 Hide orders that have a `createdDate` that exists in the future.
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Labels: Bug

#630 Dashboard: localize chart axis and chart markers
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/DateFormatter+Helpers.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
Labels: Localization

#632 When no payment method exists, hide payment summary from payment section
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Labels: Bug

#634 Fixes some localization issues on the Order List and Notification screens
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Labels: Localization

#635 Add promo strings for screenshots
  WooCommerce/Resources/AppStoreStrings.pot
  fastlane/Fastfile
  fastlane/appstoreres/metadata/source/promo_screenshot_1.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_1_b.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_2.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_3.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_4.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_5.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_6.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_7.txt
  fastlane/appstoreres/metadata/source/promo_screenshot_8.txt
Labels: Tooling

#637 Restore displaying taxes, even when amounts are zero.
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewModels/OrderItemViewModel.swift
Labels: Bug

#639 Login: Add help button to store picker screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.swift
  WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.xib
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
Labels: Enhancement

#642 Change Tracks string value to match spreadsheet
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
Labels: Bug

#643 Store picker: don't allow cell selection for a single store
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
Labels: Bug

#649 Dashboard: Update recency message to match designs
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift
Labels: Bug, Localization

#651 Reduce number of conflicts in RELEASE-NOTES.txt
  .gitattributes
Labels: Tooling
