Repository woocommerce/woocommerce-ios, pull requests merged in 2020-04, with the labels that each got.

#2065 Removed load product visibility check
  WooCommerce/Classes/ViewRelated/Products/ProductLoaderViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: Add/Edit Products, [Type] Bug

#2066 Allow sending of initial events in KeyboardFrameObserver
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
  WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift
  WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/ServiceLocatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardFrameObserverTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardStateProviderTests.swift
Labels: Product List

#2068 Updated Wormholy to v.1.5.2 which is fully compatible with Swift 5.2 and Xcode 11.4
  Podfile
  Podfile.lock
Labels: Low hanging fruit, Tech Debt

#2059 [Categories] Add Basic ProductCategory Store
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductCategoryListMapper.swift
  Networking/Networking/Remote/ProductCategoriesRemote.swift
  Networking/NetworkingTests/Mapper/ProductCategoyListMapperTests.swift
  Networking/NetworkingTests/Remote/ProductCategoriesRemoteTests.swift
  Networking/NetworkingTests/Responses/categories-all.json
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/ProductCategoryAction.swift
  Yosemite/Yosemite/Stores/ProductCategoryStore.swift
  Yosemite/YosemiteTests/Stores/ProductCategoryStoreTests.swift
Labels: Add/Edit Products

#2039 Update to shared lanes
  Gemfile.lock
  fastlane/Pluginfile
  fastlane/actions/ios_update_metadata_source.rb
Labels: Tooling

#2076 Fix build warnings on `develop`
  WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardStateProviderTests.swift
Labels: Tech Debt

#2075 Update media POST endpoint to v1.1 with error handling
  Networking/Networking/Remote/MediaRemote.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
Labels: Add/Edit Products

#2060 Product image upload: WP media library UI integration
  Networking/Networking/Model/Media/Media.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Media/Media+WPMediaAsset.swift
  WooCommerce/Classes/ViewRelated/Products/Media/MediaPickingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Media/MediaType+WPMediaType.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryImagePickerViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryImagePickerViewController.xib
  WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryPickerDataSource.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductImageActionHandlerTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Tools/Media/Media+MediaType.swift
  Yosemite/Yosemite/Tools/Media/Media+ProductImage.swift
  Yosemite/Yosemite/Tools/Media/MediaType.swift
  Yosemite/YosemiteTests/Tools/Media/Media+Equatable.swift
  Yosemite/YosemiteTests/Tools/Media/Media+MediaTypeTests.swift
  Yosemite/YosemiteTests/Tools/Media/Media+ProductImageTests.swift
  Yosemite/YosemiteTests/Tools/Media/MediaTypeTests.swift
Labels: Add/Edit Products

#2048 Update hotfix tooling
  fastlane/Fastfile
Labels: Tooling

#2080 Fix build error on `develop`
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
Labels: Tech Debt

#2070 Add NSMutableAttributedString.replaceFirstOccurrence
  WooCommerce/Classes/Extensions/NSMutableAttributedString+Helpers.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/NSMutableAttributedStringHelperTests.swift
Labels: Product List

#2077 Product Settings: implemented Featured and Catalog Visibility
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductCatalogVisibility.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Catalog Visibility/ProductCatalogVisibilityViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Catalog Visibility/ProductCatalogVisibilityViewController.xib
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsViewModelTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Products/ProductSettings.swift
  Yosemite/Yosemite/Model/Updaters/ProductUpdater.swift
  Yosemite/YosemiteTests/Model/Updaters/Product+UpdaterTestCases.swift
Labels: Add/Edit Products, [Status] Needs Design Review

#2071 [Auth] Remove the `.show2FA` segue and navigate programmatically
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#2092 Parse the stats v4 dates with the site time zone instead of device time zone
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.swift
  Yosemite/Yosemite/Model/Extensions/OrderStatsV4Interval+Date.swift
  Yosemite/YosemiteTests/Model/Extensions/OrderStatsV4Interval+DateTests.swift
Labels: Store Stats, [Type] Crash

#2094 Product Settings: edit the product slug (product's URL)
  Networking/Networking/Model/Product/Product.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Slug/ProductSlugViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Slug/ProductSlugViewController.xib
  WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsViewModelTests.swift
  Yosemite/Yosemite/Model/Products/ProductSettings.swift
  Yosemite/Yosemite/Model/Updaters/ProductUpdater.swift
  Yosemite/YosemiteTests/Model/Updaters/Product+UpdaterTestCases.swift
Labels: Add/Edit Products

#2100 Merge 4.0 code freeze to develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#2078 Add Empty State View for Products and Orders Search
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptySearchResultsViewController/EmptySearchResultsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptySearchResultsViewController/EmptySearchResultsViewController.xib
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.xib
  WooCommerce/Resources/Images.xcassets/woo-empty-search-results.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-empty-search-results.imageset/woo-empty-search-results-dark.pdf
  WooCommerce/Resources/Images.xcassets/woo-empty-search-results.imageset/woo-empty-search-results-light.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: Order List, Product List

#2067 Add Dark Mode support to the open-source licenses
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/LicensesViewController.swift
  WooCommerce/Resources/HTML/licenses.html
Labels: [Type] Enhancement

#2101 Fixed SettingTitleAndValueTableViewCell that truncate the title
  WooCommerce/Classes/ViewRelated/ReusableViews/SettingTitleAndValueTableViewCell.xib
Labels: [Type] Bug

#2105 Use Aztec.HTMLParser to fix NSAttributedString crash
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking.xcodeproj/xcshareddata/xcbaselines/B557D9EB209753AA005962F4.xcbaseline/DBFB8993-CF1F-4D62-8E43-E9560E0ACF03.plist
  Networking/Networking.xcodeproj/xcshareddata/xcbaselines/B557D9EB209753AA005962F4.xcbaseline/Info.plist
  Networking/Networking/Extensions/String+HTML.swift
  Networking/NetworkingTests/Extensions/String+HTMLTests.swift
  Networking/NetworkingTests/Testing/XCTestCase+Wait.swift
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Order List, Product List, Product Reviews

#2102 Added "View product in store" option in Products "More" Action Sheet
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: Add/Edit Products

#2111 Merge 4.0 release notes to develop
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#2118 Merge release 4.0 into develop
  Podfile
  Podfile.lock
  WooCommerce/Resources/en.lproj/Localizable.strings
Labels: Releases

#2106 Fix memory leaks from view controllers - product form, Aztec, search, order details
  WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
  WooCommerce/Classes/ViewRelated/Editor/FormatBar/Command/Implementation/AztecLinkFormatBarCommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ManualTrackingViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ShipmentProvidersViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
  WooCommerce/Classes/ViewRelated/Text View Screen/TextViewViewController.swift
Labels: Tech Debt, [Type] Bug

#2107 Edit Product > Shipping Settings: retrieve shipping class and block tap action before completion
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Responses/product.json
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: Add/Edit Products, [Type] Bug

#2112 [Manage Categories] Shows simple/basic Category Selector screen
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/Cell/ProductCategoryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/Cell/ProductCategoryTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewController.xib
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Categories/ProductCategoryListViewModelTests.swift
Labels: Add/Edit Products

#2127 Only request Photo Library permission when adding images from Photo Library in image upload
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/DefaultProductUIImageLoader.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductUIImageLoaderTests.swift
Labels: Add/Edit Products, [Type] Bug

#2110 shouldPop: delegate method is not called on simulators with iOS 13.4
  WooCommerce/Classes/Extensions/UINavigationController+Woo.swift
Labels: [Type] Bug

#2114 Image Upload: make an image request cancellable
  Networking/Networking/Model/Media/Media.swift
  WooCommerce/Classes/Tools/ImageService/DefaultImageService.swift
  WooCommerce/Classes/Tools/ImageService/ImageDownloader.swift
  WooCommerce/Classes/Tools/ImageService/ImageService.swift
  WooCommerce/Classes/Tools/ImageService/KingfisherImageDownloader+ImageDownloadable.swift
  WooCommerce/Classes/ViewRelated/Editor/AztecTextViewAttachmentHandler.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/ProductImageCollectionViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesCollectionViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Media/CancellableMedia.swift
  WooCommerce/Classes/ViewRelated/Products/Media/DefaultProductUIImageLoader.swift
  WooCommerce/Classes/ViewRelated/Products/Media/Media+WPMediaAsset.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductUIImageLoader.swift
  WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryImagePickerViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryPickerDataSource.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockImageDownloader.swift
  WooCommerce/WooCommerceTests/Mockups/MockKingfisherImageDownloader.swift
  WooCommerce/WooCommerceTests/Tools/DefaultImageServiceTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductUIImageLoaderTests.swift
  Yosemite/YosemiteTests/Tools/Media/Media+Equatable.swift
Labels: Add/Edit Products

#2131 Fix test cases in `CurrencyFormatterTests` from locale, singleton usage, and negative value with RTL
  WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift
  WooCommerce/WooCommerceTests/Tools/CurrencyFormatterTests.swift
Labels: Tech Debt, Unit Tests

#2134 Update README to recommend rake dependencies
  README.md
Labels: Documentation

#2129 Merge 4.0.0.1 to develop
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Responses/product.json
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
  config/Version.Public.xcconfig
Labels: Releases

#2130 [Manage Categories] Category selector screen pagination strategy
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/NetworkingTests/Responses/categories-empty.json
  Networking/NetworkingTests/Responses/categories-extra.json
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Categories/ProductCategoryListViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductCategoryAction.swift
  Yosemite/Yosemite/Stores/ProductCategoryStore.swift
  Yosemite/YosemiteTests/Stores/ProductCategoryStoreTests.swift
Labels: Add/Edit Products

#2126 Image Upload: update navigation UX
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageStatus.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductImageActionHandlerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductImageStatus+HelpersTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductImageStatus+ImagesTests.swift
Labels: Add/Edit Products

#2137 Orders → Move ResultsController to ViewModel
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
Labels: Order List

#2140 Strip geolocation data from images for upload by default
  Yosemite/Yosemite/Tools/Media/MediaExportService.swift
Labels: Add/Edit Products

#2135 Thread safety for image statuses in `ProductImageActionHandler`
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductImageActionHandlerTests.swift
Labels: Add/Edit Products, Tech Debt

#2125 Fix localisation issues
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#2143 UL&S: Remove .showSelfHostedLogin segue
  Podfile
  Podfile.lock
Labels: Login, [Type] Enhancement

#2141 Image upload: attach the product ID to an image uploaded from edit product
  Networking/Networking/Network/Network.swift
  Networking/Networking/Remote/MediaRemote.swift
  Networking/NetworkingTests/Remote/MediaRemoteTests.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
  WooCommerce/WooCommerceTests/Mockups/MockMediaStoresManager.swift
  Yosemite/Yosemite/Actions/MediaAction.swift
  Yosemite/Yosemite/Stores/MediaStore.swift
  Yosemite/YosemiteTests/Stores/MediaStoreTests.swift
Labels: Add/Edit Products

#2139 [Manage Categories] Build and Render Category Selector tree view
  Networking/Networking/Model/Product/ProductCategory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/Cell/ProductCategoryTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/Cell/ProductCategoryTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryCellViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryViewModelBuilder.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcbaselines/B56DB3DC2049BFAA00D4AA8E.xcbaseline/1106C823-AE63-4DFC-B3B6-09B6413DA78A.plist
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcbaselines/B56DB3DC2049BFAA00D4AA8E.xcbaseline/Info.plist
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Categories/ProductCategoryListViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Categories/ProductCategoryViewModelBuilderTests.swift
Labels: Add/Edit Products, [Status] Needs Design Review

#2146 Handled the Swipe Back gesture that triggers the "Discard Changes" action sheet
  WooCommerce/Classes/Extensions/UINavigationController+Woo.swift
  WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
  WooCommerce/Classes/ViewRelated/Text View Screen/TextViewViewController.swift
Labels: Add/Edit Products

#2153 Updated Wormholy to version 1.6.0
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#2151 UL&S: Remove .showWPUsernamePassword segue
  Podfile
  Podfile.lock
Labels: Login, [Type] Enhancement

#2150 Order List → Support Future Orders
  Networking/Networking/Remote/OrdersRemote.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/Model/Age.swift
  WooCommerce/Classes/Model/StorageOrder+Woo.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift
  WooCommerce/WooCommerceTests/Model/AgeTests.swift
  WooCommerce/WooCommerceTests/Testing/Calendar+Extensions.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
  Yosemite/Yosemite/Actions/OrderAction.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
Labels: Order List

#2159 Products: present the keyboard in screens with only one textfield
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Purchase Note/ProductPurchaseNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Slug/ProductSlugViewController.swift
Labels: Add/Edit Products, [Type] Enhancement

#2158 Products: tapping on row begin editing of the text field
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/ReusableViews/TitleAndTextFieldTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/UnitInputTableViewCell.swift
Labels: Add/Edit Products, [Type] Bug

#2152 Merge 4.0 final into develop
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/description.txt
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/marketing_url.txt
  fastlane/metadata/ar-SA/promotional_text.txt
  fastlane/metadata/ar-SA/release-notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/description.txt
  fastlane/metadata/he/keywords.txt
  fastlane/metadata/he/marketing_url.txt
  fastlane/metadata/he/promotional_text.txt
  fastlane/metadata/he/release-notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#2163 Merge 4.0 final into release 4.1
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  fastlane/metadata/ar-SA/description.txt
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/marketing_url.txt
  fastlane/metadata/ar-SA/promotional_text.txt
  fastlane/metadata/ar-SA/release-notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/description.txt
  fastlane/metadata/he/keywords.txt
  fastlane/metadata/he/marketing_url.txt
  fastlane/metadata/he/promotional_text.txt
  fastlane/metadata/he/release-notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#2154 Bottom Sheet: add bottom sheet code from WPiOS
  WooCommerce/Classes/ViewRelated/BottomSheet/BottomSheetViewController+Constants.swift
  WooCommerce/Vendors/WPiOS-BottomSheet/BottomSheetAnimationController.swift
  WooCommerce/Vendors/WPiOS-BottomSheet/BottomSheetViewController.swift
  WooCommerce/Vendors/WPiOS-BottomSheet/DrawerPresentationController.swift
  WooCommerce/Vendors/WPiOS-BottomSheet/GripView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#2098 Stats v4: fix the time range for "This Week" tab considering daily saving time change
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/Date+StartAndEnd.swift
  WooCommerce/WooCommerceTests/Extensions/DateStartAndEndTests.swift
Labels: Store Stats, [Type] Bug

#2155 Bottom Sheet: add generic bottom sheet list selector UI
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorSectionHeaderView.swift
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorSectionHeaderView.xib
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewController+DrawerPresentable.swift
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewController.xib
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewProperties.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#2156 Bottom Sheet: Products tab sort options
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Products/BottomSheetListSelector/ProductsSortOrderBottomSheetListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/UIAlertController+SortProducts.swift
  WooCommerce/Vendors/WPiOS-BottomSheet/BottomSheetViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/BottomSheetListSelector/ProductsSortOrderBottomSheetListSelectorCommandTests.swift
Labels: Product List, [Type] Enhancement

#2162 Array utility to get the IndexPath of a Section that conform to RowIterable
  WooCommerce/Classes/Extensions/Array+IndexPath.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Purchase Note/ProductPurchaseNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Slug/ProductSlugViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/ArrayIndexPathTests.swift
Labels: Tech Debt, [Type] Enhancement

#2172 Merge 4.1 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#2180 Make sure PushNotificationManagerTests test objects are cleared
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
Labels: Tech Debt

#2177 Fix Age.from returning `today` instead of `upcoming`
  WooCommerce/Classes/Model/Age.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
  WooCommerce/WooCommerceTests/Model/AgeTests.swift
Labels: Order List

#2178 Refresh Order List on app activation
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
Labels: Order List

#2181 Fixed release notes for release 4.2
  RELEASE-NOTES.txt
Labels: Low hanging fruit

#2047 Feature/beta builds on ci
  .circleci/config.yml
  fastlane/Fastfile
Labels: Tooling

#2182 Merge 4.1 release notes to develop
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#2144 Product images header shouldn't scroll back on image status updates
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderTableViewCell.swift
Labels: Add/Edit Products

#2193 Merge 4.1.0.1 to develop
  config/Version.Public.xcconfig
Labels: Releases

#2194 Docs: Add Coding Guidelines about Structs vs Classes
  docs/README.md
Labels: Documentation

#2191 Add PublishSubject observable
  WooCommerce/Classes/Tools/Observables/Observable.swift
  WooCommerce/Classes/Tools/Observables/ObservationToken.swift
  WooCommerce/Classes/Tools/Observables/Observer.swift
  WooCommerce/Classes/Tools/Observables/PublishSubject.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/Observables/PublishSubjectTests.swift
Labels: Architecture

#2192 Order List → Refresh When Receiving a new Order Notification While in the Foreground
  RELEASE-NOTES.txt
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/ServiceLocator/ForegroundNotification.swift
  WooCommerce/Classes/ServiceLocator/PushNotesManager.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockPushNotificationsManager.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
Labels: Order List

#2203 Refactor OrderSearchStarterViewModel for Testability
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Search/Order/OrderSearchStarterViewModelTests.swift
Labels: Order List

#2201 UL&S: Remove .startMagicLinkFlow segue
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#2195 Update `ListSelectorViewController` for usage in products tab filtering
  WooCommerce/Classes/ViewRelated/ListSelector/ListSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/ListSelector/ListSelectorViewProperties.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/ProductBackordersSettingListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/ProductStockStatusListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/ProductTaxStatusListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/List Selector Data Source/ProductStatusSettingListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductBackordersSettingListSelectorCommandTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductStatusSettingListSelectorCommandTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductStatusSettingListSelectorDataSourceTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductStockStatusListSelectorCommandTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductTaxStatusListSelectorCommandTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductTaxStatusListSelectorDataSourceTests.swift
Labels: Add/Edit Products

#2207 Product Settings: Menu Order now allow negative values
  WooCommerce/Classes/Tools/UnitInputFormatter/IntegerInputFormatter.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Menu Order/ProductMenuOrderViewController.swift
  WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift
Labels: Add/Edit Products, [Type] Bug

#2208 Orders → Search: Show Status Totals
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/NumberFormatter+LocalizedOrNinetyNinePlus.swift
  WooCommerce/Classes/ViewModels/MainTabViewModel.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/NumberFormatter+LocalizedOrNinetyNinePlusTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Order/OrderSearchStarterViewModelTests.swift
Labels: Order List, [Status] Needs Design Review

#2197 LoginPrologue: Remove "Jetpack" text from Log In button
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.xib
Labels: Login, [Status] Needs Design Review
