Repository woocommerce/woocommerce-ios, pull requests merged in 2020-03, with the labels that each got.

#1916 `ColumnFlowLayout`: fix `UICollectionViewFlowLayout` warnings
  WooCommerce/Classes/ViewRelated/ReusableViews/ColumnFlowLayout.swift
Labels: Add/Edit Products

#1914 Image Upload: rename `ProductImagesService` & `ProductImagesProvider`
  WooCommerce/Classes/Tools/ObservationToken.swift
  WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesCollectionViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/DefaultProductUIImageLoader.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImageViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductUIImageLoader.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockProductImagesProvider.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductImageActionHandlerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductUIImageLoaderTests.swift
Labels: Add/Edit Products, Tech Debt

#1918 Make reviewer_avatar_urls optional
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Product/ProductReview.swift
  Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift
  Networking/NetworkingTests/Responses/reviews-missing-avatar-urls.json
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Notifications/ReviewDetailsViewController.swift
  Yosemite/Yosemite/Model/Storage/ProductReview+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift
Labels: Product Reviews

#1921 Turned on edit products editing feature behind switch
  RELEASE-NOTES.txt
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
Labels: Add/Edit Products

#1920 Merge 3.7 final into develop
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1924 Update Nokogiri to fix a warning
  Gemfile.lock
Labels: Tooling

#1900 WP media library: Networking & Yosemite layers
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/MediaRemote.swift
  Networking/NetworkingTests/Remote/MediaRemoteTests.swift
  Networking/NetworkingTests/Responses/media-library.json
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/MediaAction.swift
  Yosemite/Yosemite/Stores/MediaStore.swift
  Yosemite/YosemiteTests/Stores/MediaStoreTests.swift
  Yosemite/YosemiteTests/Tools/Media/Media+Equatable.swift
Labels: Add/Edit Products, Networking, Yosemite

#1919 Reviews tab: move view controllers away from Storyboard
  WooCommerce/Classes/ViewRelated/Base.lproj/Main.storyboard
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Notifications/Notifications.storyboard
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Tech Debt

#1931 Order List: fixed clipped order status
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Labels: Order List, [Type] Bug

#1927 Migrating to WKWebView, after that Apple stop accepting apps that use UIWebView
  WooCommerce/Classes/Tools/UserAgent.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/UserAgentTests.swift
Labels: Tech Debt

#1939 Fixed tests that are failing because "Switch must be exhaustive"
  WooCommerce/WooCommerceTests/Mockups/MockMediaStoresManager.swift
Labels: Broken Tests, Unit Tests

#1940 Fixed launch screen stretched
  RELEASE-NOTES.txt
  WooCommerce/Resources/Assets.xcassets/LaunchLogo.imageset/woo-icon-120x120.pdf
  WooCommerce/Resources/Base.lproj/LaunchScreen.storyboard
Labels: [Status] Needs Design Review, [Type] Bug

#1941 Merge 3.8 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1942 Update Tracks
  Podfile.lock
Labels: Tooling

#1950 Add Tracking: changed all the occurences of "Shipping Provider" to "Shipping Carrier"
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift
  WooCommerce/Classes/ViewModels/ShippingProvidersViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ManualTrackingViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ShipmentProvidersViewController.swift
Labels: Order Details, [Status] Needs Design Review

#1970 Merge 3.8 release notes into develop
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#1930 Updates to Zendesk 5.0 SDK and CocoaPods 1.9.1
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Support, Tech Debt

#1971 Products Search: show the editable version of a product
  WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
Labels: Add/Edit Products, [Type] Bug

#1969 Edit Product: fixed the discard changes prompt on iPad
  WooCommerce/Classes/Extensions/UIAlertController+Helpers.swift
Labels: Add/Edit Products, [Type] Bug

#1972 Edit Products: fixed inconsistent case in error message title
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: Add/Edit Products, [Type] Bug

#1977 Edit Products: show discard changes action sheet if the product has outstanding changes when navigating away
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: Add/Edit Products

#1982 Edit Product: allow empty title
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: Add/Edit Products, [Type] Bug

#1973 [Dark Mode] Fixes tab-bar invisible border in iOS 13.1
  WooCommerce/Classes/Extensions/UITabBar+Appearance.swift
Labels: Dark Mode

#1987 Update ReviewsViewController tabbar-item icon
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: Product Reviews

#1984 Update Gridicons pod to 0.20-beta
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#1994 Update Tracks to use the latest available version, 0.4.4-beta.2
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#1995 Update WordPressUI pod to 1.5.2-beta.1
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#1997 Update Authenticator, WordPressShared, and Alamofire
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#1979 Edit Products: fix unexpected discard changes prompt
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
Labels: Add/Edit Products, [Type] Bug

#1991 Attempt to fix crash after visiting the tax class list selector screen a few times
  Yosemite/Yosemite/Actions/TaxClassAction.swift
  Yosemite/Yosemite/Stores/TaxClassStore.swift
  Yosemite/YosemiteTests/Stores/TaxClassStoreTests.swift
Labels: Add/Edit Products, [Type] Crash

#1989 Edit Product: "update" CTA should only be displayed when a change is made
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: Add/Edit Products, [Status] Needs Design Review, [Type] Bug

#1996 Fixed decimal type in price comparison to check if product data has changed
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: Add/Edit Products, [Type] Bug

#1999 Edit Product Sale Price: revised the date pickers behavior
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
Labels: Add/Edit Products

#1986 Update colors for Aztec HTML text view and blockquote text
  WooCommerce/Classes/Styles/UIColor+SemanticColors.swift
  WooCommerce/Classes/ViewRelated/Editor/AztecUIConfigurator.swift
Labels: Add/Edit Products, [Type] Bug

#2005 Allow editing a link on tap in Aztec
  WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
Labels: Add/Edit Products, [Type] Bug

#2006 Updated dependencies that are using UIWebView
  Podfile
  Podfile.lock
Labels: Tech Debt

#2004 Update Top-Performers cell to match the Product-Tab design
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.xib
Labels: Dashboard, [Status] Needs Design Review

#2011 Merge 3.8 rc 2 into develop
  WooCommerce/Classes/Extensions/UIAlertController+Helpers.swift
  WooCommerce/Classes/Styles/UIColor+SemanticColors.swift
  WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
  WooCommerce/Classes/ViewRelated/Editor/AztecUIConfigurator.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
  Yosemite/Yosemite/Actions/TaxClassAction.swift
  Yosemite/Yosemite/Stores/TaxClassStore.swift
  Yosemite/YosemiteTests/Stores/TaxClassStoreTests.swift
  config/Version.Public.xcconfig
Labels: Releases

#2010 Update main project to use Gridicons 1.0-beta.1 pod
  Podfile
  Podfile.lock
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Editor/FormatBar/AztecFormatBarFactory.swift
  WooCommerce/Classes/ViewRelated/Editor/FormatBar/FormatBarItemViewProperties.swift
  WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
Labels: [Type] Enhancement

#2007 [Auth] Remove the `.showLoginEmail` segue and navigate programmatically
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Enhancement

#2015 Merge 3.8 final into develop
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#2008 Pass `CurrencySettings` to `CurrencyFormatter` and `PriceInputFormatter` for unit tests
  WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift
  WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
  WooCommerce/Classes/Tools/UnitInputFormatter/PriceInputFormatter.swift
  WooCommerce/WooCommerceTests/Tools/PriceInputFormatterTests.swift
Labels: Tech Debt, Unit Tests

#2002 Adds an exclamation point to the end of the product banner
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: [Type] Bug

#2024 Merge 3.9 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#2022 Add .idea folder to .gitignore
  .gitignore
Labels: Tooling

#2012 Edit Products: update product name edit UI to inline text field
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Extensions/UITextField+Helpers.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Add/Edit Products

#2009 Edit Products > price settings: set currency position based on store settings
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UIStackView+Subviews.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/Product+PriceSettingsViewModels.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/Product+InventorySettingsViewModels.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/Product+ShippingSettingsViewModels.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/UnitInputTableViewCell.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/UIStackView+SubviewsTests.swift
Labels: Add/Edit Products

#2026 Add Coding Style Guide
  docs/README.md
  docs/coding-style-guide.md
Labels: Documentation

#2017 Perform dual-fetch when loading the first page of the Processing tab
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Network/MockupNetwork.swift
  Networking/NetworkingTests/Responses/orders-load-all-2.json
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/SyncCoordinator.swift
  WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/SyncCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/OrderAction.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests+FetchFilteredAndAllOrders.swift
Labels: Order List

#2023 [Auth] Remove the `.showLinkMailView` segue and navigate programmatically
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#2018 Update Product cell style
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.xib
  WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: Product List, [Status] Needs Design Review

#2025 Adds ManageProductCategories feature flag #2000
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
Labels: Add/Edit Products

#2030 Remove "NSLocalizedString" in comment
  WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
Labels: Localization

#2029 Remove extra logic in `CurrencySettings`'s init
  WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
Labels: Add/Edit Products, Tech Debt

#2028 Edit Product > Price Settings: extract view data logic from view controller
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/ProductTaxClassListSelectorDataSource.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
  WooCommerce/WooCommerceTests/Mockups/MockTaxClassStoresManager.swift
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductTaxClassListSelectorDataSourceTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductPriceSettingsViewModelTests.swift
Labels: Add/Edit Products, Tech Debt

#2014 Add GitHub release creation to the release tooling
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#2041 Tax and Shipping Classes: Show existing data instead of ghost view when synchronizing
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
Labels: Add/Edit Products

#2050 Update Octokit
  Gemfile.lock
Labels: Tooling

#2031 [Auth] Remove the `.showGoogle` segue and navigate programmatically
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#2046 Fix function name in `DefaultProductFormTableViewModel+EditProductsM2Tests`
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel+EditProductsM2Tests.swift
Labels: Add/Edit Products, Tech Debt

#2034 Edit Product > Price Settings: support sale dates without a start or end date
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UILabel+Helpers.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductPriceSettingsViewModelTests.swift
Labels: Add/Edit Products, [Status] Needs Design Review

#2040 Enabled Products tab & M1 editing features by default
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/MainTabBarControllerTests+ProductListFeatureFlag.swift
Labels: Add/Edit Products, [Type] Enhancement

#2019 Download Arabic and Hebrew metadata
  fastlane/download_metadata.swift
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/ar-SA/subtitle.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/he/subtitle.txt
Labels: Localization, Tooling

#2058 Merge 3.9 release notes into develop
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#2043 [Categories] Display product categories on Product Edit screen
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product+ProductForm.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
  WooCommerce/WooCommerceTests/Mockups/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel+EditProductsM3Tests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
Labels: Add/Edit Products, [Status] Needs Design Review

#2032 Supported zero sale price in Edit Products
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Product/Product.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Responses/product-on-sale-with-empty-sale-price.json
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductPriceSettingsViewModelTests.swift
Labels: Add/Edit Products, [Type] Bug

#2049 Decouple ResultsController from NSManagedObjectContext
  RELEASE-NOTES.txt
  Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift
  Storage/Storage/Protocols/StorageType.swift
  WooCommerce/WooCommerceTests/Tools/ResultsControllerUIKitTests.swift
  Yosemite/Yosemite/Tools/ResultsController.swift
  Yosemite/YosemiteTests/Mockups/MockupStorage.swift
  Yosemite/YosemiteTests/Tools/ResultsControllerTests.swift
Labels: Unit Tests

#2055 Remove `stats` feature flag
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardUIFactory.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardUIFactoryTests.swift
Labels: Dashboard, Store Stats

#2056 Product Settings: implemented the changing status of a Product
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductStatus.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/List Selector Data Source/ProductStatusSettingListSelectorDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsSections.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
  WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductStatusSettingListSelectorDataSourceTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsViewModelTests.swift
  Yosemite/Yosemite/Model/Updaters/ProductUpdater.swift
  Yosemite/YosemiteTests/Model/Updaters/Product+UpdaterTestCases.swift
Labels: Add/Edit Products

#2038 Product List: add a toolbar with "Sort" and "Filter" CTAs
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Toolbar/ToolbarView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Product List

#2044 Product List: sort products based on name / date, ascending / descending
  Networking/Networking/Remote/ProductsRemote.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/UIAlertController+SortProducts.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/Enums/ProductsSortOrder.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/Yosemite/Tools/Products/ResultsController+SortProducts.swift
  Yosemite/Yosemite/Tools/ResultsController.swift
  Yosemite/YosemiteTests/Mockups/MockProduct.swift
  Yosemite/YosemiteTests/Stores/ProductStore+ProductsSortOrderTests.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
  Yosemite/YosemiteTests/Tools/Products/ResultsController+StorageProductTests.swift
Labels: Product List

#2062 Allow Customization of Keyboard Height Frame
  WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameAdjustmentProvider.swift
  WooCommerce/Classes/ViewRelated/Keyboard/KeyboardScrollable.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Order List, Product List
