Repository woocommerce/woocommerce-ios, pull requests merged in 2021-07, with the labels that each got.

#4518 Merge 7.0 Release Notes
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#4506 Docs: Add issue triage documentation
  README.md
  docs/issue-triage.md
Labels: type: documentation

#4478 Auth Role Checks: Part 2 - Add user interface for role error page
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Resources/Images.xcassets/woo-incorrect-role-error.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-incorrect-role-error.imageset/img-profiles-error-dark.pdf
  WooCommerce/Resources/Images.xcassets/woo-incorrect-role-error.imageset/img-profiles-error-light.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/RoleErrorViewModelTests.swift
Labels: feature: login

#4520 Fix missing tracking section on orders
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
Labels: feature: order details, type: bug

#4404 [Tooling] Fix GitHub releases for intermediate betas
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  Rakefile
  Scripts/update-translations.rb
  WooCommerce/Credentials/replace_secrets.rb
  fastlane/Deliverfile
  fastlane/Fastfile
Labels: category: tooling

#4505 Fix frozen animation on lists / scroll views when switching tabs
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UIRefreshControl+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: bug

#4495 Handle optional `delivery_days` field in Shipping Labels Carrier and Rates
  Networking/Networking/Model/ShippingLabel/Packages/Carriers and Rates/ShippingLabelCarrierRate.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarrierRow.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarrierRowViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
Labels: feature: shipping labels, type: bug

#4510 Shipping Labels: state selection in address validation screen
  Networking/Networking/Model/StateOfACountry.swift
  Networking/Networking/Remote/DataRemote.swift
  Podfile
  Podfile.lock
  Storage/Storage.xcodeproj/project.pbxproj
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Suggested Address/ShippingLabelSuggestedAddressViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelStateOfACountryListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TitleAndTextFieldTableViewCell.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelAddressFormViewModelTests.swift
  Yosemite/Yosemite/Actions/DataAction.swift
  Yosemite/Yosemite/Stores/DataStore.swift
Labels: feature: shipping labels

#4475 Shipping Labels: UI layer to make purchase and display progress and label printing views
  Networking/Networking/Model/ShippingLabel/Packages/Carriers and Rates/ShippingLabelCarrierRate.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarrierRow.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarrierRowViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
Labels: feature: shipping labels, status: feature-flagged

#4512 Variations Hide price-warning row borders
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductVariationFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactory+ReadonlyProductTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactory+VisibilityTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductVariationFormActionsFactory+ReadonlyVariationTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductVariationFormActionsFactoryTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/BottomSheetListSelector/ProductFormActionsFactory+NonEmptyBottomSheetActionsTests.swift
Labels: feature: product details, feature: variation details

#4504 Fix issue with interactive pop gesture in WooNavigationController
  RELEASE-NOTES.txt
  WooCommerce/Classes/System/WooNavigationController.swift
Labels: feature: app settings, feature: order details, type: bug

#4517 [Mobile Payments] Add KnownReadersProvider protocol and KnownReadersStoredList which implements it
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsKnownReadersProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsKnownReadersStoredList.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockAppSettingsStoresManager.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/CardReaderSettings/CardReaderSettingsKnownReadersStoredListTests.swift
Labels: feature: mobile payments

#4523 Shipping Labels: changing shipping addresses or package details now remove selected rate
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelFormViewModelTests.swift
Labels: feature: shipping labels, type: bug

#4529 Fixed the package weight in Shipping Label Creation form
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
Labels: feature: shipping labels, type: bug

#4527 [Mobile Payments] Prevents crash when reconnecting to a reader
  WooCommerce/Classes/Extensions/String+HTML.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsUnknownViewController.swift
Labels: feature: mobile payments, status: feature-flagged, type: crash

#4531 Shipping Labels: Fix mapping error when polling for shipping label status
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ShippingLabelStatusMapper.swift
  Networking/Networking/Model/ShippingLabel/Enums/ShippingLabelStatusPollingResponse.swift
  Networking/Networking/Remote/ShippingLabelRemote.swift
  Networking/NetworkingTests/Mapper/ShippingLabelStatusMapperTests.swift
  Networking/NetworkingTests/Remote/ShippingLabelRemoteTests.swift
  Yosemite/Yosemite/Stores/ShippingLabelStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockShippingLabelRemote.swift
  Yosemite/YosemiteTests/Stores/ShippingLabelStoreTests.swift
Labels: feature: shipping labels, status: feature-flagged

#4508 [Mobile Payments] Fix modals in landscape
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.xib
Labels: feature: mobile payments, type: bug

#4536 Shipping Labels: fixed navigation title showed in tab bar in Package Details and Package List screens
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/Package Selection/ShippingLabelPackageList.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
Labels: feature: shipping labels, type: bug

#4540 [Mobile Payments] Fix crash when attempting to collect payment while retrying
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalError.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
Labels: feature: mobile payments, type: crash

#4542 [Mobile Payments] Fix crash when attempting to collect payment while retrying (7.0 Backport)
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalError.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
Labels: feature: mobile payments, type: crash

#4534 [Order Fulfilment] Add Review Order screen (previously known as Fulfill Order)
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: fulfillment, type: enhancement

#4538 Fix: typo and sync status in Shipping Labels carrier and rates
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriersViewModel.swift
Labels: feature: shipping labels, type: bug

#4530 Show appropriate message when saving a product.
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductVariationModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormDataModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController+Helpers.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: product details

#4532 Variations: Remove unnecessary no-price warning banner
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsTopBannerFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: variation list

#4554 [Mobile Payments] Show Collect Payment button only for eligible orders with a total amount greater than zero
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift
Labels: feature: mobile payments

#4555 [Mobile Payments] Fix "Keep Searching" for readers
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
Labels: feature: mobile payments, type: bug

#4526 [Mobile Payments] Add Known Readers Provider to Settings VM Ordered List and pass into VMs
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsConnectedViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsConnectedViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsUnknownViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsUnknownViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsViewModelsOrderedList.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTableViewCells/ConnectedReaderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTableViewCells/ConnectedReaderTableViewCell.xib
Labels: feature: mobile payments

#4564 Improve "send feedback" loading indicator UI
  WooCommerce/Classes/ViewRelated/ReusableViews/LoadingView.swift
Labels: category: design, feature: send feedback

#4556 Fix: TopBannerView color with `info` type
  WooCommerce/Classes/Styles/UIColor+SemanticColors.swift
  WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
Labels: feature: shipping labels, type: bug

#4561 Shipping Label: Refactor ReprintShippingLabel for use printing new shipping labels
  Networking/Networking/Model/ShippingLabel/ShippingLabelSettings.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelCoordinator.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Reprint Shipping Label/PrintShippingLabelCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Reprint Shipping Label/PrintShippingLabelViewModelTests.swift
Labels: feature: shipping labels, status: feature-flagged

#4562 Shipping Labels: Customize print label screen for purchase flow
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelCoordinator.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelViewController.xib
  WooCommerce/Classes/ViewRelated/ReusableViews/ButtonTableViewCell.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Reprint Shipping Label/PrintShippingLabelCoordinatorTests.swift
Labels: feature: shipping labels, status: feature-flagged

#4569 Shipping Labels: Display notice if shipping label purchase fails
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
Labels: feature: shipping labels, status: feature-flagged

#4552 [Mobile Payments] Use "cancel style" for secondary modal buttons
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
Labels: feature: mobile payments, type: bug

#4570 Shipping Label: Handle missing service_name in shipping label
  Networking/Networking/Model/ShippingLabel/ShippingLabel.swift
Labels: feature: shipping labels

#4535 [Order Fulfillment][Part 2] Update Review Order screen with Products section
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/OrderItem.swift
  Networking/Networking/Model/OrderItemAttribute.swift
  Networking/Networking/Model/Refund/OrderItemRefund.swift
  Networking/Networking/Model/Refund/Refund.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Review Order/ReviewOrderViewModelTests.swift
Labels: feature: fulfillment, type: enhancement

#4539 [Order Fulfillment][Part 3] Add customer section to Review Order screen
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Review Order/ReviewOrderViewModelTests.swift
Labels: feature: fulfillment, type: enhancement

#4577 Tracks events for Shipping Labels M2 and M3
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/Package Selection/ShippingLabelPackageList.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Payment Methods/ShippingLabelPaymentMethods.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Suggested Address/ShippingLabelSuggestedAddressViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
Labels: category: analytics, feature: shipping labels

#4578 Enabled the Shipping Label creation for all the US store owners
  RELEASE-NOTES.txt
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
Labels: feature: shipping labels

#4533 Big titles solution
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: category: design, type: enhancement

#4549 [Order Fulfillment][Part 4] Add Tracking Section to Review Order screen
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/ShipmentTracking.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockShipmentActionStoresManager.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Review Order/ReviewOrderViewModelTests.swift
Labels: feature: fulfillment, type: enhancement

#4567 [Order Fulfillment][Part 5] Mark Order Complete footer view for Review Order screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.swift
Labels: feature: fulfillment, status: do not merge, type: enhancement

#4574 Variations: Show notice after creating a variation
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
Labels: feature: variation list

#4585 Inform translators of the constraints of the "99+" string
  WooCommerce/Classes/Extensions/NumberFormatter+LocalizedOrNinetyNinePlus.swift
Labels: feature: order list

#4586 Merge 7.0 final into develop
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Rakefile
  Scripts/update-translations.rb
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Credentials/replace_secrets.rb
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#4594 Merge 7.1 code freeze into develop
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Pluginfile
  fastlane/download_metadata.swift
Labels: Releases

#4563 Update "sort and filter" product toolbar behaviour
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: feature: product details

#4592 [Mobile Payments] Hide the collect payment button when the net amount pending does not match the total order amount
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderPaymentDetailsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/OrderPaymentDetailsViewModelTests.swift
Labels: feature: mobile payments, type: bug

#4591 [Order Fulfillment] Add missing analytics event for tapping Mark Order Complete
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
Labels: category: analytics, feature: fulfillment

#4589 [Order Fulfillment] Update success notice message for order fulfillment
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderFulfillmentNoticePresenter.swift
Labels: feature: fulfillment, type: enhancement

#4612 [CPP Onboarding] Feature flag for In-Person Payments
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
Labels: feature: mobile payments, status: feature-flagged, type: task

#4613 [CPP Onboarding] Generic error page
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsUnavailableView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: mobile payments, status: feature-flagged, type: task

#4601 Shipping Labels: Validate that address name field is not empty
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelFormViewModelTests.swift
Labels: feature: shipping labels

#4401 Check translation progress during final release
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: category: tooling

#4623 Add-ons: Remove addOnsI1 feature flag
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
Labels: category: woo extensions, type: task

#4602 Login: Make sure account settings and site plan are synced immediately on login
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
Labels: feature: login

#4624 [CPP Onboarding] Set padding for generic error to 24 pixels
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsUnavailableView.swift
Labels: feature: mobile payments, status: feature-flagged, type: enhancement

#4614 Product list & Product search edge to edge
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.xib
Labels: category: design, feature: product list, type: bug

#4615 [CPP Onboarding] Initial structure
  Storage/Storage/Tools/StorageType+Extensions.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsPresentingViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/CardPresentPaymentAction.swift
  Yosemite/Yosemite/Model/Enums/CardPresentPaymentsOnboardingState.swift
  Yosemite/Yosemite/Stores/CardPresentPaymentStore.swift
Labels: feature: mobile payments, status: feature-flagged, type: task

#4572 [Mobile Payments] Add view controller for when we know at least one card reader to search for
  WooCommerce/Classes/ViewRelated/Dashboard/Dashboard.storyboard
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsKnownViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsKnownViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: mobile payments

#4628 Fix: updated the top banner in Order Detail screen informing the user of the shipping label creation
  Storage/Storage/Model/FeedbackType.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/ShippingLabelsTopBannerFactory.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Shipping Labels/ShippingLabelsTopBannerFactoryTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyViewControllerTests.swift
  Yosemite/Yosemite/Stores/AppSettings/InAppFeedbackCardVisibilityUseCase.swift
Labels: feature: shipping labels, type: bug

#4575 [Mobile Payments] Add known-readers view to the stack, remove old known reader code
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsKnownViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsUnknownViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsViewModelsOrderedList.swift
  WooCommerce/WooCommerceTests/Mocks/MockCardPresentPaymentsStoresManager.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/CardReaderSettings/CardReaderSettingsConnectedViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/CardReaderSettings/CardReaderSettingsKnownViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/CardReaderSettings/CardReaderSettingsUnknownViewModelTests.swift
  Yosemite/Yosemite/Actions/CardPresentPaymentAction.swift
  Yosemite/Yosemite/Stores/CardPresentPaymentStore.swift
  Yosemite/YosemiteTests/Stores/CardPresentPaymentStoreTests.swift
Labels: feature: mobile payments

#4632 Shipping Labels: Enable Create Shipping Label button on orders with only refunded labels
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/ShippingLabelsTopBannerFactory.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Shipping Labels/ShippingLabelsTopBannerFactoryTests.swift
Labels: feature: shipping labels, type: bug

#4617 System plugins - Adding new model into Storage layer
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/SystemPlugin+CoreDataClass.swift
  Storage/Storage/Model/SystemPlugin+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 54.xcdatamodel/contents
  Storage/Storage/Tools/StorageType+Deletions.swift
  Storage/Storage/Tools/StorageType+Extensions.swift
  Storage/StorageTests/CoreData/MigrationTests.swift
  Storage/StorageTests/Tools/StorageTypeDeletionsTests.swift
  Storage/StorageTests/Tools/StorageTypeExtensionsTests.swift
Labels: category: woo extensions

#4618 System plugins - Adding new model into Networking layer
  Fakes/Fakes/Fakes.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/SystemPlugin.swift
Labels: category: woo extensions

#4634 System plugins - Fix OrderDetailsDataSource tests adding `.some(nil)` to datePaid property
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift
Labels: type: technical debt

#4635 Merge 7.1 beta 2 into develop
  Gemfile.lock
  Storage/Storage/Model/FeedbackType.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/ShippingLabelsTopBannerFactory.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Shipping Labels/ShippingLabelsTopBannerFactoryTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyViewControllerTests.swift
  Yosemite/Yosemite/Stores/AppSettings/InAppFeedbackCardVisibilityUseCase.swift
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#4631 [Order Fulfillment] Update constraints of Review Order footer view to safe areas
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Review Order/ReviewOrderViewController.swift
Labels: feature: fulfillment, type: bug

#4637 Edge-to-edge table views on Reviews tab
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Reviews/ReviewDetailsViewController.xib
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.xib
Labels: feature: review details, feature: review list, type: enhancement

#4638 Edge-to-edge table views on Orders tab
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Orders.storyboard
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersTabbedViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersTabbedViewController.xib
Labels: feature: order details, feature: order list, type: enhancement

#4641 Drop custom equatable conformance
  Hardware/Hardware/CardReader/CardPresentTransactionDetails.swift
  Hardware/Hardware/CardReader/ReceiptDetails.swift
  Networking/Networking/Model/Account.swift
  Networking/Networking/Model/Address.swift
  Networking/Networking/Model/Media/Media.swift
  Networking/Networking/Model/NoteMedia.swift
  Networking/Networking/Model/NoteRange.swift
  Networking/Networking/Model/Order.swift
  Networking/Networking/Model/OrderCouponLine.swift
  Networking/Networking/Model/OrderItem.swift
  Networking/Networking/Model/OrderItemTax.swift
  Networking/Networking/Model/OrderNote.swift
  Networking/Networking/Model/OrderRefundCondensed.swift
  Networking/Networking/Model/OrderStatus.swift
  Networking/Networking/Model/Post.swift
  Networking/Networking/Model/Product/ProductAttribute.swift
  Networking/Networking/Model/Product/ProductCategory.swift
  Networking/Networking/Model/Product/ProductDefaultAttribute.swift
  Networking/Networking/Model/Product/ProductDimensions.swift
  Networking/Networking/Model/Product/ProductDownload.swift
  Networking/Networking/Model/Product/ProductImage.swift
  Networking/Networking/Model/Product/ProductReview.swift
  Networking/Networking/Model/Product/ProductShippingClass.swift
  Networking/Networking/Model/Product/ProductTag.swift
  Networking/Networking/Model/Product/ProductVariationAttribute.swift
  Networking/Networking/Model/Refund/OrderItemRefund.swift
  Networking/Networking/Model/Refund/OrderItemTaxRefund.swift
  Networking/Networking/Model/Refund/Refund.swift
  Networking/Networking/Model/ShipmentTracking.swift
  Networking/Networking/Model/ShipmentTrackingProvider.swift
  Networking/Networking/Model/ShipmentTrackingProviderGroup.swift
  Networking/Networking/Model/Site.swift
  Networking/Networking/Model/SiteAPI.swift
  Networking/Networking/Model/SitePlan.swift
  Networking/Networking/Model/SiteSetting.swift
  Networking/Networking/Model/Stats/OrderStatsV4.swift
  Networking/Networking/Model/Stats/OrderStatsV4Interval.swift
  Networking/Networking/Model/Stats/OrderStatsV4Totals.swift
  Networking/Networking/Model/Stats/SiteVisitStats.swift
  Networking/Networking/Model/Stats/SiteVisitStatsItem.swift
  Networking/Networking/Model/Stats/TopEarnerStats.swift
  Networking/Networking/Model/Stats/TopEarnerStatsItem.swift
  Networking/Networking/Model/TaxClass.swift
  Networking/Networking/Settings/Credentials.swift
  Storage/Storage/Model/PreselectedProvider.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift
  Yosemite/YosemiteTests/Tools/Media/Media+Equatable.swift
Labels: type: technical debt

#4619 Auth Role Checks: Part 2.5 - Add accessibility support for role error screen
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.xib
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
Labels: feature: login

#4644 Shipping Labels: Validate that address name field is not empty
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelFormViewModelTests.swift
Labels: feature: shipping labels, type: bug

#4645 Shipping Labels: fixed total weight in Package Details
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetailsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelPackageDetailsViewModelTests.swift
Labels: feature: shipping labels, type: bug

#4218 [Mobile Payments] Add code to suppress Wallet during card capture
  WooCommerce/Classes/ViewModels/CardPresentPayments/PaymentCaptureOrchestrator.swift
  WooCommerce/Resources/Woo-Alpha.entitlements
  WooCommerce/Resources/Woo-Debug.entitlements
  WooCommerce/Resources/Woo-Release.entitlements
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: mobile payments, status: do not merge

#4650 Drop unnecessary Comparable conformance
  Networking/Networking/Model/Account.swift
  Networking/Networking/Model/Address.swift
  Networking/Networking/Model/Order.swift
  Networking/Networking/Model/OrderItemTax.swift
  Networking/Networking/Model/OrderNote.swift
  Networking/Networking/Model/Post.swift
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductAttribute.swift
  Networking/Networking/Model/Product/ProductCategory.swift
  Networking/Networking/Model/Product/ProductDefaultAttribute.swift
  Networking/Networking/Model/Product/ProductDimensions.swift
  Networking/Networking/Model/Product/ProductDownload.swift
  Networking/Networking/Model/Product/ProductImage.swift
  Networking/Networking/Model/Product/ProductTag.swift
  Networking/Networking/Model/Refund/OrderItemRefund.swift
  Networking/Networking/Model/Refund/OrderItemTaxRefund.swift
  Networking/Networking/Model/Refund/Refund.swift
  Networking/Networking/Model/ShipmentTracking.swift
  Networking/Networking/Model/Site.swift
  Networking/Networking/Model/SiteAPI.swift
  Networking/Networking/Model/SitePlan.swift
  Networking/Networking/Model/SiteSetting.swift
  Networking/Networking/Model/Stats/OrderStatsV4Interval.swift
  Networking/Networking/Model/Stats/OrderStatsV4Totals.swift
  Networking/Networking/Model/Stats/SiteVisitStats.swift
  Networking/Networking/Model/Stats/SiteVisitStatsItem.swift
  Networking/Networking/Model/Stats/TopEarnerStats.swift
  Networking/Networking/Model/Stats/TopEarnerStatsItem.swift
  WooCommerce/Classes/ViewModels/Order Details/Aggregate Order Items/AggregateOrderItem.swift
  docs/NETWORKING.md
Labels: type: technical debt

#4660 Hide bottom tab bar for card reader settings presenting view controller
  WooCommerce/Classes/ViewRelated/Dashboard/Dashboard.storyboard
Labels: feature: mobile payments

#4647 System Plugins - Update Yosemite layer - Add Remote and Mapper - 1/2
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/SystemPluginsMapper.swift
  Networking/Networking/Remote/SystemPluginsRemote.swift
  Networking/NetworkingTests/Mapper/SystemPluginsMapperTests.swift
  Networking/NetworkingTests/Remote/SystemPluginsRemoteTests.swift
  Networking/NetworkingTests/Responses/systemPlugins.json
  Yosemite/Yosemite/Model/Model.swift
Labels: category: woo extensions

#4620 Auth Role Checks: Part 1+2 - Add model and view classes
  Fakes/Fakes/Fakes.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/UserMapper.swift
  Networking/Networking/Model/User.swift
  Networking/Networking/Remote/UserRemote.swift
  Networking/Networking/Settings/WordPressAPIVersion.swift
  Networking/NetworkingTests/Mapper/UserMapperTests.swift
  Networking/NetworkingTests/Remote/UserRemoteTests.swift
  Networking/NetworkingTests/Responses/user-complete.json
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/Resources/Images.xcassets/woo-incorrect-role-error.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-incorrect-role-error.imageset/img-profiles-error-dark.pdf
  WooCommerce/Resources/Images.xcassets/woo-incorrect-role-error.imageset/img-profiles-error-light.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/RoleErrorViewModelTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/UserAction.swift
  Yosemite/Yosemite/Stores/UserStore.swift
  Yosemite/YosemiteTests/Stores/UserStoreTests.swift
Labels: feature: login

#4492 Auth Role Checks: Part 3 - Add role eligibility use case
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift
  WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift
  WooCommerce/Classes/Model/EligibilityErrorInfo.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/RoleEligibilityUseCaseTests.swift
  WooCommerce/WooCommerceTests/Authentication/RoleErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Model/EligibilityErrorInfoTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Extensions/User+Roles.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/YosemiteTests/Model/Extensions/User+RolesTests.swift
Labels: feature: login

#4665 Auth Role Checks: Part 3.5 - Move EligibilityErrorInfo to Storage module
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/EligibilityErrorInfo.swift
  Storage/Storage/Model/GeneralAppSettings.swift
  WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift
  WooCommerce/Classes/Model/EligibilityErrorInfo.swift
  WooCommerce/Classes/Model/StorageEligibilityErrorInfo+Woo.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/RoleEligibilityUseCaseTests.swift
  WooCommerce/WooCommerceTests/Model/EligibilityErrorInfoTests.swift
  WooCommerce/WooCommerceTests/Model/StorageEligibilityErrorInfoWooTests.swift
  Yosemite/Yosemite/Actions/AppSettingsAction.swift
  Yosemite/Yosemite/Model/Extensions/User+Roles.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/AppSettingsStore.swift
  Yosemite/YosemiteTests/Model/Extensions/User+RolesTests.swift
Labels: feature: login

#4493 Auth Role Checks: Part 4 - Implement user-facing flow changes
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/RoleErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockRoleEligibilityUseCase.swift
Labels: feature: login

#4662 System Plugins - Update Yosemite layer - Add Action and Store - 2/2
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/SystemStatusAction.swift
  Yosemite/Yosemite/Model/Storage/SystemPlugin+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/SystemStatusStore.swift
  Yosemite/YosemiteTests/Stores/SystemStatusStoreTests.swift
Labels: category: woo extensions

#4657 [Shipping Labels] Edge-to-edge table views
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/EdgeInsets+Woo.swift
  WooCommerce/Classes/View Modifiers/View+InsetPaddings.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarrierAndRatesTopBanner.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/Package Selection/ShippingLabelPackageList.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Payment Methods/ShippingLabelPaymentMethods.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Payment Methods/ShippingLabelPaymentMethodsTopBanner.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Suggested Address/ShippingLabelSuggestedAddressViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Suggested Address/ShippingLabelSuggestedAddressViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.xib
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.xib
  WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
  WooCommerce/Classes/ViewRelated/Top Banner/TopBannerWrapperView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: shipping labels, type: enhancement

#4658 Shipping Labels: Include selected package weight in total package weight
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/TitleAndTextFieldRow.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelPackageDetailsViewModelTests.swift
Labels: feature: shipping labels, type: bug

#4669 System plugins - Sync System plugins in DefaultStoreManager and Site plugins in PluginList
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Plugins/PluginListViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Plugins/PluginListViewModel.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Plugins/SitePluginListViewModelTests.swift
Labels: category: woo extensions

#4663 [Shipping Labels] Hide contact button when phone number is missing
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressTopBannerFactory.swift
Labels: feature: shipping labels, type: bug

#4670 Fix: Add network mock for users/me v2 endpoint
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceUITests/Mocks/mappings/me/rest_v2_sites_users_me.json
Labels: category: ui tests

#4576 Move Fastlane secrets outside of repository
  .configure
  fastlane/Fastfile
  fastlane/Matchfile
Labels: category: tooling

#4672 Update MediaType to use modern UTType API
  Yosemite/Yosemite/Tools/Media/MediaAssetExporter.swift
  Yosemite/Yosemite/Tools/Media/MediaType.swift
  Yosemite/Yosemite/Tools/Media/URL+Media.swift
Labels: type: technical debt

#4673 Merge 7.1 final into develop
  WooCommerce/Classes/Extensions/Decimal+Helpers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelPackageDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/TitleAndTextFieldRow.swift
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerceTests/Extensions/DecimalWooTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelPackageDetailsViewModelTests.swift
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#4678 Merge 7.2 code freeze into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#4675 Shipping Labels: Create separate feature flags for M4
  WooCommerce/Classes/System/DefaultFeatureFlagService.swift
  WooCommerce/Classes/System/FeatureFlag.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift
Labels: feature: shipping labels, type: task

#4680 Order Detail: "email note to customer" option is now hidden if no email is available
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/Add Order Note/NewNoteViewController.swift
Labels: feature: order details, type: bug

#4697 Plugins: Fix Storage warnings
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 54.xcdatamodel/contents
Labels: type: technical debt

#4696 Shipping Labels: Show country picker for origin and destination address forms
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelCountryListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelFormViewModelTests.swift
Labels: feature: shipping labels, type: task

#4689 [CPP Onboarding] Add initial unit tests for onboarding state calculation
  Fakes/Fakes/Fakes.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/PaymentGatewayAccount.swift
  Yosemite/YosemiteTests/Mocks/MockStorageManager+Sample.swift
  Yosemite/YosemiteTests/Stores/CardPresentPaymentStoreTests.swift
Labels: category: unit tests, feature: mobile payments

#4700 New Tracks event `shipping_label_order_is_eligible`
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
Labels: category: analytics, feature: shipping labels

#4699 Upgrade ZendeskSupportSDK 5.0.1 -> 5.3.0
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: technical debt

#4691 [Mobile Payments] Add card reader ID to payment intent
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
Labels: feature: mobile payments

#4682 [Mobile Payments] Remove direct access to cell views
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsConnectedViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsKnownViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsUnknownViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTableViewCells/ConnectedReaderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/HeadlineTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/ImageTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LearnMoreTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/NumberedListItemTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TitleTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TitleTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: feature: mobile payments

#4705 Merge 7.2 release notes into develop
  Gemfile.lock
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases
