Repository woocommerce/woocommerce-ios, pull requests merged in 2022-09, with the labels that each got.

#7619 Merge 10.0.1 changes from 10.1 to trunk
  WooCommerce/Classes/Authentication/AuthenticationConstants.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: Releases

#7610 Remove `.systemStatusReport` feature flag references
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
Labels: type: enhancement, type: technical debt, category: experimental features

#7622 Add support for force-refreshing the server-side analytics cache
  Networking/Networking/Remote/LeaderboardsRemote.swift
  Networking/Networking/Remote/OrderStatsRemoteV4.swift
  Networking/NetworkingTests/Remote/LeaderboardsRemoteTests.swift
  Networking/NetworkingTests/Remote/OrderStatsRemoteV4Tests.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  Yosemite/Yosemite/Actions/StatsActionV4.swift
  Yosemite/Yosemite/Model/Mocks/ActionHandlers/MockStatsActionV4Handler.swift
  Yosemite/Yosemite/Stores/AvailabilityStore.swift
  Yosemite/Yosemite/Stores/StatsStoreV4.swift
  Yosemite/YosemiteTests/Mocks/MockNetwork+Path.swift
  Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift
Labels: type: task, category: analytics, category: performance

#7623 Remove unused code on `AvailabilityAction`
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/AvailabilityAction.swift
  Yosemite/Yosemite/Model/Mocks/ActionHandlers/MockAvailabilityActionHandler.swift
  Yosemite/Yosemite/Model/Mocks/MockStoresManager.swift
  Yosemite/Yosemite/Stores/AvailabilityStore.swift
  Yosemite/YosemiteTests/Stores/StatsV4AvailabilityStoreTests.swift
Labels: type: technical debt

#7621 Custom help content for "Jetpack required Error" screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackErrorViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewModel.swift
  WooCommerce/Classes/Model/CustomHelpCenterContent.swift
  WooCommerce/Classes/ServiceLocator/Authentication.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/JetpackErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/ULErrorViewControllerTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockAuthentication.swift
  WooCommerce/WooCommerceTests/Model/CustomHelpCenterContentTests.swift
Labels: type: task, feature: login, feature: support

#7611 [Engage] Universal Links: Handle Order Details universal links
  WooCommerce/Classes/Universal Links/RouteMatcher.swift
  WooCommerce/Classes/Universal Links/Routes/OrderDetailsRoute.swift
  WooCommerce/Classes/Universal Links/Routes/Route.swift
  WooCommerce/Classes/Universal Links/UniversalLinkRouter.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderLoaderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift
  WooCommerce/WooCommerceTests/Mocks/MockRoute.swift
  WooCommerce/WooCommerceTests/Universal Links/UniversalLinkRouterTests.swift
Labels: type: task, feature: deep links

#7630 [Mobile Payments] Learn more link from Payments Menu Pay in Person toggle
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsPlugin+CashOnDelivery.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsCashOnDeliveryPaymentGatewayNotSetUpViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTitleSubtitleToggleTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTitleSubtitleToggleTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: mobile payments

#7617 [Mobile Payments] Switch action for Payments Menu Cash on Delivery toggle
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsPlugin+CashOnDelivery.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsCashOnDeliveryPaymentGatewayHelpers.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsCashOnDeliveryPaymentGatewayNotSetUpViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTitleSubtitleToggleTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTitleSubtitleToggleTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: mobile payments

#7613 [Mobile Payments] UI for Enable Pay in Person toggle switch in IPP settings
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsSearchingViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsPlugin+CashOnDelivery.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsCashOnDeliveryPaymentGatewayHelpers.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsLearnMore.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/LearnMoreViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsCashOnDeliveryPaymentGatewayNotSetUpView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsCashOnDeliveryPaymentGatewayNotSetUpViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsOnboardingError.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsPluginNotSetup.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTableViewCell.xib
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTitleSubtitleToggleTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTitleSubtitleToggleTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: mobile payments

#7609 Update the logged-out A/A test and prologue CTA order A/B experiment to the new experiments
  Experiments/Experiments/ABTest.swift
Labels: feature: login, category: analytics

#7625 Save test result as artifacts
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
Labels: category: tooling

#7631 [Engage] Universal Links: Handle Payments universal links
  WooCommerce/Classes/Universal Links/Routes/PaymentsRoute.swift
  WooCommerce/Classes/Universal Links/UniversalLinkRouter.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: deep links

#7635 [Mobile Payments] Analytics for Pay in Person toggle on Payments Menu
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsCashOnDeliveryPaymentGatewayNotSetUpViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTitleSubtitleToggleTableViewCell.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsCashOnDeliveryPaymentGatewayNotSetUpViewModelTests.swift
Labels: type: task, feature: mobile payments, category: analytics

#7637 [Mobile Payments] Relabel Pay in Person toggle: remove “Enable”, mention checkout
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
Labels: type: task, feature: mobile payments

#7640 Make PaymentsRoute conform to Route to make the project compile.
  WooCommerce/Classes/Universal Links/Routes/PaymentsRoute.swift
Labels: type: bug, feature: deep links

#7558 Add Store Widgets target and Fastlane configuration
  Gemfile.lock
  WooCommerce/StoreWidgets/Assets.xcassets/AccentColor.colorset/Contents.json
  WooCommerce/StoreWidgets/Assets.xcassets/AppIcon.appiconset/Contents.json
  WooCommerce/StoreWidgets/Assets.xcassets/Contents.json
  WooCommerce/StoreWidgets/Assets.xcassets/WidgetBackground.colorset/Contents.json
  WooCommerce/StoreWidgets/Info.plist
  WooCommerce/StoreWidgets/StoreWidgets.intentdefinition
  WooCommerce/StoreWidgets/StoreWidgets.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: category: tooling, feature: widgets

#7642 Updated release notes for 10.2
  CHANGELOG.md
Labels: Releases

#7645 Merge 10.1 final to trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#7646 Merge 10.2 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#7649 Set `skip_prechecks:true` in CI release builds
  .buildkite/commands/release-build.sh
Labels: category: tooling

#7626 Remove `.hubMenu` feature flag references
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/MainTabBarControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
Labels: type: enhancement, type: technical debt, category: experimental features

#7658 Widgets: Update Xcode configuration
  WooCommerce/Resources/Info.plist
  WooCommerce/StoreWidgets/StoreWidgets.intentdefinition
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: widgets

#7647 Make sure test results are archived when test suites fail
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
Labels: category: tooling

#7638 Dashboard: save the last selected time range tab and restore it on the next dashboard launch
  RELEASE-NOTES.txt
  Storage/Storage/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/GeneralStoreSettings.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  Yosemite/Yosemite/Actions/AppSettingsAction.swift
  Yosemite/Yosemite/Stores/AppSettingsStore.swift
Labels: type: enhancement, feature: stats, category: performance

#7662 Fix an issue where UI tests for iPad isn't running on iPad
  .buildkite/pipeline.yml
Labels: category: tooling

#7666 [Mobile Payments] Rename PluginWebView to AuthenticatedWebView
  WooCommerce/Classes/Authentication/AuthenticatedWebViewController.swift
  WooCommerce/Classes/Authentication/AuthenticatedWebViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackErrorViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackSetupWebViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NoWooErrorViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/WooSetupWebViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, category: woo extensions, feature: mobile payments

#7659 [Engage] Universal links: Tracking
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Universal Links/UniversalLinkRouter.swift
Labels: type: task, feature: deep links

#7660 Widgets: Update UI for Dark Mode
  WooCommerce/StoreWidgets/StoreInfoViewModifiers.swift
Labels: feature: widgets

#7661 [Widgets] Non Login UI
  WooCommerce/StoreWidgets/Images.xcassets/Contents.json
  WooCommerce/StoreWidgets/Images.xcassets/woo-logo-white.imageset/Contents.json
  WooCommerce/StoreWidgets/Images.xcassets/woo-logo-white.imageset/woo-logo-white.pdf
  WooCommerce/StoreWidgets/Images/UIImage+Widgets.swift
  WooCommerce/StoreWidgets/StoreInfoViewModifiers.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: widgets

#7656 [Mobile Payments] Refresh Payment Gateways when Payment Menu opened
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModelTests.swift
Labels: type: enhancement, feature: mobile payments

#7653 Remove `.jetpackConnectionPackageSupport` feature flag references
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NoWooErrorViewModel.swift
  WooCommerce/Classes/Extensions/WordPressComSiteInfo+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackInstall/JetpackInstallStepsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/StorePickerViewModelTests.swift
  WooCommerce/WooCommerceTests/Extensions/WordPressComSiteInfoWooTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/JetpackInstall/JetpackInstallStepsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
  Yosemite/Yosemite/Actions/AccountAction.swift
  Yosemite/Yosemite/Stores/AccountStore.swift
  Yosemite/YosemiteTests/Stores/AccountStoreTests.swift
Labels: type: enhancement, type: technical debt, category: experimental features

#7672 Remove ios_version parameter from test_without_building lane
  .buildkite/commands/run-ui-tests.sh
  .buildkite/pipeline.yml
  fastlane/Fastfile
Labels: category: tooling

#7674 Rename widgets target entitlements to be consistent with app target
  WooCommerce/StoreWidgets/Entitlements/StoreWidgets-Alpha.entitlements
  WooCommerce/StoreWidgets/Entitlements/StoreWidgets-Debug.entitlements
  WooCommerce/StoreWidgets/Entitlements/StoreWidgets-Release.entitlements
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: technical debt

#7650 Dashboard: sync stats after swiping to another time range tab
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
Labels: type: bug, feature: stats

#7664 Ensure app and widget targets have the same version values
  WooCommerce/Resources/Info.plist
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  config/Version.Public.xcconfig
Labels: category: tooling

#7671 [Mobile Payments] Moooore IPP: Remove all references to IPP from settings
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
Labels: type: task, feature: mobile payments

#7670 [Mobile Payments] Signed-in card reader purchase
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/AuthenticatedWebViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/PurchaseCardReaderWebViewViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModelTests.swift
Labels: type: enhancement, feature: mobile payments

#7600 Login: Update Networking and Yosemite layers to handle WordPress.org REST API
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/JetpackConnectionURLMapper.swift
  Networking/Networking/Mapper/JetpackUserMapper.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/DotcomUser.swift
  Networking/Networking/Model/JetpackUser.swift
  Networking/Networking/Network/AlamofireNetwork.swift
  Networking/Networking/Network/MockNetwork.swift
  Networking/Networking/Network/Network.swift
  Networking/Networking/Network/NullNetwork.swift
  Networking/Networking/Network/WordPressOrgNetwork.swift
  Networking/Networking/Remote/JetpackConnectionRemote.swift
  Networking/Networking/Requests/WordPressOrgRequest.swift
  Networking/NetworkingTests/Mapper/JetpackConnectionURLMapperTests.swift
  Networking/NetworkingTests/Mapper/JetpackUserMapperTests.swift
  Networking/NetworkingTests/Remote/JetpackConnectionRemoteTests.swift
  Networking/NetworkingTests/Requests/WordPressOrgRequestTests.swift
  Networking/NetworkingTests/Responses/jetpack-connected-user.json
  Networking/NetworkingTests/Responses/jetpack-connection-url.json
  Networking/NetworkingTests/Responses/jetpack-user-not-connected.json
  Podfile
  Podfile.lock
  WooCommerce/Classes/Yosemite/DeauthenticatedState.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/JetpackConnectionAction.swift
  Yosemite/Yosemite/Base/DeauthenticatedStore.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/JetpackConnectionStore.swift
  Yosemite/YosemiteTests/Stores/JetpackConnectionStoreTests.swift
  docs/NETWORKING.md
Labels: type: enhancement, feature: login

#7669 [Engage] Universal Links: Handle mobile segment
  WooCommerce/Classes/Universal Links/RouteMatcher.swift
  WooCommerce/Classes/Universal Links/Routes/OrderDetailsRoute.swift
  WooCommerce/Classes/Universal Links/Routes/PaymentsRoute.swift
  WooCommerce/Classes/Universal Links/Routes/Route.swift
  WooCommerce/Classes/Universal Links/UniversalLinkRouter.swift
  WooCommerce/WooCommerceTests/Mocks/MockRoute.swift
  WooCommerce/WooCommerceTests/Universal Links/UniversalLinkRouterTests.swift
Labels: type: task, feature: deep links

#7675 [UI Tests] - Update ScreenObject version to v0.2.2
  WooCommerce.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WooCommerce/UITestsFoundation/Screens/Orders/OrdersScreen.swift
  WooCommerce/UITestsFoundation/Screens/Orders/SingleOrderScreen.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceScreenshots/WooCommerceScreenshots.swift
Labels: category: ui tests

#7681 Widgets: Keychain Setup
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/Keychain+Entries.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/StoreWidgets/Entitlements/StoreWidgets-Alpha.entitlements
  WooCommerce/StoreWidgets/Entitlements/StoreWidgets-Debug.entitlements
  WooCommerce/StoreWidgets/Entitlements/StoreWidgets-Release.entitlements
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: widgets

#7682 Widgets: Set up User Defaults Sharing
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: widgets

#7678 [Mobile Payments] Cancel discovery when user taps cancel
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsAlerts.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsAlertsProvider.swift
  WooCommerce/WooCommerceTests/Mocks/MockCardReaderSettingsAlerts.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardReaderConnectionControllerTests.swift
Labels: type: bug, feature: mobile payments

#7688 [Mobile Payments] Make the message in error onboarding view multiline.
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/Onboarding Errors/InPersonPaymentsOnboardingErrorMainContentView.swift
Labels: type: bug, feature: mobile payments

#7692 Merge 10.2 final to trunk
  WooCommerce/Resources/Info.plist
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#7694 [Mobile Payments] Revert `needsPayment` use for showing the `Collect Payment` button
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift
Labels: type: bug, feature: mobile payments

#7690 Widgets: Fetch today data
  WooCommerce/StoreWidgets/StoreInfoDataService.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: widgets

#7699 Merge 10.3 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#7641 Custom help content for "Store picker" screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Model/CustomHelpCenterContent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerceTests/Model/CustomHelpCenterContentTests.swift
Labels: type: task, feature: login, feature: support

#7698 Remove coupons view/create/edit/delete feature flag references
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewController.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesViewController.swift
Labels: type: technical debt, category: experimental features

#7680 Remove `backgroundProductImageUpload` feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/ServiceLocator/LegacyProductImageUploader.swift
  WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewController.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductVariationFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/MainTabBarControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+ChangesTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+ObservablesTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+SaveTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormViewModel+ChangesTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormViewModel+ImageUploaderTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormViewModel+ObservablesTests.swift
Labels: type: enhancement, type: technical debt, category: experimental features

#7676 Remove `appleIDAccountDeletion` feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
Labels: type: enhancement, type: technical debt, category: experimental features

#7608 Login: Support setting up Jetpack connection for logging in with site credentials
  Networking/Networking/Network/WordPressOrgNetwork.swift
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackConnectionErrorViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackConnectionWebViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewModel.swift
  WooCommerce/Classes/Authentication/WordPressOrgCredentials+Authenticator.swift
  WooCommerce/Classes/ServiceLocator/Authentication.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackConnectionErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackConnectionWebViewModelTests.swift
  WooCommerce/WooCommerceTests/Extensions/WordPressOrgCredentialsAuthenticatorTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockAuthentication.swift
  Yosemite/Yosemite/Actions/JetpackConnectionAction.swift
  Yosemite/Yosemite/Stores/JetpackConnectionStore.swift
  Yosemite/YosemiteTests/Stores/JetpackConnectionStoreTests.swift
Labels: type: enhancement, feature: login

#7697 Widgets: Show Not logged in view
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7701 Widgets: Unable to fetch data View
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7691 Configure localization automation for Widgets extension
  Scripts/build-phases/LintAppLocalizedStringsUsage.sh
  Scripts/build-phases/LintAppLocalizedStringsUsage.swift
  WooCommerce/Classes/Tools/AppLocalizedString.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: category: tooling, category: i18n

#7704 Dashboard: fix a crash from unexpected number of order stats intervals
  WooCommerce/Classes/Extensions/Date+StartAndEnd.swift
  WooCommerce/WooCommerceTests/Extensions/DateStartAndEndTests.swift
Labels: type: crash, feature: stats

#7706 Login: Add tracks for Jetpack connection flow
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackConnectionErrorViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackConnectionWebViewModel.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackConnectionErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackConnectionWebViewModelTests.swift
Labels: feature: login, category: analytics

#7687 [Mobile Payments] Fix card reader connection modal transitions
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderModalFlowViewControllerProtocol.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/SeveralReadersFoundViewController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/SeveralReadersFoundViewController.xib
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsAlerts.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: bug, feature: mobile payments

#7712 Update Automattic-Tracks-iOS library to latest beta version.
  Podfile
  Podfile.lock
Labels: type: enhancement, category: tooling

#7689 [Mobile Payments] Delay dismissing connection modal until cancellation is fully complete
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalScanningForReader.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
Labels: type: bug, feature: mobile payments

#7707 Widgets: Share store TZ settings
  WooCommerce/StoreWidgets/StoreInfoDataService.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/Extensions/Date+StartAndEnd.swift
  WooFoundation/WooFoundationTests/Extensions/DateStartAndEndTests.swift
Labels: feature: widgets

#7708 Widgets: Data formatting
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/Tools/Shared Site Settings/SelectedSiteSettings.swift
  WooCommerce/StoreWidgets/StoreInfoDataService.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooFoundation/WooFoundation/Currency/CurrencyCode.swift
  WooFoundation/WooFoundation/Currency/CurrencySettings.swift
Labels: feature: widgets

#7716 Update Charts to 4.1.0
  WooCommerce.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: type: enhancement

#7371 Make the app compatible with Xcode 14
  .buildkite/pipeline.yml
  Podfile
  Podfile.lock
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/ShippingLineDetails.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsPeriodViewModelTests.swift
Labels: category: tooling

#7717 Widget: Analytics
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/AppDelegate.swift
Labels: feature: widgets

#7720 Widget: Last refreshed label
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7718 Fix "Linking against a dylib which is not safe for use in application extensions" warnings
  Experiments/Experiments.xcodeproj/project.pbxproj
  Networking/Networking.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
Labels: category: tooling

#7719 Mock an action response to prevent the test case sending HTTP request
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Addresses/EditOrderAddressFormViewModelTests.swift
Labels: category: unit tests

#7725 Upgrade project to Xcode 14.0 stable recommended settings
  Gemfile.lock
  Podfile.lock
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation.xcodeproj/xcshareddata/xcschemes/WooFoundation.xcscheme
Labels: category: tooling

#7724 Products: fix the draft status blue text color in the product row
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/View Models/ProductsTabProductViewModel.swift
Labels: type: bug, feature: product list

#7665 Dashboard: reset the last sync timestamp after new orders
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/ServiceLocator/PushNotesManager.swift
  WooCommerce/Classes/ServiceLocator/PushNotification.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/WooCommerceTests/Mocks/MockPushNotificationsManager.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/MainTabBarControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Notifications/ReviewsCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
  Yosemite/Yosemite/Actions/OrderAction.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: feature: stats

#7731 Widgets: Updates copies
  WooCommerce/Classes/Tools/Shared Site Settings/SelectedSiteSettings.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7733 Widgets: Fix version override in extension settings
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: widgets

#7732 Widgets: Remove Feature Flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7062 Upgrade to support Xcode 14.0
  .buildkite/pipeline.yml
  Gemfile.lock
  Networking/Networking.xcodeproj/xcshareddata/xcschemes/Networking.xcscheme
  Podfile
  Podfile.lock
  Storage/Storage.xcodeproj/xcshareddata/xcschemes/Storage.xcscheme
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/ShippingLineDetails.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/GenerateCredentials.xcscheme
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce Alpha.xcscheme
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce.xcscheme
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerceScreenshots.xcscheme
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerceUITests.xcscheme
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsPeriodViewModelTests.swift
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation.xcodeproj/xcshareddata/xcschemes/WooFoundation.xcscheme
  Yosemite/Yosemite.xcodeproj/xcshareddata/xcschemes/Yosemite.xcscheme
Labels: status: do not merge, category: tooling

#7729 Updated release notes for 10.4
  CHANGELOG.md
Labels: Releases

#7734 Update fastlane to 2.210
  Gemfile.lock
Labels: category: tooling

#7728 Update Tracks to 0.13.0-beta.2 to address verbose Sentry logs
  Podfile
  Podfile.lock
Labels: type: bug

#7730 Custom help content for "Enter WPCOM password" screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Model/CustomHelpCenterContent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerceTests/Model/CustomHelpCenterContentTests.swift
Labels: type: task, feature: login, feature: support

#7735 Revert badge refresh removal from OrdersRootViewController
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
Labels: type: bug, feature: notifications, feature: order list

#7736 Merge 10.3 final to trunk
  Gemfile.lock
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooFoundation/WooFoundation/Extensions/Date+StartAndEnd.swift
  WooFoundation/WooFoundationTests/Extensions/DateStartAndEndTests.swift
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#7737 Custom help content for "Open mail to find magic link" screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Model/CustomHelpCenterContent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerceTests/Model/CustomHelpCenterContentTests.swift
Labels: type: task, feature: login, feature: support

#7727 Products: Add duplicate product feature
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormRemoteActionUseCase.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController+Helpers.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductVariationFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormRemoteActionUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: type: enhancement, feature: product details

#7744 Product Duplication: Update release notes
  RELEASE-NOTES.txt
Labels: feature: product details

#7743 Order creation: Add orderCreationSearchCustomers feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: feature: order creation

#7747 Custom help content for "Wrong WordPress.com account error" screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/Classes/Model/CustomHelpCenterContent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/ULAccountMismatchViewControllerTests.swift
  WooCommerce/WooCommerceTests/Authentication/WrongAccountErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockAuthentication.swift
  WooCommerce/WooCommerceTests/Model/CustomHelpCenterContentTests.swift
Labels: type: task, feature: login, feature: support

#7749 Add `fake()` method to DotcomUser and JetpackUser entities
  Fakes/Fakes/Networking.generated.swift
Labels: type: enhancement, type: task

#7752 Widgets: Improve Widget Accessibility
  RELEASE-NOTES.txt
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7748 Login: Handle Jetpack connection for WP.com login
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/ULAccountMismatchViewControllerTests.swift
  WooCommerce/WooCommerceTests/Authentication/WrongAccountErrorViewModelTests.swift
Labels: type: enhancement, feature: login

#7751 Remove JetpackConnectionErrorViewModel and its tests
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackConnectionErrorViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/JetpackConnectionErrorViewModelTests.swift
Labels: type: enhancement, feature: login

#7759 Login: More unit tests for WrongAccountErrorViewModel
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/Authenticator.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/WrongAccountErrorViewModelTests.swift
Labels: type: enhancement, feature: login

#7762 Updated release notes for 10.5
  CHANGELOG.md
Labels: Releases

#7765 Store picker: Fix crash when selecting a store in the store picker
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewModel.swift
  WooCommerce/WooCommerceTests/Authentication/StorePickerViewModelTests.swift
Labels: type: crash

#7767 Custom help content for "Not a WooCommerce site" error screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Navigation Exceptions/NoWooErrorViewModel.swift
  WooCommerce/Classes/Model/CustomHelpCenterContent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerceTests/Authentication/NoWooErrorViewModelTests.swift
  WooCommerce/WooCommerceTests/Model/CustomHelpCenterContentTests.swift
Labels: type: task, feature: support

#7772 Merge 10.5 code freeze to trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#7746 Update Networking layer with GET `/wp-json/wc/v3/customers/<id>`
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/CustomerMapper.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Customer.swift
  Networking/Networking/Remote/CustomerRemote.swift
  Networking/NetworkingTests/Mapper/CustomerMapperTests.swift
  Networking/NetworkingTests/Remote/CustomerRemoteTests.swift
  Networking/NetworkingTests/Responses/customer.json
Labels: type: enhancement, category: parity, feature: order creation

#7769 Help button in fancy alert in "Wrong WordPress.com account error" screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+UnifiedLogin.swift
Labels: type: task, feature: support

#7738 Search products by SKU: storage layer - add `filterKey` to `ProductSearchResults` entity
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/ProductSearchResults+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 73.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
Labels: feature: product list

#7774 Login Prologue: feature carousel should not be shown right after onboarding
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/ServiceLocator/Authentication.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockAuthentication.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewControllerTests.swift
Labels: type: bug, feature: login

#7739 Search products by SKU: add a segmented control to products search
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/ProductsRemote.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/products-sku-search.json
  Storage/Storage/Tools/StorageType+Extensions.swift
  Storage/StorageTests/Tools/StorageTypeExtensionsTests.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Linked Products List Selector/ProductListSelector/ProductListMultiSelectorSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Product/ProductSearchUICommandTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Model/Products/ProductSearchFilter.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: type: enhancement, feature: product list

#7781 Search products by SKU: show SKU to search result cell, empty query optimization, analytics
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/View Models/ProductsTabProductViewModel.swift
  WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductsTabProductViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Product/ProductSearchUICommandTests.swift
Labels: type: enhancement, feature: product list

#7773 Login: Show instruction to connect to a WP.com site from the account mismatch error screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackConnectionWebViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+UnifiedLogin.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackConnectionWebViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/ULAccountMismatchViewControllerTests.swift
  WooCommerce/WooCommerceTests/Authentication/WrongAccountErrorViewModelTests.swift
Labels: type: enhancement, feature: login

#7782 Widgets: Fix analytics events
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
Labels: category: analytics, priority: high, feature: widgets

#7785 Merge 10.4.1 hotfix into `release/10.5`
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
Labels: Releases

#7783 [Review Replies] Add comment reply endpoint to Networking layer
  Networking/Networking/Remote/CommentRemote.swift
  Networking/NetworkingTests/Remote/CommentRemoteTests.swift
Labels: feature: review details

#7784 [Review Replies] Add comment reply action to Yosemite layer
  Yosemite/Yosemite/Actions/CommentAction.swift
  Yosemite/Yosemite/Stores/CommentStore.swift
  Yosemite/YosemiteTests/Stores/CommentStoreTests.swift
Labels: feature: review details

#7764 Add CustomerStore and support for loadCustomer action
  Networking/Networking/Remote/CustomerRemote.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CreateOrderAddressFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModelProtocol.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressForm.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressFormViewModel.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/CustomerAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
  docs/YOSEMITE.md
Labels: type: enhancement, category: parity, feature: order creation

#7775 [Mobile Payments] Only show IPP announcement if it's supported in the store's country
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
Labels: type: bug, feature: mobile payments

#7788 [Review Replies] Add reply button to product review detail
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Reviews/Cells/NoteDetailsCommentTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Reviews/Cells/NoteDetailsCommentTableViewCell.xib
  WooCommerce/Classes/ViewRelated/Reviews/ReviewDetailsViewController.swift
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: feature: review details, status: feature-flagged

#7790 Bulk Prices: Added success notice with bulk updating variation prices
  WooCommerce/Classes/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewController.swift
Labels: feature: variation details

#7789 [Review Replies] Add a "Reply to Product View" screen in Product Review detail.
  WooCommerce/Classes/ViewRelated/Reviews/ReviewDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewReply.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewReplyViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Reviews/ReviewReplyViewModelTests.swift
Labels: feature: review details, status: feature-flagged

#7792 Lock Screen Widgets: Add app link widget
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/StoreWidgets/Lockscreen/AppLinkWidget.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
  WooCommerce/StoreWidgets/StoreWidgets.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: status: feature-flagged, feature: widgets

#7798 [Review Replies] Add analytics for replying to product reviews
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewReplyViewModel.swift
Labels: category: analytics, feature: review details

#7799 [Review Replies] Remove feature flag to release replying to product reviews
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Reviews/ReviewDetailsViewController.swift
Labels: feature: review details

#7802 Bulk Prices: Shows API limit warning
  WooCommerce/Classes/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewModelTests.swift
Labels: feature: variation details

#7800 Updated release notes for 10.6
  CHANGELOG.md
Labels: Releases

#7804 Bulk Prices: Release feature
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewModelTests.swift
Labels: feature: variation details
