Repository woocommerce/woocommerce-ios, pull requests merged in 2022-11, with the labels that each got.

#7965 Simplified login: Update store picker with entry point to store creation
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.swift
  WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.xib
  WooCommerce/Classes/Authentication/Epilogue/AddStoreFooterView.swift
  WooCommerce/Classes/Authentication/Epilogue/EmptyStoresTableViewCell.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: login

#7885 Customer search: Fill customer fields on Order screen
  Networking/NetworkingTests/Mapper/WCAnalyticsCustomerMapperTests.swift
  Networking/NetworkingTests/Remote/WCAnalyticsCustomerRemoteTests.swift
  Networking/NetworkingTests/Responses/wc-analytics-customers.json
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CreateOrderAddressFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/OrderCustomerListView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModelProtocol.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressForm.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Addresses/EditOrderAddressFormViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Customer/CustomerSearchUICommandTests.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: enhancement, category: parity, feature: order creation

#7985 Store creation MVP: analytics
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreCreation.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Authentication/Store Creation/LoggedOutStoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewModels/Authentication/AccountCreationFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: login, category: analytics

#7986 Account creation: handle email-based username error by generating another fallback username
  Networking/Networking/Remote/AccountRemote.swift
  Yosemite/Yosemite/Stores/AccountCreationStore.swift
Labels: type: bug

#8000 Products Onboarding: Trigger add product flow from banner CTA
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: status: feature-flagged, feature: products onboarding

#7992 Products Onboarding: Integrate Template Endpoint
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: products onboarding

#7831 Add performance monitoring configuration behind feature flags – Off by default
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
  WooCommerce/Classes/Tools/Logging/WooCrashLoggingStack.swift
Labels: category: tooling, status: feature-flagged

#7995 Account creation: design polishes - fonts, ToS link, text field focus styles
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationFormFieldView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/TextFieldStyles.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement

#8006 Account creation: design polishes - add a button to show/hide text field input for a secure field
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationFormFieldView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/TextFieldStyles.swift
Labels: type: enhancement

#8007 Account creation: design polishes - update ToS link style to an underline, font/color updates
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationFormFieldView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/AttributedText.swift
Labels: type: enhancement

#7991 [Just In Time Messages] Add UTM params and analytics to JITM Call to Action
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModelTests.swift
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/Mocks/MockUTMParameterProvider.swift
  WooFoundation/WooFoundation/Utilities/UTMParameters.swift
  WooFoundation/WooFoundation/Utilities/WooCommerceComUTMProvider.swift
  WooFoundation/WooFoundationTests/Utilities/UTMProviderProtocolExtensionTests.swift
  WooFoundation/WooFoundationTests/Utilities/WooCommerceComUTMProviderTests.swift
Labels: type: enhancement, category: analytics, feature: jitm

#8001 [Just In Time Messages] Dismiss JITM
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/DataBoolMapper.swift
  Networking/Networking/Remote/JustInTimeMessagesRemote.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerceTests/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  Yosemite/Yosemite/Actions/JustInTimeMessageAction.swift
  Yosemite/Yosemite/Stores/JustInTimeMessageStore.swift
Labels: type: task, category: analytics, feature: jitm

#7970 [Tooling] Make Codegen module aware
  CodeGeneration/Sourcery/Copiable/Models+Copiable.swifttemplate
  CodeGeneration/Sourcery/Fakes/Fakes.swifttemplate
  Fakes/Fakes/Hardware.generated.swift
  Fakes/Fakes/Networking.generated.swift
  Fakes/Fakes/Yosemite.generated.swift
  Hardware/Hardware/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/Copiable/Models+Copiable.generated.swift
  WooCommerce/Classes/Copiable/Models+Copiable.generated.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/WooCommerceTests/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/JustInTimeMessageAction.swift
  Yosemite/Yosemite/Model/Copiable/Models+Copiable.generated.swift
  Yosemite/Yosemite/Model/JustInTimeMessage.swift
  Yosemite/Yosemite/Stores/JustInTimeMessageStore.swift
  Yosemite/YosemiteTests/Stores/JustInTimeMessageStoreTests.swift
Labels: type: task, category: tooling

#8005 Products Onboarding: Support template products
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/ProductFactory.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/ProductFactoryTests.swift
Labels: feature: products onboarding

#8003 Products Onboarding: Add the banner experiment to the app
  Experiments/Experiments/ABTest.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockABTesting.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
Labels: feature: products onboarding

#8011 Products Onboarding: Template Analytics
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
Labels: feature: products onboarding

#8009 Store creation: show a confirmation alert when dismissing the view, store picker popover fix
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
Labels: type: enhancement, type: crash

#7907 Add tracks for Customer Search
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModelProtocol.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressForm.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Addresses/EditOrderAddressFormViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Customer/CustomerSearchUICommandTests.swift
Labels: type: enhancement, category: analytics, category: parity, feature: order creation

#7999 Simplified login: Prologue screen updates
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationConstants.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Prologue/LoginProloguePages.swift
  WooCommerce/UITestsFoundation/Screens/Login/PrologueScreen.swift
Labels: type: task, feature: login

#7996 Simplified login: Apply A/B test
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/WooCommerceTests/Authentication/NotWPAccountViewModelTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
Labels: type: task, feature: login

#8013 Product Preview: Limit previews to wp.com stores
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Site.swift
  Networking/NetworkingTests/Mapper/AccountMapperTests.swift
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/Authentication/WebAuth/RequestAuthenticator.swift
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Inbox/InboxNoteRow.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
  Yosemite/Yosemite/Model/Mocks/Graphs/ScreenshotsObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
Labels: feature: product details, status: feature-flagged

#7974 Product Preview: Add WebKitViewController to handle authenticated sessions
  WooCommerce/Classes/Authentication/WebAuth/LinkBehavior.swift
  WooCommerce/Classes/Authentication/WebAuth/NavigationTitleView.swift
  WooCommerce/Classes/Authentication/WebAuth/WebKitViewController.swift
  WooCommerce/Classes/Authentication/WebAuth/WebProgressView.swift
  WooCommerce/Classes/Authentication/WebAuth/WebViewControllerConfiguration.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: product details, status: feature-flagged

#8022 Update the git cache path from `woocommerce` to `automattic`
  .buildkite/cache-builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: category: tooling

#8023 Store creation M1: enable feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: type: task

#8024 Add unit tests for `AccountCreationFormViewModel`
  WooCommerce/Classes/ViewModels/Authentication/AccountCreationFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/Authentication/AccountCreationFormViewModelTests.swift
Labels: type: technical debt

#8021 [In-App Purchases] Add environment variable for the WordPress.com API base url
  Networking/Networking/Settings/Settings.swift
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce.xcscheme
Labels: type: task, feature: in-app purchases

#8010 [Just In Time Messages] GET request and view analytic events
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerceTests/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  Yosemite/Yosemite/Actions/JustInTimeMessageAction.swift
  Yosemite/Yosemite/Stores/JustInTimeMessageStore.swift
  Yosemite/YosemiteTests/Stores/JustInTimeMessageStoreTests.swift
Labels: type: task, category: analytics, feature: jitm

#8012 [Just In Time Messages] Refresh JITMs
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
Labels: type: task, feature: jitm

#8017 [Just In Time Messages] Add build and locale identifiers to JITM request
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Hardware/Hardware.xcodeproj/project.pbxproj
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/JustInTimeMessagesRemote.swift
  Networking/Networking/Requests/JetpackRequest.swift
  Networking/NetworkingTests/Remote/JustInTimeMessagesRemoteTests.swift
  Networking/NetworkingTests/Requests/JetpackRequestTests.swift
  RELEASE-NOTES.txt
  Storage/Storage.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/Extensions/Bundle+Woo.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Stores/JustInTimeMessageStore.swift
Labels: type: task, feature: jitm

#8031 Add support for WP-API error parsing
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/WordPressApiError.swift
  Networking/Networking/Remote/InAppPurchasesRemote.swift
  Networking/Networking/Remote/Remote.swift
  Networking/Networking/Requests/DotcomRequest.swift
  Networking/Networking/Requests/JetpackRequest.swift
  Networking/Networking/Requests/Request.swift
  Networking/Networking/Requests/WordPressOrgRequest.swift
  Networking/Networking/Validators/DotcomValidator.swift
  Networking/Networking/Validators/ResponseDataValidator.swift
  Networking/Networking/Validators/WordPressApiValidator.swift
  Networking/NetworkingTests/Remote/RemoteTests.swift
  Networking/NetworkingTests/Responses/error-wp-rest-forbidden.json
  Networking/NetworkingTests/Validators/DotcomValidatorTests.swift
  Networking/NetworkingTests/Validators/WordPressApiValidatorTests.swift
Labels: type: task, category: architecture, feature: in-app purchases

#8034 Products Onboarding: Update banner design based on review feedback
  Storage/Storage/Model/Feature Announcements/FeatureAnnouncementCampaign.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/FeatureAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/ProductsOnboardingAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/FeatureAnnouncementCardView.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
Labels: status: feature-flagged, feature: products onboarding

#8038 Products Onboarding: Add Template Experiment
  Experiments/Experiments/ABTest.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
Labels: feature: products onboarding

#8040 Products Onboarding: Improve bottom sheet template copy
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductCreationTypeCommand.swift
Labels: feature: products onboarding

#8025 Merge 11.0 final to trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8035 Updated release notes for 11.1
  CHANGELOG.md
Labels: Releases

#8042 Fix order notification deeplink
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
Labels: feature: notifications, priority: high

#8043 Merge 11.1 code freeze to trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8026 Store creation M1: unit tests for coordinators
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/LoggedOutStoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Tools/Coordinator.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuCoordinator.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/FlowCoordinator/AddOrderCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/SKU Scanner/ProductSKUBarcodeScannerCoordinator.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/LoggedOutStoreCreationCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/StoreCreationCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/StorePickerCoordinatorTests.swift
Labels: type: technical debt

#8029 Account creation: add `UnauthenticatedRequest` instead of passing empty credentials to `AuthenticatedRequest`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Network/AlamofireNetwork.swift
  Networking/Networking/Network/MockNetwork.swift
  Networking/Networking/Requests/UnauthenticatedRequest.swift
  Networking/NetworkingTests/Requests/UnauthenticatedRequestTests.swift
  WooCommerce/Classes/Yosemite/DeauthenticatedState.swift
  docs/NETWORKING.md
  docs/architecture-overview.md
Labels: type: technical debt

#8041 Experiments: Update documentation and remove logged-in A/A test
  Experiments/Experiments/ABTest.swift
  docs/EXPERIMENTS.md
Labels: category: experiments

#8053 Login: Disable New to Woo link in prologue
  Experiments/Experiments/DefaultFeatureFlagService.swift
Labels: feature: login

#8050 Centralize WordPressKit pod definition in `Podfile`
  Podfile
  Podfile.lock
Labels: category: tooling

#8051 [In-app Purchases] Improve debug view UX
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
Labels: feature: in-app purchases

#8052 Products Onboarding: Add support for using `frame_nonce` in product previews
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Site.swift
  Networking/Networking/Remote/AccountRemote.swift
  Networking/NetworkingTests/Mapper/AccountMapperTests.swift
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Site+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 77.xcdatamodel/contents
  Storage/StorageTests/CoreData/ManagedObjectModelsInventoryTests.swift
  Storage/StorageTests/CoreData/MigrationTests.swift
  WooCommerce/WooCommerceUITests/Mocks/mappings/me/rest_v11_me_sites.json
  Yosemite/Yosemite/Model/Mocks/Graphs/ScreenshotsObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
Labels: feature: products onboarding

#8060 Domain suggestions: Networking and Yosemite layers
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/DomainRemote.swift
  Networking/NetworkingTests/Remote/DomainRemoteTests.swift
  Networking/NetworkingTests/Responses/domain-suggestions.json
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/DomainAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDomainRemote.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
Labels: type: task

#8062 Login: Remove the survey at the end of the login onboarding flow
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+LoginOnboarding.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Prologue/LoginOnboardingSurveyView.swift
  WooCommerce/Classes/Authentication/Prologue/LoginOnboardingViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: login

#8064 Track XMLRPC failure
  Podfile
  Podfile.lock
Labels: type: task, feature: login

#8059 Products Onboarding: Bottom Sheets Titles
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorSectionHeaderView.swift
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorSectionHeaderView.xib
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewProperties.swift
  WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/FlowCoordinator/AddOrderCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Downloadable Files/File List/ProductDownloadListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: feature: products onboarding

#8058 Products Onboarding: Enable product previews for all stores
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: status: feature-flagged, feature: products onboarding

#8072 Products Onboarding: Adds a templateEligible property to productListAddProductTapped event
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: feature: products onboarding

#8065 Store creation M2 - domain selection: basic UI integration
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainRowView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorViewModel.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/StoreCreationCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainSelectorViewModelTests.swift
Labels: type: enhancement, status: feature-flagged

#8008 Add IPP plugin status tags to ZenDesk
  WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/WooCommerceTests/Testing/MockZendeskManager.swift
Labels: type: enhancement, feature: support

#8073 Merge 11.1.0.1 to trunk
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8070 Products Onboarding: Add product_detail_preview_tapped event
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: feature: product details, category: analytics, status: feature-flagged

#8028 Simplified Login: Update prologue screen image
  WooCommerce/Classes/Authentication/Prologue/LoginProloguePages.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Resources/Images.xcassets/login-prologue-woo-mobile.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/login-prologue-woo-mobile.imageset/Prologue Image Dark.pdf
  WooCommerce/Resources/Images.xcassets/login-prologue-woo-mobile.imageset/Prologue Image Light.pdf
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task, feature: login

#8078 [Mobile Payments] Remove upsellCardReader banner from OrderList
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
Labels: type: task, feature: mobile payments

#8077 windows was deprecated in iOS 15: Use UIWindowScene.windows instead
  WooCommerce/Classes/Environment Keys/SafeAreaInsetsKey.swift
Labels: type: enhancement, iOS 15

#8074 Login: Fix layout issue on account mismatch error screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/WooCommerceTests/Authentication/WrongAccountErrorViewModelTests.swift
Labels: type: enhancement, feature: login

#8076 Login: Update Networking for plugin management endpoints with cookie authentication
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/SitePluginMapper.swift
  Networking/Networking/Remote/JetpackConnectionRemote.swift
  Networking/NetworkingTests/Mapper/SitePluginMapperTests.swift
  Networking/NetworkingTests/Remote/JetpackConnectionRemoteTests.swift
  Networking/NetworkingTests/Responses/site-plugin-without-envelope.json
Labels: type: task, feature: login

#8090 Products Onboarding: Update save and publish events
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: feature: product details, category: analytics

#8091 Product Onboarding: Allow Template Products to be previewed
  Fakes/Fakes/Products/ProductFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+ObservablesTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: products onboarding

#8100 Product Preview: Track preview failed event
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/WebAuth/WebKitViewController.swift
Labels: feature: product details, category: analytics, status: feature-flagged

#8102 Products Onboarding: Remove feature flag and release product preview feature
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: product details

#8101 Update release notes for 11.2
  CHANGELOG.md
Labels: Releases

#8103 Merge 11.1 final to trunk
  WooCommerce/Resources/ja.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ja/release_notes.txt
Labels: Releases

#8099 Address warning about `try` used on a method that does not `throws`
  Networking/Networking/Remote/JustInTimeMessagesRemote.swift
Labels: category: tooling

#8105 Merge 11.2 code freeze to trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8092 Store creation M2 - domain selection: empty/error/loading states, design updates
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainRowView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/FilterListSelector.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelector.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/SearchHeader.swift
  WooCommerce/Resources/Images.xcassets/domain-search-placeholder.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/domain-search-placeholder.imageset/domain-search-placeholder.pdf
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainSelectorViewModelTests.swift
Labels: type: enhancement, status: feature-flagged

#8095 Login: Update Yosemite layer to handle Jetpack plugin management with cookie authentication
  Yosemite/Yosemite/Actions/JetpackConnectionAction.swift
  Yosemite/Yosemite/Stores/JetpackConnectionStore.swift
  Yosemite/YosemiteTests/Stores/JetpackConnectionStoreTests.swift
Labels: type: task, feature: login

#8093 kUTType was deprecated in iOS15, use UTType instead
  Yosemite/Yosemite/Tools/Media/MediaAssetExporter.swift
  Yosemite/Yosemite/Tools/Media/MediaImageExporter.swift
  Yosemite/YosemiteTests/Tools/Media/MediaImageExporterTests.swift
  Yosemite/YosemiteTests/Tools/Media/URL+MediaTests.swift
Labels: type: enhancement, iOS 15

#8107 Store creation M2: site creation Networking & Yosemite layer changes
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Remote/SiteRemoteTests.swift
  Networking/NetworkingTests/Responses/site-creation-domain-error.json
  Networking/NetworkingTests/Responses/site-creation-success.json
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/SiteAction.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
  Yosemite/YosemiteTests/Base/DispatcherTests.swift
  Yosemite/YosemiteTests/Mocks/MockSiteStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockSiteRemote.swift
  Yosemite/YosemiteTests/Stores/SiteStoreTests.swift
Labels: type: task

#8109 Store creation M2: show store summary after store creation success
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationSummaryView.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Resources/Images.xcassets/store-summary.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-summary.imageset/store-summary.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: enhancement, status: feature-flagged

#8113 [In-app Purchases] Improve error reporting
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
Labels: type: task, feature: in-app purchases

#8111 [In-app Purchases]Use environment variable to get test site id for IAP
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce.xcscheme
Labels: type: task, feature: in-app purchases

#8115 [Mobile Payments] Show spinner while awaiting reader readiness
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalPreparingReader.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentPaymentsModalViewModel.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/PaymentCaptureOrchestrator.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/PaymentReceiptEmailParameterDeterminer.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlertsProtocol.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsAlerts.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/IndefiniteCircularProgressViewStyle.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockOrderDetailsPaymentAlerts.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/PaymentCaptureOrchestratorTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/PaymentReceiptEmailParameterDeterminerTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/RefundSubmissionUseCaseTests.swift
Labels: type: bug, feature: mobile payments

#8120 Store creation M2: WPCOM plan screen (UI only)
  WooCommerce/Classes/Authentication/Store Creation/Plan/StoreCreationPlanFeaturesView.swift
  WooCommerce/Classes/Authentication/Store Creation/Plan/StoreCreationPlanView.swift
  WooCommerce/Classes/Authentication/Store Creation/Plan/StoreCreationPlanViewModel.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Resources/Images.xcassets/store-creation-plan.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-creation-plan.imageset/store-creation-plan.pdf
  WooCommerce/Resources/Images.xcassets/wpcom-logo.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/wpcom-logo.imageset/wpcom-logo.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: enhancement

#8124 [In-app Purchases] Improve transaction handling logic
  Networking/Networking/Model/WordPressApiError.swift
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
Labels: type: task, feature: in-app purchases

#8133 [In-app Purchases] Include purchase result in purchaseProduct API
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesForWPComPlansManager.swift
Labels: type: task, feature: in-app purchases

#8125 Distribute WCiOS Prototype Builds to Collaborators
  fastlane/Fastfile
Labels: category: tooling

#8127 Login: New Jetpack required screen
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/EmptyStoresTableViewCell.swift
  WooCommerce/Classes/Authentication/Epilogue/EmptyStoresTableViewCell.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackSetupRequiredViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewModel.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Resources/Images.xcassets/woo-empty-store-picker.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-empty-store-picker.imageset/woo-empty-store-picker.pdf
  WooCommerce/Resources/Images.xcassets/woo-jetpack-connection.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-jetpack-connection.imageset/woo-jetpack-connection.pdf
  WooCommerce/Resources/Images.xcassets/woo-jetpack-setup.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-jetpack-setup.imageset/woo-jetpack-setup.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackSetupRequiredViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/ULErrorViewControllerTests.swift
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task, feature: login

#8138 Products Onboarding: Remove unused web auth code
  WooCommerce/Classes/Authentication/WebAuth/AuthenticationService.swift
  WooCommerce/Classes/Authentication/WebAuth/CookieJar.swift
  WooCommerce/Classes/Authentication/WebAuth/RequestAuthenticator.swift
  WooCommerce/Classes/Authentication/WebAuth/WebKitViewController.swift
  WooCommerce/Classes/Authentication/WebAuth/WebViewControllerConfiguration.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/CookieJarTests.swift
  WooCommerce/WooCommerceTests/Tools/RequestAuthenticatorTests.swift
  WooCommerce/WooCommerceTests/Tools/WKCookieJarTests.swift
Labels: feature: product details

#8140 Products Onboarding: Stay on My Store screen after tapping on banner CTA
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: products onboarding

#8139 Remove not needed functions.
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
  WooCommerce/Classes/Extensions/UIImage+TintColor.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: technical debt

#8141 Store creation M2: success screen
  WooCommerce/Classes/Authentication/Store Creation/Installations/StoreCreationSuccessView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement

#8143 Update required version of Xcode in the readme
  README.md
Labels: type: documentation

#8142 Login: Add new screen for site credential login in the Jetpack setup flow
  WooCommerce/Classes/Authentication/Jetpack Setup/LoginJetpackSetupCoordinator.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Site Credential Login/SiteCredentialLoginView.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Site Credential Login/SiteCredentialLoginViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackSetupRequiredViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackInstall/JetpackInstallStepsView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/JetpackInstallHeaderView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/SiteCredentialLoginViewModelTests.swift
Labels: type: task, feature: login

#8155 Add feature flag: System Status Report to support requests
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: enhancement, feature: support

#8136 [Mobile Payments] Display reader input method message when reader is ready
  Hardware/Hardware.xcodeproj/project.pbxproj
  Hardware/Hardware/CardReader/CardReaderEvent.swift
  Hardware/Hardware/CardReader/CardReaderInputOptions.swift
  Hardware/Hardware/CardReader/StripeCardReader/CardReaderEvent+Stripe.swift
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalReaderIsReady.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalTapCard.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentRefundOrchestrator.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/PaymentCaptureOrchestrator.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlertsProtocol.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockOrderDetailsPaymentAlerts.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalReaderIsReadyTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalTapCardTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/PaymentCaptureOrchestratorTests.swift
  Yosemite/Yosemite/Model/Model.swift
Labels: type: bug, feature: mobile payments

#8161 Merge 11.3 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8158 [Analytics Hub] Add a "see more" button on the dashboard
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Dashboard/AnalyticsHub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: stats, status: feature-flagged

#8169 Merge 11.3 release notes to trunk
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#8157 [Analytics Hub] Add Networking support for Average Order Value analytics
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Stats/OrderStatsV4Totals.swift
  Networking/NetworkingTests/Mapper/OrderStatsMapperV4Tests.swift
  Networking/NetworkingTests/Responses/order-stats-v4-daily.json
  Networking/NetworkingTests/Responses/order-stats-v4-defaults.json
  Networking/NetworkingTests/Responses/order-stats-v4-hour.json
  Networking/NetworkingTests/Responses/order-stats-v4-month.json
  Networking/NetworkingTests/Responses/order-stats-v4-year.json
  Yosemite/Yosemite/Model/Mocks/MockObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/OrderStatsV4+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/OrderStatsV4Interval+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/OrderStatsV4Totals+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Model/Extensions/OrderStatsV4Interval+DateTests.swift
  Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift
Labels: category: analytics

#8162 [Analytics Hub] Add Storage support for Average Order Value analytics
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/OrderStatsV4Totals+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 78.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
  Yosemite/Yosemite/Model/Storage/OrderStatsV4Totals+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift
Labels: category: analytics

#8176 Convert async -> Result signature functions to async throws
  Networking/Networking/Remote/AccountRemote.swift
  Networking/Networking/Remote/DomainRemote.swift
  Networking/Networking/Remote/JustInTimeMessagesRemote.swift
  Networking/Networking/Remote/Remote.swift
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Remote/AccountRemoteTests.swift
  Networking/NetworkingTests/Remote/DomainRemoteTests.swift
  Networking/NetworkingTests/Remote/JustInTimeMessagesRemoteTests.swift
  Networking/NetworkingTests/Remote/RemoteTests.swift
  Networking/NetworkingTests/Remote/SiteRemoteTests.swift
  TestKit/Sources/TestKit/Assertions.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/ViewModels/Authentication/AccountCreationFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/RemoveAppleIDAccessCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/WooCommerceTests/ViewModels/Authentication/AccountCreationFormViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/RemoveAppleIDAccessCoordinatorTests.swift
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/Extensions/Result+Extensions.swift
  Yosemite/Yosemite/Stores/AccountCreationStore.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/Yosemite/Stores/JustInTimeMessageStore.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
  Yosemite/Yosemite/Stores/StatsStoreV4.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockAccountRemote.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDomainRemote.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockSiteRemote.swift
Labels: type: technical debt

#8175 [Analytics Hub] Create shared set of stats helpers for My Store and Analytics Hub
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsPeriodViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsPeriodViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StatsDataTextFormatterTests.swift
Labels: feature: stats

#8033 [Tooling] Update Xcode version refs in tooling scripts
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .xcode-version
  .xcversion
  fastlane/Fastfile
Labels: category: tooling

#8160 Read `version` for `update_appstore_strings` from codebase
  fastlane/Fastfile
Labels: category: tooling

#8163 Products Onboarding: Adds Main Analytics Hub View
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/AnalyticsHub/AnalyticsHubView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: category: analytics

#8177 Analytics Hub: Adds Report Card
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/StatsCard.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/ViewModifiers/WooStyleModifiers.swift
Labels: category: analytics

#8185 Analytics Hub: Add Main View Model
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsReportCard.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsReportCardViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: category: analytics

#8181 [Analytics Hub] Add helpers for creating the delta percentage text
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StatsDataTextFormatterTests.swift
Labels: feature: stats

#8154 Store creation M2: integrate with mock IAP to test the entire flow
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Plan/MockInAppPurchases.swift
  WooCommerce/Classes/Authentication/Store Creation/Plan/StoreCreationPlanView.swift
  WooCommerce/Classes/Authentication/Store Creation/Store name/StoreNameForm.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationSummaryView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/StoreCreationCoordinatorTests.swift
Labels: type: task, status: feature-flagged

#8094 Fix 'contentEdgeInsets' was deprecated in iOS 15.0
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerNoteTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Filters/FilteredOrdersHeaderBar.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/VerticalButton.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveySubmittedViewController.swift
Labels: type: enhancement, iOS 15

#8165 Store creation M2: domain selector updates
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/SearchHeader.swift
  WooCommerce/Resources/Images.xcassets/domain-search-placeholder.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/domain-search-placeholder.imageset/domain-search-placeholder-dark.pdf
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainSelectorViewModelTests.swift
Labels: type: enhancement, status: feature-flagged

#8204 Login - Jetpack setup - Tracks event for authorization using different WPCOM account
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/LoginJetpackSetupCoordinator.swift
Labels: type: enhancement, feature: login

#8187 Login - Jetpack Setup: Add tracks events
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/LoginJetpackSetupCoordinator.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/LoginJetpackSetupView.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/LoginJetpackSetupViewModel.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Site Credential Login/SiteCredentialLoginView.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Site Credential Login/SiteCredentialLoginViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackSetupRequiredViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/LoginJetpackSetupHostingControllerTests.swift
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/LoginJetpackSetupViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/SiteCredentialLoginHostingViewControllerTests.swift
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/SiteCredentialLoginViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/JetpackSetupRequiredViewModelTests.swift
Labels: type: enhancement, feature: login

#8191 [Analytics Hub] Add fake order stats for configuring Analytics cards
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
Labels: category: analytics

#8188 Change deprecated kUUTypeUTF8PlainText for UTType
  Networking/Networking/Model/Product/ProductDownloadDragAndDrop.swift
Labels: type: enhancement, feature: add/edit products, iOS 15

#8202 [Analytics Hub] Return the direction of the delta along with formatted delta percentage
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StatsDataTextFormatterTests.swift
Labels: feature: stats

#8174 [Mobile Payments] Add local mobile discovery to StripeCardReaderService
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Hardware/Hardware.xcodeproj/project.pbxproj
  Hardware/Hardware/CardReader/CardReaderService.swift
  Hardware/Hardware/CardReader/CardReaderType.swift
  Hardware/Hardware/CardReader/StripeCardReader/CardReaderDiscoveryMethod.swift
  Hardware/Hardware/CardReader/StripeCardReader/CardReaderType+Stripe.swift
  Hardware/Hardware/CardReader/StripeCardReader/NoOpCardReaderService.swift
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
  Storage/Storage/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/GeneralAppSettings.swift
  Storage/StorageTests/Model/AppSettings/GeneralAppSettingsTests.swift
  WooCommerce/Classes/Model/BetaFeature.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardReaderType+Manual.swift
  WooCommerce/Resources/Woo-Debug.entitlements
  WooCommerce/WooCommerceTests/Mocks/MockCardPresentPaymentsStoresManager.swift
  WooCommerce/WooCommerceTests/Stripe Integration Tests/StripeCardReaderIntegrationTests.swift
  Yosemite/Yosemite/Actions/CardPresentPaymentAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/CardPresentPaymentStore.swift
  Yosemite/YosemiteTests/Mocks/CardPresentPayments/MockCardReaderService.swift
  Yosemite/YosemiteTests/Stores/AppSettings/InAppFeedbackCardVisibilityUseCaseTests.swift
  Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
  Yosemite/YosemiteTests/Stores/CardPresentPaymentStoreTests.swift
Labels: type: enhancement, feature: mobile payments, status: feature-flagged

#8184 [Mobile Payments] Groundwork for refactor of CollectOrderPaymentUseCase
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyCollectOrderPaymentUseCaseTests.swift
Labels: type: task, feature: mobile payments, status: feature-flagged

#8211 [Analytics Hub] Add network actions
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
  Yosemite/Yosemite/Actions/StatsActionV4.swift
  Yosemite/Yosemite/Stores/StatsStoreV4.swift
Labels: feature: stats, status: feature-flagged

#8197 Analytics Hub: Adjust UI for landscape orientation
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
Labels: feature: hub menu

#8203 Store creation M2: checkout flow - Networking layer changes
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/PaymentRemote.swift
  Networking/Networking/Requests/DotcomRequest.swift
  Networking/Networking/Settings/WordPressAPIVersion.swift
  Networking/NetworkingTests/Remote/PaymentRemoteTests.swift
  Networking/NetworkingTests/Responses/create-cart-success.json
  Networking/NetworkingTests/Responses/load-plan-success.json
  Yosemite/Yosemite/Model/Model.swift
Labels: type: task

#8134 Remove "Check for Nested Frameworks" build phase
  Scripts/check-nested-frameworks.sh
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: category: tooling, type: technical debt

#8171 Add System Status Report to ZenDesk support requests
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerceTests/Testing/MockZendeskManager.swift
Labels: type: enhancement, feature: support

#8212 Temporarily remove mistakenly merged entitlement
  WooCommerce/Resources/Woo-Debug.entitlements
Labels: type: task, feature: mobile payments

#8170 Native Jetpack Installation: Apply A/B test
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
Labels: type: enhancement, feature: login

#8218 Login: Jetpack setup: Add tracks
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/LoginJetpackSetupView.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/LoginJetpackSetupViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackInstall/JetpackInstallSteps.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/JetpackInstallStepTests.swift
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/LoginJetpackSetupViewModelTests.swift
Labels: type: enhancement, feature: login

#8208 [Analytics Hub] Initialize Revenue and Orders Analytics cards with localized placeholder data
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
Labels: feature: stats

#8159 Analytics Hub: Create date range section
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsTimeRangeCard.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsTimeRangeCardViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: category: analytics

#8167 Updated release notes for 11.3
  CHANGELOG.md
Labels: Releases

#8223 [Mobile Payments] Make Preparing Reader background one color
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
Labels: type: bug, feature: mobile payments

#8226 Enable the SSR Request feature flag.
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: type: task

#8207 [Analytics Hub] Add formatters for net revenue stats data
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StatsDataTextFormatterTests.swift
Labels: feature: stats

#8215 Analytics Hub: Products Card UI
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsProductCard.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsProductCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsReportCard.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/DeltaTag.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: category: analytics

#8193 Analytics Hub: Introduce time range controller
  Networking/Networking/Extensions/DateFormatter+Woo.swift
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubTimeRangeGenerator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StatsTimeRangeV4+UI.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubTimeRangeGeneratorTests.swift
  WooFoundation/WooFoundation/Extensions/Date+StartAndEnd.swift
Labels: category: analytics

#8232 Merge 11.3 final to trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8227 Updated release notes for 11.4
  CHANGELOG.md
Labels: Releases

#8233 Merge 11.4 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8183 [Moooore IPP] Remove Payments Feature Announcement (Red Badge) and Simple Payments from Orders
  RELEASE-NOTES.txt
  Storage/Storage/Model/Feature Announcements/FeatureAnnouncementCampaign.swift
  WooCommerce/Classes/ViewModels/MainTabViewModel.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/FlowCoordinator/AddOrderCoordinator.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/FlowCoordinator/BottomSheetOrderType.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/FlowCoordinator/NewSimplePaymentsLocationNoticeViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/FlowCoordinator/NewSimplePaymentsLocationNoticeViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersTopBannerFactory.swift
  WooCommerce/UITestsFoundation/Screens/Orders/OrdersScreen.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/MainTabViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/AddOrderCoordinatorTests.swift
Labels: type: task

#8205 Store creation M2: checkout flow - Yosemite layer changes
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/PaymentAction.swift
  Yosemite/Yosemite/Stores/PaymentStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockPaymentRemote.swift
  Yosemite/YosemiteTests/Stores/PaymentStoreTests.swift
Labels: type: task

#8229 [Analytics Hub] Add data binding
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsReportCard.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsPeriodViewModel.swift
Labels: feature: stats, status: feature-flagged

#8241 Native Jetpack Installation: Replace disabled A/B test experiment with new one
  Experiments/Experiments/ABTest.swift
Labels: type: bug, feature: login, priority: high

#8234 Analytics Hub: Fill Products Card with data
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StatsDataTextFormatterTests.swift
Labels: category: analytics

#8246 Merge 11.4.0.2 to trunk
  Experiments/Experiments/ABTest.swift
  Gemfile
  Gemfile.lock
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Pluginfile
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8238 Login: Update unit tests for Jetpack setup
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/LoginJetpackSetupViewModel.swift
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/LoginJetpackSetupViewModelTests.swift
Labels: feature: login, category: unit tests

#8129 Fix 'imageEdgeInsets' was deprecated in iOS 15.0
  WooCommerce/Classes/Extensions/UIButton+TitleAndImage.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/Containers/BottomButtonContainer/BottomButtonContainerView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerInfoTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerNoteTableViewCell.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: technical debt, iOS 15

#8216 Store creation M2: checkout flow
  Experiments/Experiments/FeatureFlag.swift
  Networking/Networking/Remote/PaymentRemote.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/Plan/WebCheckoutViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Plan/WebPurchasesForWPComPlans.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/LoggedOutStoreCreationCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/StoreCreationCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/WebCheckoutViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/WebPurchasesForWPComPlansTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
Labels: type: enhancement, status: feature-flagged

#8249 Account creation: show loading state for the continue button after tapping it
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
Labels: type: bug

#8230 [Analytics Hub] Adds an AnalyticsLineChart view
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsLineChart.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: category: analytics

#8231 [Analytics Hub] Add line chart with placeholder data to AnalyticsReportCard
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsReportCard.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsReportCardViewModel.swift
Labels: category: analytics

#8244 [Analytics Hub] Update decimals handling logic
  WooCommerce/Classes/Extensions/Decimal+Helpers.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StatsDataTextFormatterTests.swift
Labels: feature: stats, status: feature-flagged

#8220 Add note regarding `\u{2011}` logging a `genstrings` warning
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalScanningForReader.swift
Labels: category: tooling, category: i18n

#8250 Update logged-out A/A test name and re-add logged-in A/A test
  Experiments/Experiments/ABTest.swift
Labels: category: experiments

#8179 Support account deletion for SIWA and with store creation features enabled
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/EmptyStoresTableViewCell.swift
  WooCommerce/Classes/Authentication/Epilogue/EmptyStoresTableViewCell.xib
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CloseAccountCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Settings/CloseAccountCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
Labels: type: task

#8228 [Just In Time Messages] Hide announcement when navigation bar is short
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: type: enhancement, feature: jitm

#8242 [Analytics Hub] Update Analytics cards with real line chart data
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsIntervalDataParser.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsPeriodViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Factories/StatsDataTextFormatterTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Factories/StatsIntervalDataParserTests.swift
Labels: category: analytics

#8192 [Mobile Payments] Add preflight controller for reader connection management
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: mobile payments, status: feature-flagged

#8195 [Mobile Payments] Remove viewController from CardReaderConnectionController
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CardPresentPaymentAlertsPresenter.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: mobile payments, status: feature-flagged
