Repository woocommerce/woocommerce-ios, pull requests merged in 2022-10, with the labels that each got.

#7807 Add docs and unit test for Model 70 CD migration
  Storage/Storage/Model/MIGRATIONS.md
  Storage/StorageTests/CoreData/MigrationTests.swift
Labels: type: technical debt, type: documentation

#7795 Site discovery: remember site credentials within the screen that connects to Jetpack through the WP.com account
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
Labels: type: enhancement, feature: login

#7814 Merge 10.6 code freeze to trunk
  .buildkite/release-builds.yml
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#7794 WP.com account creation: enable signup behind a feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/AuthenticationConstants.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: type: enhancement, feature: login

#7816 Show error when role eligibility request fails
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
Labels: type: bug, feature: login

#7780 Update Networking layer with GET `/wc-analytics/customers?search`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/WCAnalyticsCustomerMapper.swift
  Networking/Networking/Model/WCAnalyticsCustomer.swift
  Networking/Networking/Remote/WCAnalyticsCustomerRemote.swift
  Networking/NetworkingTests/Mapper/WCAnalyticsCustomerMapperTests.swift
  Networking/NetworkingTests/Remote/WCAnalyticsCustomerRemoteTests.swift
  Networking/NetworkingTests/Responses/wc-analytics-customers.json
Labels: type: enhancement, category: parity, feature: order creation

#7821 Store picker - Continue button loading state
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewModel.swift
Labels: type: task, feature: login

#7819 Bulk Update: Add analytics for bulk update variation prices feature
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/Bulk Edit Price/BulkUpdatePriceSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
Labels: category: analytics, feature: variation details

#7805 Lock Screen Widgets: Refactor StoreInfoWidget to support more widget families
  WooCommerce/StoreWidgets/Homescreen/StoreInfoView.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: widgets

#7806 Lock Screen Widgets: Add 3 stats widgets
  WooCommerce/StoreWidgets/Homescreen/StoreInfoView.swift
  WooCommerce/StoreWidgets/Lockscreen/StoreInfoCircularWidget.swift
  WooCommerce/StoreWidgets/Lockscreen/StoreInfoInlineWidget.swift
  WooCommerce/StoreWidgets/Lockscreen/StoreInfoRectangularWidget.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/CurrencyFormatterTests.swift
  WooFoundation/WooFoundation/Currency/CurrencyFormatter.swift
Labels: status: feature-flagged, feature: widgets

#7826 Fix /woocommerce-features webpage link
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
Labels: feature: login

#7825 Update release notes for 10.7
  CHANGELOG.md
Labels: Releases

#7827 Merge 10.6 final to trunk
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#7828 Merge 10.7 code freeze to trunk
  CHANGELOG.md
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#7829 Explicitly prevent `xcodebuild` from changing the binary's build number
  fastlane/Fastfile
Labels: Releases

#7838 Lock Screen Widgets: Update analytics
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/AppDelegate.swift
Labels: category: analytics, feature: widgets

#7840 Elevate: Remove A/B test condition for linked products promo
  Experiments/Experiments/ABTest.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
Labels: feature: product details

#7839 Lock Screen Widgets: Remove feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/StoreWidgets/Lockscreen/AppLinkWidget.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7824 CustomerSearchResults to Customer mapping logic
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CreateOrderAddressFormViewModel.swift
  Yosemite/Yosemite/Actions/CustomerAction.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: enhancement, category: parity, feature: order creation

#7841 Adds Storage layer for Customer and CustomerSearchResult
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/Customer+CoreDataClass.swift
  Storage/Storage/Model/Customer+CoreDataProperties.swift
  Storage/Storage/Model/CustomerSearchResult+CoreDataClass.swift
  Storage/Storage/Model/CustomerSearchResult+CoreDataProperties.swift
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 74.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
Labels: type: enhancement, category: parity, feature: order creation

#7740 Remove orders/totals request from notifications manager
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
  WooFoundation/WooFoundation/Extensions/Date+StartAndEnd.swift
Labels: feature: notifications, feature: order list, category: performance

#7845 Decode HTML in product categories names
  WooCommerce/Classes/ViewRelated/Products/Categories/ProductCategoryViewModelBuilder.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product+ProductForm.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Categories/ProductCategoryViewModelBuilderTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
Labels: feature: product details

#7837 [IAP] Add feature flag for In-app purchases
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: task, feature: in-app purchases

#7844 [ExPlat] Distinguish between logged-out and logged-in experiment assignments
  Experiments/Experiments/ABTest.swift
  WooCommerce/Classes/Analytics/TracksProvider.swift
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  docs/EXPERIMENTS.md
Labels: category: analytics

#7852 [ExPlat] Update logged-in A/A test (take 3)
  Experiments/Experiments/ABTest.swift
Labels: category: analytics

#7857 Reload product when review notification received
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
Labels: feature: product details

#7858 [Just In Time Messages] Send UTM params on card reader purchase links
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/AuthenticatedWebViewController.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/FeatureAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/UpsellCardReadersCampaign.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/PurchaseCardReaderWebViewViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModelTests.swift
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/Mocks/MockUTMParameterProvider.swift
  WooFoundation/WooFoundation/Utilities/UTMParameters.swift
  WooFoundation/WooFoundation/Utilities/WooCommerceComUTMProvider.swift
  WooFoundation/WooFoundationTests/Utilities/WooCommerceComUTMProviderTests.swift
  Yosemite/Yosemite/Model/Payments/CardPresentPaymentsConfiguration.swift
  Yosemite/YosemiteTests/Model/CardPresentConfigurationTests.swift
Labels: type: enhancement, feature: jitm

#7862 [Mobile Payments] Use AuthenticatedWebView from Upsell Card Reader Feature Cards
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/UpsellCardReadersCampaign.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsView.swift
Labels: feature: mobile payments

#7861 Home Screen Widgets: Update widget accessibility style condition for iOS 14
  WooCommerce/StoreWidgets/Homescreen/StoreInfoView.swift
Labels: feature: widgets

#7865 Merge 10.7 final to trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#7867 Added release notes for 10.8
  CHANGELOG.md
Labels: Releases

#7847 Login: Handle Jetpack site connection for self-hosted sites
  Networking/Networking/Network/AlamofireNetwork.swift
  Networking/Networking/Network/MockNetwork.swift
  Networking/Networking/Network/Network.swift
  Networking/Networking/Network/NullNetwork.swift
  Networking/Networking/Network/WordPressOrgNetwork.swift
  Networking/Networking/Remote/JetpackConnectionRemote.swift
  Networking/Networking/Remote/Remote.swift
  WooCommerce/Classes/Authentication/AuthenticatedWebViewController.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/JetpackConnectionWebViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULAccountMismatchViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/Classes/Extensions/NSMutableAttributedString+Helpers.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/ULAccountMismatchViewControllerTests.swift
  WooCommerce/WooCommerceTests/Authentication/WrongAccountErrorViewModelTests.swift
  Yosemite/Yosemite/Stores/JetpackConnectionStore.swift
Labels: type: enhancement, feature: login

#7874 Login: Update release notes for Jetpack site connection
  RELEASE-NOTES.txt
Labels: type: enhancement, feature: login

#7875 Implement networking for In-app purchases
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/InAppPurchaseOrderResultMapper.swift
  Networking/Networking/Mapper/InAppPurchasesProductMapper.swift
  Networking/Networking/Remote/InAppPurchasesRemote.swift
  Networking/NetworkingTests/Mapper/InAppPurchaseOrderResultMapperTests.swift
  Networking/NetworkingTests/Mapper/InAppPurchasesProductsMapperTests.swift
  Networking/NetworkingTests/Remote/InAppPurchasesRemoteTests.swift
  Networking/NetworkingTests/Responses/iap-order-create.json
  Networking/NetworkingTests/Responses/iap-products.json
  Networking/NetworkingTests/Responses/iap-sample-receipt.json
Labels: type: task, feature: in-app purchases

#7851 Bump deployment target to 15.0
  Experiments/Experiments.xcodeproj/project.pbxproj
  Fakes/Fakes.xcodeproj/project.pbxproj
  Hardware/Hardware.xcodeproj/project.pbxproj
  Networking/Networking.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Storage/Storage.xcodeproj/project.pbxproj
  TestKit/Package.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApllicationLogDetailView.swift
  WooCommerce/Classes/ViewRelated/Products/Media/CameraCaptureCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Media/DeviceMediaLibraryPicker.swift
  WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryImagePickerViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation.xcodeproj/project.pbxproj
  Yosemite/Yosemite.xcodeproj/project.pbxproj
Labels: type: task, feature: in-app purchases

#7870 In-app purchases debug screen
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/GeneralAppSettings.swift
  Storage/StorageTests/Model/AppSettings/GeneralAppSettingsTests.swift
  WooCommerce/Classes/Model/BetaFeature.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesConfiguration.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/YosemiteTests/Stores/AppSettings/InAppFeedbackCardVisibilityUseCaseTests.swift
  Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Labels: type: task, feature: in-app purchases

#7876 In-app purchases Yosemite implementation
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/Resources/WooProducts.storekit
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce.xcscheme
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/InAppPurchaseAction.swift
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
  Yosemite/Yosemite/Tools/InAppPurchases/AppAccountToken.swift
  Yosemite/YosemiteTests/Tools/InAppPurchases/AppAccountTokenTests.swift
Labels: type: task, feature: in-app purchases

#7883 Integrate InAppPurchaseStore with networking
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
Labels: type: task, feature: in-app purchases

#7873 Widgets Configuration: Add time interval setting
  WooCommerce/StoreWidgets/Homescreen/StoreInfoView.swift
  WooCommerce/StoreWidgets/StatsTimeRange.swift
  WooCommerce/StoreWidgets/StoreInfoDataService.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgets/StoreInfoWidget.swift
Labels: feature: widgets

#7893 Include real site ID in IAP purchases
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
Labels: type: bug, feature: in-app purchases

#7886 Store creation MVP: site picker entry point behind a feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/AuthenticatedWebViewController.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.xib
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationWebViewModel.swift
  WooCommerce/Classes/Extensions/Publisher+Concurrency.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: login

#7848 Customer Search: Coordinate `Customer` and `CustomerSearchResults` entities with Storage
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Customer.swift
  Networking/Networking/Model/WCAnalyticsCustomer.swift
  Networking/NetworkingTests/Responses/customer-2.json
  Storage/Storage/Tools/StorageType+Extensions.swift
  Storage/StorageTests/Tools/StorageTypeExtensionsTests.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CreateOrderAddressFormViewModel.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/Customer+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: enhancement, category: parity, feature: order creation

#7894 Updated release notes for 10.9
  CHANGELOG.md
Labels: Releases

#7895 Merge 10.8 final to trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#7896 Merge 10.9 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#7897 Store creation MVP: networking layer changes
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/AccountRemote.swift
  Networking/Networking/Remote/Remote.swift
  Networking/NetworkingTests/Remote/AccountRemoteTests.swift
  Networking/NetworkingTests/Remote/RemoteTests.swift
  Networking/NetworkingTests/Responses/account-username-suggestions.json
  Networking/NetworkingTests/Responses/create-account-error-email-exists.json
  Networking/NetworkingTests/Responses/create-account-error-invalid-email.json
  Networking/NetworkingTests/Responses/create-account-error-password.json
  Networking/NetworkingTests/Responses/create-account-error-username.json
  Networking/NetworkingTests/Responses/create-account-success.json
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockAccountRemote.swift
Labels: type: enhancement, feature: login

#7898 Store creation MVP: Yosemite layer changes
  Networking/Networking/Remote/AccountRemote.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/AccountCreationAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/AccountCreationStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockAccountRemote.swift
  Yosemite/YosemiteTests/Stores/AccountCreationStoreTests.swift
Labels: type: enhancement, feature: login

#7910 [Just In Time Messages] GET JITM network request
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/JustInTimeMessageListMapper.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/JustInTimeMessage.swift
  Networking/Networking/Remote/JustInTimeMessagesRemote.swift
  Networking/Networking/Remote/Remote.swift
  Networking/NetworkingTests/Mapper/JustInTimeMessageListMapperTests.swift
  Networking/NetworkingTests/Remote/JustInTimeMessagesRemoteTests.swift
  Networking/NetworkingTests/Responses/just-in-time-message-list.json
Labels: type: task, feature: jitm

#7877 [Products Onboarding] Add support for checking products onboarding eligibility
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductIDMapper.swift
  Networking/Networking/Remote/ProductsRemote.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/products-ids-only-empty.json
  Networking/NetworkingTests/Responses/products-ids-only.json
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: feature: product list

#7925 Products Onboarding: Adds feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: feature: products onboarding

#7906 Store creation MVP - account creation: form UI
  Networking/Networking/Settings/Credentials.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/ViewModels/Authentication/AccountCreationFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationFormFieldView.swift
  WooCommerce/Classes/Yosemite/DeauthenticatedState.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: login

#7880 Customer Search: Implement UI
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CreateOrderAddressFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/OrderCustomerListView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModelProtocol.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressForm.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, category: parity, feature: order creation

#7921 [Products Onboarding] Check for and track products onboarding eligibility
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: feature: stats, feature: product list

#7938 Products Onboarding: Present product template Type bottom sheet
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductCreationTypeCommand.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: feature: products onboarding

#7939 Products Onboarding: Show the product template bottom sheet for new-ish stores
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
Labels: feature: products onboarding

#7927 Store creation MVP: add entry point to prologue after account creation
  WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, status: feature-flagged

#7952 Account creation: add login CTA for existing users
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/ButtonStyles.swift
Labels: type: enhancement, feature: login

#7943 Products Preview: Add loginURL to Site
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Site.swift
  Networking/Networking/Remote/AccountRemote.swift
  Networking/NetworkingTests/Mapper/AccountMapperTests.swift
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Site+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 76.xcdatamodel/contents
  Storage/StorageTests/CoreData/ManagedObjectModelsInventoryTests.swift
  Storage/StorageTests/CoreData/MigrationTests.swift
  WooCommerce/WooCommerceUITests/Mocks/mappings/me/rest_v11_me_sites.json
  Yosemite/Yosemite/Model/Mocks/Graphs/ScreenshotsObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
Labels: type: task

#7955 AttributedText: fix SwiftUI issue on publishing changes from within view updates
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/AttributedText.swift
Labels: type: technical debt

#7937 [In-app Purchases] Send app receipt instead of transaction when creating order
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
  Yosemite/Yosemite/Tools/InAppPurchases/InAppPurchaseReceiptRefreshRequest.swift
Labels: type: task, feature: in-app purchases

#7954 Simplified Login: Unrecognized email address screen
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.xib
  WooCommerce/Classes/Extensions/UIFont+Helpers.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/NotWPAccountViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/ULErrorViewControllerTests.swift
  WooCommerce/WooCommerceTests/Internal/WordPressAuthenticator+Internal.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
Labels: type: task, feature: login

#7947 Products Onboarding: Restrict product types based on the creation type
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
Labels: feature: products onboarding

#7932 [Just In Time Messages] Load top JITM: Yosemite layer
  Fakes/Fakes/Yosemite.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/NetworkingTests/Responses/empty-data-array.json
  Networking/NetworkingTests/Responses/just-in-time-message-list-multiple.json
  Networking/NetworkingTests/Responses/just-in-time-message-list.json
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/JustInTimeMessageAction.swift
  Yosemite/Yosemite/Model/Copiable/Models+Copiable.generated.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/YosemiteJustInTimeMessage.swift
  Yosemite/Yosemite/Stores/JustInTimeMessageStore.swift
  Yosemite/YosemiteTests/Stores/JustInTimeMessageStoreTests.swift
Labels: type: task, feature: jitm

#7958 [In-app Purchases] Cancel receipt refresh when complete
  Yosemite/Yosemite/Tools/InAppPurchases/InAppPurchaseReceiptRefreshRequest.swift
Labels: type: bug, feature: in-app purchases

#7957 Update logged-out A/A test name, and remove completed A/B experiment
  Experiments/Experiments/ABTest.swift
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
Labels: type: task, category: analytics

#7929 Simplified login: Integrate the mimimal login screens
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationConstants.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/UITestsFoundation/Screens/Login/PrologueScreen.swift
  WooCommerce/WooCommerceUITests/Tests/LoginTests.swift
Labels: type: task, feature: login

#7940 Simplified Login: Update prologue screen
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Prologue/LoginProloguePages.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
Labels: type: task, feature: login

#7964 Store creation MVP: login entry point
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
Labels: type: enhancement, feature: login

#7948 [Just In Time Messages] Display Just In Time Message on the My Store screen (visual UI only)
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Networking/Networking/Model/JustInTimeMessage.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/FeatureAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/FeatureAnnouncementCardView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Stores/JustInTimeMessageStore.swift
Labels: type: enhancement, feature: jitm

#7956 Simplified login: Launch account creation flow from unrecognized email error screen.
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ULErrorViewController.swift
  WooCommerce/WooCommerceTests/Authentication/NotWPAccountViewModelTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
Labels: type: task, feature: login

#7967 Merge 10.9 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#7972 Pass signInSource while creating AccountCreationFormHostingController
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
Labels: type: bug, feature: login

#7959 [In-App Purchases] Site creation flow interface
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesForWPComPlansManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/InAppPurchaseAction.swift
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
Labels: type: task, feature: in-app purchases

#7975 Added release notes for 11.0
  CHANGELOG.md
Labels: Releases

#7981 Merge 11.0 code freeze into `trunk`
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#7962 Product Onboarding: Adds "Create Template" Endpoint
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/EntityIDMapper.swift
  Networking/Networking/Model/Product/ProductStatus.swift
  Networking/Networking/Remote/ProductsRemote.swift
  Networking/Networking/Settings/WooAPIVersion.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/product-id-only.json
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: feature: products onboarding

#7960 Product Preview: Add "Preview" button to product details
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: product details, status: feature-flagged

#7980 Products Onboarding: Add visual UI for banner to My Store dashboard
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/ProductsOnboardingAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: status: feature-flagged, feature: products onboarding

#7988 Products Onboarding: Update buttons for onboarding banner
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/FeatureAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/ProductsOnboardingAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/FeatureAnnouncementCardView.swift
Labels: status: feature-flagged, feature: products onboarding

#7961 Product Preview: Add WebView authentication tools
  WooCommerce/Classes/Authentication/WebAuth/AuthenticationService.swift
  WooCommerce/Classes/Authentication/WebAuth/CookieJar.swift
  WooCommerce/Classes/Authentication/WebAuth/RequestAuthenticator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockCookieJar.swift
  WooCommerce/WooCommerceTests/Tools/CookieJarTests.swift
  WooCommerce/WooCommerceTests/Tools/RequestAuthenticatorTests.swift
  WooCommerce/WooCommerceTests/Tools/WKCookieJarTests.swift
Labels: feature: product details

#7973 [Just In Time Messages] Open WebView for JITM Call to Action
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/UpsellCardReadersCampaign.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/WebView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/WebViewSheet.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/WooNavigationSheet.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: jitm

#7989 Products Onboarding: Add analytics for onboarding banner
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/ProductsOnboardingAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
Labels: category: analytics, status: feature-flagged, feature: products onboarding
