Repository woocommerce/woocommerce-ios, pull requests merged in 2023-08, with the labels that each got.

#10358 Store creation: Remove feature flag for free trial
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift
Labels: type: technical debt

#10363 [IAP] Improve voiceover on woo express plans screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Upgrades/FullFeatureListView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/WooPlanCardView.swift
Labels: type: task, category: accessibility, feature: in-app purchases

#10341 Enable Google SDK-less login in production
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: feature: login, category: tooling

#10365 [Better Customer Selection] Add selected customer information to the order
  Networking/Networking/Model/Customer.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/OrderCustomerSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  Yosemite/Yosemite/Model/Storage/Customer+ReadOnlyConvertible.swift
Labels: type: task, feature: order creation

#10360 Store creation: Remove web store creation
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/StoreCreationCoordinatorTests.swift
Labels: type: technical debt

#10370 [Better Customer Selection] Add/Edit Customer
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/OrderCustomerSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressForm.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
Labels: type: task, feature: order creation

#10362 Store creation: Remove outdated feature flags and enable store creation by default
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Plan/WebPurchasesForWPComPlans.swift
  WooCommerce/Classes/Extensions/WordPressAuthenticator+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/NotWPAccountViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/WebPurchasesForWPComPlansTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
Labels: type: technical debt

#10369 Add banner to purchase a paid plan for WooExpress sites with expired plan
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/StorePlanBanner.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/StorePlanBannerPresenter.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
Labels: type: task

#10377 [Profiler] Cleanup feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationSummaryView.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
Labels: type: task

#10379 [Optimize profiler] Add feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
Labels: type: task

#10387 [Profiler] Challenges question screen UI
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreCreation.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Challenges/StoreCreationChallengesQuestionOptions.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Challenges/StoreCreationChallengesQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Challenges/StoreCreationChallengesQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationChallengesQuestionViewModelTests.swift
Labels: type: task

#10378 Unit tests for `StorePlanBannerPresenter`
  WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/LegacyUpgradesViewModel.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/StorePlanBannerPresenter.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/Classes/ViewRelated/Upgrades/SubscriptionsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockConnectivityObserver.swift
  WooCommerce/WooCommerceTests/Mocks/MockPushNotificationsManager.swift
  WooCommerce/WooCommerceTests/Mocks/MockStorePlanSynchronizer.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Free Trial/StorePlanBannerPresenterTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
Labels: category: unit tests

#10384 RequirementsChecker: navigate to IAP for sites with expired WooExpress plans
  Networking/Networking/Model/Site.swift
  Networking/Networking/Settings/WooConstants.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/RequirementsChecker.swift
  WooCommerce/WooCommerceTests/Tools/RequirementsCheckerTests.swift
Labels: type: bug

#10395 [Better customer selection] Add username to model
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Customer.swift
  Networking/Networking/Model/WCAnalyticsCustomer.swift
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/Customer+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 93.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Customer/CustomerSearchUICommandTests.swift
  Yosemite/Yosemite/Model/Storage/Customer+ReadOnlyConvertible.swift
Labels: type: task, feature: order creation

#10388 Update ScreenObject package to latest
  WooCommerce.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, category: ui tests

#10373 Sentry: Disable tracking HTTP client errors and app hangs
  Podfile
  Podfile.lock
  WooCommerce/Classes/Tools/Logging/WooCrashLoggingStack.swift
Labels: type: enhancement, category: tooling

#10382 Product list filter: add extension product types
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Filters/FilterProductListViewModel.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStore+FilterProductsTests.swift
Labels: type: enhancement, category: woo extensions, feature: product list

#10397 Track product list filter tapped/applied events for all sources
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ProductListFilter.swift
  WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift
  WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/UsageDetails/CouponRestrictions.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorNavigationView.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: product list, category: analytics

#10404 Merge 14.7 final to trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/description.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/description.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/description.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/description.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10405 Merge 14.8 code freeze to trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#10371 [Better Customer Selection] Empty/Error Screen
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Customer/CustomerSearchUICommandTests.swift
  Yosemite/Yosemite/Actions/CustomerAction.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: task, feature: order creation

#10391 [Better Customer Selection] Older WooCommerce plugin clients
  Networking/Networking/Remote/WCAnalyticsCustomerRemote.swift
  Networking/NetworkingTests/Remote/WCAnalyticsCustomerRemoteTests.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewModel.swift
  WooCommerce/Resources/Images.xcassets/woo-customer-search.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-customer-search.imageset/customer-search.pdf
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewModelTests.swift
  Yosemite/Yosemite/Actions/CustomerAction.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: task, feature: order creation

#10411 [Better Customer Selection] Add pagination to search
  Networking/Networking/Remote/WCAnalyticsCustomerRemote.swift
  Networking/NetworkingTests/Remote/WCAnalyticsCustomerRemoteTests.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  Yosemite/Yosemite/Actions/CustomerAction.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: task, feature: order creation

#10412 [Better Customer Selection] Tracking
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModelProtocol.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Addresses/EditOrderAddressFormViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Customer/CustomerSearchUICommandTests.swift
Labels: type: task, feature: order creation

#10403 [Better customer selection] Underline search term in customer cell fields
  WooCommerce/Classes/Extensions/NSMutableAttributedString+Helpers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/OrderCustomerListView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TitleAndSubtitleAndDetailTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/UnderlineableTitleAndSubtitleAndDetailTableViewCell.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/UnderlineableTitleAndSubtitleAndDetailTableViewCell.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: order creation

#10366 [IAP] Updated design for Free Trial summary cards
  WooCommerce/Classes/ViewRelated/Upgrades/CurrentPlanDetailsView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/LegacyUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/SubscriptionsViewModel.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
Labels: type: task, feature: in-app purchases

#10436 Merge 14.7.1 hotfix to release/14.8
  RELEASE-NOTES.txt
  WooCommerce.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WooCommerce/Classes/Analytics/ReactNativeAnalyticsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: Releases

#10413 [Better Customer Selection] Fix Search Logic issues
  Networking/Networking/Remote/WCAnalyticsCustomerRemote.swift
  Networking/NetworkingTests/Remote/WCAnalyticsCustomerRemoteTests.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
Labels: type: task, feature: order creation

#10401 Store creation: Update profiler flow
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Challenges/StoreCreationChallengesQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Features/StoreCreationFeaturesQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingStatusQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#10424 Profiler: Split country question into 2 screens
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionView.swift
Labels: type: task

#10438 Blaze: Check for existing order to update Blaze banner visibility
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
  Yosemite/Yosemite/Actions/OrderAction.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: type: task

#10423 [Better Customer Selection] Show ghost animation when all customers are loading
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/UnderlineableTitleAndSubtitleAndDetailTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Customer/CustomerSearchUICommandTests.swift
  WooFoundation/WooFoundation/Colors/UIColor+SemanticColors.swift
  Yosemite/Yosemite/Actions/CustomerAction.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Mocks/MockStorageManager+Sample.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: task, feature: order creation

#10441 Update `.contentEdgeInsets` for refund view controller to newest API
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewController.swift
Labels: type: task, feature: refunds, iOS 15

#10440 Store creation profiler: Update wording and assets for loading screen
  WooCommerce/Classes/Authentication/Store Creation/Progress/StoreCreationProgressView.swift
  WooCommerce/Classes/Authentication/Store Creation/Progress/StoreCreationProgressViewModel.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Resources/Images.xcassets/store-creation-progress-1.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-creation-progress-1.imageset/loading1-light&dark.svg
  WooCommerce/Resources/Images.xcassets/store-creation-progress-2.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-creation-progress-2.imageset/loading2-light&dark.svg
  WooCommerce/Resources/Images.xcassets/store-creation-progress-3.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-creation-progress-3.imageset/loading3-light&dark.svg
  WooCommerce/Resources/Images.xcassets/store-creation-progress-4.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-creation-progress-4.imageset/loading4-light&dark.svg
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-gift.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-gift.imageset/store-creation-progress-bg-gift.png
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-gift.imageset/store-creation-progress-bg-gift@2x.png
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-gift.imageset/store-creation-progress-bg-gift@3x.png
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-woman.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-woman.imageset/store-creation-progress-bg-woman.png
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-woman.imageset/store-creation-progress-bg-woman@2x.png
  WooCommerce/Resources/Images.xcassets/store-creation-progress-bg-woman.imageset/store-creation-progress-bg-woman@3x.png
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Progress/StoreCreationProgressViewModelTests.swift
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task

#10452 Store creation: Update alerts wording and actions.
  WooCommerce/Classes/Authentication/Store Creation/Free Trial/FreeTrialSummaryView.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
Labels: type: task

#10425 [Better Customer Selection] Enable Feature
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: type: task, feature: order creation

#10457 [Better Customer Selector] Do not adjust table view bottom inset when showing the customer list.
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
Labels: type: task, feature: order creation

#10420 Telemetry: track & send installation date
  Networking/Networking/Remote/TelemetryRemote.swift
  Networking/NetworkingTests/Extensions/MockNetwork+Path.swift
  Networking/NetworkingTests/Remote/TelemetryRemoteTests.swift
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  Yosemite/Yosemite/Actions/TelemetryAction.swift
  Yosemite/Yosemite/Stores/TelemetryStore.swift
  Yosemite/YosemiteTests/Stores/TelemetryStoreTests.swift
Labels: category: analytics

#10461 Merge 14.8.0.1 to trunk
  WooCommerce.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10455 Store creation: Integrate API to update store title
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Remote/SiteRemoteTests.swift
  Networking/NetworkingTests/Responses/site-settings-success.json
  Yosemite/Yosemite/Actions/SiteAction.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockSiteRemote.swift
  Yosemite/YosemiteTests/Stores/SiteStoreTests.swift
Labels: type: task

#10347 [Local notification] Remove 24h notification remote feature flag
  Networking/Networking/Remote/FeatureFlagRemote.swift
  Networking/NetworkingTests/Remote/FeatureFlagRemoteTests.swift
  Networking/NetworkingTests/Responses/feature-flags-load-all.json
Labels: type: task

#10462 [Free trial] Remove code for deprecated local notifications
  Networking/Networking/Remote/FeatureFlagRemote.swift
  Networking/NetworkingTests/Remote/FeatureFlagRemoteTests.swift
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationSchedulerTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationTests.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
  Yosemite/YosemiteTests/Stores/FeatureFlagStoreTests.swift
Labels: type: task

#10464 Fix flaky unit test
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Progress/StoreCreationProgressViewModelTests.swift
Labels: type: bug

#10454 Address memory leak when adding new notes to order
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/Add Order Note/NewNoteViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/Add Order Note/NewNoteViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: bug, type: task, feature: order details

#10468 Merge 14.8 final into trunk
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10469 Merge 14.9 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#10458 [In-Person Payments] Improve data tracking for all Payment Methods
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift
  WooFoundation/WooFoundation/Currency/CurrencyCode.swift
Labels: feature: mobile payments, category: analytics

#10466 Store onboarding: Handle store name setup
  Networking/Networking/Remote/SiteRemote.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreName/StoreNameSetupView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreName/StoreNameSetupViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreNameSetupViewModelTests.swift
  Yosemite/Yosemite/Actions/SiteAction.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
Labels: type: task

#10475 Store profiler: Add unit tests for `StoreCreationProfilerQuestionContainerViewModel`
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModel.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModelTests.swift
Labels: type: task, category: unit tests

#10465 Store onboarding: Add new local task for updating store title
  Networking/Networking/Model/Site.swift
  Networking/Networking/Model/StoreOnboardingTask.swift
  Networking/Networking/Remote/SiteRemote.swift
  Networking/Networking/Settings/WooConstants.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreOnboarding.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreName/StoreNameSetupView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreName/StoreNameSetupViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreNameSetupViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
  Yosemite/Yosemite/Actions/SiteAction.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
Labels: type: task

#10459 Store creation: API to upload profiler answers
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Remote/SiteRemoteTests.swift
  Networking/NetworkingTests/Responses/site-upload-profiler-answers-success.json
  Yosemite/Yosemite/Actions/SiteAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockSiteRemote.swift
  Yosemite/YosemiteTests/Stores/SiteStoreTests.swift
Labels: type: task

#10460 Store creation: Usecase to store and upload profiler answers
  Networking/Networking/Remote/SiteRemote.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerUploadAnswersUseCase.swift
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationProfilerUploadAnswersUseCaseTests.swift
  WooCommerce/WooCommerceTests/System/SessionManagerTests.swift
Labels: type: task

#10480 Merge 14.9 release notes into trunk
  CHANGELOG.md
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#10476 Remove unnecessary reload call in `OrderDetails`
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
Labels: type: bug, feature: order details, type: technical debt

#10471 Store creation: Make new profiler flow default
  Networking/Networking/Remote/SiteRemote.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreCreation.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingStatusQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/StoreCreationCoordinatorTests.swift
Labels: type: task

#10479 Store profiler: Update category values to match core profiler
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionOptions.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationCategoryQuestionViewModelTests.swift
Labels: type: task

#10482 Update deprecated `accentColor(_:)` in favor of `tint(_:)`
  WooCommerce/Classes/ViewRelated/Authentication/AuthenticationFormFieldView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApllicationLogDetailView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/Package Selection/Package Creation/ShippingLabelAddNewPackage.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/RangedDatePicker.swift
  WooFoundation/WooFoundation/ViewModifiers/WooStyleModifiers.swift
Labels: type: enhancement, type: task, category: design

#10473 Store profiler: Upload answers from dashboard screen
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockStoreCreationProfilerUploadAnswersUseCase.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
Labels: type: task

#10477 Store profiler: Remove unused code
  Networking/Networking/Remote/FeatureFlagRemote.swift
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Remote/FeatureFlagRemoteTests.swift
  Networking/NetworkingTests/Remote/SiteRemoteTests.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationSchedulerTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationTests.swift
  Yosemite/Yosemite/Actions/SiteAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockSiteRemote.swift
  Yosemite/YosemiteTests/Stores/FeatureFlagStoreTests.swift
  Yosemite/YosemiteTests/Stores/SiteStoreTests.swift
Labels: type: task

#10486 Store profiler: Clean up dead code
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Challenges/StoreCreationChallengesQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Challenges/StoreCreationChallengesQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Features/StoreCreationFeaturesQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Features/StoreCreationFeaturesQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/OptionalStoreCreationProfilerQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/RequiredStoreCreationProfilerQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingPlatformsQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingStatusQuestionContainerView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingStatusQuestionViewModel.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationCategoryQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationChallengesQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationCountryQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationFeaturesQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationSellingPlatformsQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationSellingStatusQuestionViewModelTests.swift
Labels: type: technical debt

#10485 Store onboarding: Show notice after setting store name and add new Setting item for store name
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
Labels: type: task, feature: app settings

#10487 Store profiler: Track profiler info
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreCreation.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionOptions.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Challenges/StoreCreationChallengesQuestionOptions.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Features/StoreCreationFeaturesQuestionOptions.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingPlatformsQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationChallengesQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationFeaturesQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModelTests.swift
Labels: type: task

#10489 Store profiler: Cleanup
  WooCommerce/Classes/Authentication/Store Creation/Store name/StoreNameForm.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/StoreCreationCoordinatorTests.swift
Labels: type: task

#10491 Store Picker: Navigate to IAP for sites with expired WooExpress plans
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
Labels: type: task

#10494 Optimize store profiler: remove feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
Labels: type: task

#10484 Track store snapshot when the merchant uses a store for the first time
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductsTotalMapper.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Customer.swift
  Networking/Networking/Model/OrderStatus.swift
  Networking/Networking/Remote/ProductsRemote.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/products-total.json
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/Tools/CardPresentPluginsDataProvider.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/Classes/Yosemite/SiteSnapshotTracker.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyCollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/Yosemite/SiteSnapshotTrackerTests.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Actions/SystemStatusAction.swift
  Yosemite/Yosemite/Model/Mocks/ActionHandlers/MockSystemStatusActionHandler.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/Yosemite/Stores/SystemStatusStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
  Yosemite/YosemiteTests/Stores/SystemStatusStoreTests.swift
Labels: category: analytics

#10500 [IAP] Show monthly plans before yearly plans
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
Labels: type: task, feature: in-app purchases

#10501 [IAP] Don't show free domain on monthly plans
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradeViewState.swift
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  Yosemite/Yosemite/Model/WooPlans/WooPlan.swift
Labels: type: task, feature: in-app purchases

#10502 Settings: Move Close Account to a new section Account Settings
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/AccountSettings/AccountSettingsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
Labels: type: task, feature: app settings

#10498 Update CHANGELOG.md for 15.0
  CHANGELOG.md
Labels: Releases

#10505 Merge 15.0 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/metadata/default/description.txt
Labels: Releases

#10507 Point Tracks to a stable version instead of `trunk`
  Podfile
  Podfile.lock
Labels: dependencies

#10493 Remove `ReviewsCoordinator`
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Notifications/ReviewsCoordinatorTests.swift
Labels: type: task, type: technical debt

#10497 [IAP] Remove iap plan purchase M1 code
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/LegacyUpgradeViewState.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/LegacyUpgradesViewModel.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/WooWPComPlan.swift
  WooCommerce/Classes/ViewRelated/Upgrades/LegacyOwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/LegacyUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/WooPlanCardView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/WooPlanFeatureBenefitsView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/WooPlanFeatureGroupRow.swift
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-essential-header.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-essential-header.imageset/express-essential-header.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-essential-header.imageset/express-essential-header@2x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-essential-header.imageset/express-essential-header@3x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-card-payment-webpage.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-card-payment-webpage.imageset/express-plans-card-payment-webpage.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-card-payment-webpage.imageset/express-plans-card-payment-webpage@2x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-card-payment-webpage.imageset/express-plans-card-payment-webpage@3x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-design-colors-typography.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-design-colors-typography.imageset/express-plans-design-colors-typography.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-design-colors-typography.imageset/express-plans-design-colors-typography@2x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-design-colors-typography.imageset/express-plans-design-colors-typography@3x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-homepage.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-homepage.imageset/express-plans-homepage.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-homepage.imageset/express-plans-homepage@2x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-homepage.imageset/express-plans-homepage@3x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-shipping-manifest.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-shipping-manifest.imageset/express-plans-shipping-manifest.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-shipping-manifest.imageset/express-plans-shipping-manifest@2x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-shipping-manifest.imageset/express-plans-shipping-manifest@3x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-two-product-webpages.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-two-product-webpages.imageset/express-plans-two-product-webpages.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-two-product-webpages.imageset/express-plans-two-product-webpages@2x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-two-product-webpages.imageset/express-plans-two-product-webpages@3x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-webpage-in-envelope.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-webpage-in-envelope.imageset/express-plans-webpage-in-envelope.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-webpage-in-envelope.imageset/express-plans-webpage-in-envelope@2x.png
  WooCommerce/Resources/Images.xcassets/express-plan-upgrade-images/express-plans-webpage-in-envelope.imageset/express-plans-webpage-in-envelope@3x.png
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/WooPlans/LegacyWooPlan.swift
  Yosemite/Yosemite/Model/WooPlans/WooPlan.swift
  Yosemite/Yosemite/Model/WooPlans/WooPlanFeatureGroup.swift
Labels: type: task, feature: in-app purchases

#10517 [Manual Taxes] Add Feature Flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: task, feature: order creation

#10508 Remove stale feature flags for login
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Extensions/WordPressAuthenticator+Woo.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift
Labels: type: technical debt

#10522 [Coupons] Configure navigation bar items when data is loaded.
  WooCommerce/Classes/ViewRelated/Coupons/EnhancedCouponListViewController.swift
Labels: type: bug, feature: coupons

#10521 Add support for `enabled` payment gateway status
  Networking/Networking/Model/WCPayAccountStatusEnum.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift
  Yosemite/Yosemite/Model/Enums/CardPresentPaymentsOnboardingState.swift
Labels: type: bug, feature: mobile payments

#10509 Add a source parameter to the shipping label purchase API request for revenue attribution
  Networking/Networking/Remote/ShippingLabelRemote.swift
  Networking/NetworkingTests/Remote/ShippingLabelRemoteTests.swift
Labels: feature: shipping labels, category: analytics

#10527 Update Release Toolkit from 8.1.0 to 9.0.0
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: category: tooling

#10528 Store profiler: Store each answer
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Remote/SiteRemoteTests.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationProfilerQuestionContainerViewModelTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockStoreCreationProfilerUploadAnswersUseCase.swift
Labels: type: task

#10524 [Manual Taxes] Tax lines UI
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/TaxLineViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/Extensions/Double+Woo.swift
Labels: type: task, feature: order creation

#10537 Switch store upon tapping store ready notification
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationSchedulerTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationTests.swift
Labels: type: task

#10538 Update CHANGELOG.md for 15.1
  CHANGELOG.md
Labels: Releases

#10533 Order list tracks event
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
Labels: type: task

#10535 [Manual Taxes] Show 'tax based on' setting
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
Labels: type: task, feature: order creation

#10519 [Mobile Payments] Remove legacy collect payment
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/PaymentCaptureOrchestrator.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentAnalytics.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockCardPresentPaymentAlertsPresenter.swift
  WooCommerce/WooCommerceTests/Mocks/MockCardPresentPaymentPreflightController.swift
  WooCommerce/WooCommerceTests/Mocks/MockCollectOrderPaymentAnalyticsTracker.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyCollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Simple Payments/MockCollectOrderPaymentUseCase.swift
Labels: type: task, feature: mobile payments

#10523 [Mobile Payments] Remove legacy payment orchestrator
  Hardware/Hardware/CardReader/PaymentIntentParameters.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/LegacyPaymentCaptureOrchestrator.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/PaymentCaptureOrchestrator.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockPaymentCaptureOrchestrator.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyPaymentCaptureOrchestratorTests.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/PaymentCaptureOrchestratorTests.swift
Labels: type: task, feature: mobile payments

#10526 [Mobile Payments] Move legacy connection controller tests to new code
  WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockCardPresentPaymentAlertsPresenter.swift
  WooCommerce/WooCommerceTests/Mocks/MockCardReaderSettingsAlerts.swift
  WooCommerce/WooCommerceTests/UnitTests.xctestplan
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/RefundSubmissionUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardReaderConnectionControllerTests.swift
Labels: type: task, feature: mobile payments

#10531 [Mobile Payments] Remove legacy connection controller
  WooCommerce/Classes/ViewRelated/CardPresentPayments/LegacyCardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsSearchingViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: mobile payments

#10540 [What's New] Support dark mode for What's New announcement icons
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/AdaptiveAsyncImage.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/AdaptiveImage.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/BadgeView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/FeatureAnnouncementCardView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/IconListItem.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/JustInTimeMessageModal.swift
  WooCommerce/Classes/ViewRelated/WhatsNew/WhatsNewFactory.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: announcements

#10542 Merge 15.0 final into trunk
  Podfile
  Podfile.lock
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10544 Add missing `PUBLIC_CONFIG_FILE` env var
  fastlane/Fastfile
Labels: category: tooling

#10541 Order list tracking: Use cached order status
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
Labels: type: task

#10546 [Manual Taxes] Educational Dialog
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/Taxes/TaxEducationalDialogView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/Taxes/TaxEducationalDialogViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/Taxes/TaxLineViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/PaymentSection/Taxes/TaxEducationalDialogViewModelTests.swift
Labels: type: task, feature: order creation

#10529 Centralize iOS deployment target definition in `xcconfig`
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  config/Common.xcconfig
  config/WooCommerce.debug.xcconfig
  config/WooCommerce.release.xcconfig
Labels: category: tooling

#10549 Prologue: Update buttons' styles and positions
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/Prologue/LoginProloguePages.swift
Labels: type: task, feature: login

#10555 Store creation profiler: Fix UI bugs
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Store Creation/Free Trial/FreeTrialSummaryView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/OptionalStoreCreationProfilerQuestionView.swift
Labels: type: bug, category: design

#10550 [Manual Taxes] Tracking
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/Taxes/TaxEducationalDialogView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/Taxes/TaxEducationalDialogViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/PaymentSection/Taxes/TaxEducationalDialogViewModelTests.swift
Labels: type: task, category: analytics

#10564 [Manual Taxes M2] Add Feature Flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: task, feature: order creation

#10578 Fastlane: Automatically distribute builds to TestFlight
  .buildkite/commands/release-build.sh
  fastlane/Fastfile
Labels: Releases

#10569 [Manual Taxes] Remove feature flag for Milestone 1
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
Labels: type: task, feature: order creation

#10575 Fix `application_store_snapshot` event not showing up in Tracks
  WooCommerce/Classes/Yosemite/SiteSnapshotTracker.swift
  WooCommerce/WooCommerceTests/Yosemite/SiteSnapshotTrackerTests.swift
Labels: type: bug, category: analytics

#10586 Merge 15.1.0.2 into trunk
  WooCommerce/Classes/Yosemite/SiteSnapshotTracker.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerceTests/Yosemite/SiteSnapshotTrackerTests.swift
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10579 WCPay setup instructions screen
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/LaunchStore/StoreOnboardingLaunchStoreCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/LaunchStore/StoreOnboardingLaunchStoreView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/LaunchStore/StoreOnboardingLaunchStoreViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/LaunchStore/StoreOnboardingStoreLaunchedView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/StoreOnboardingPaymentsSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/StoreOnboardingPaymentsSetupView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/WooPaymentsSetupInstructionsView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/LearnMoreAttributedText.swift
  WooCommerce/Resources/Images.xcassets/woo-payments-badge.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-payments-badge.imageset/woo-payments-badge.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task

#10572 Store onboarding: Update payment task description, priority and URL
  Networking/Networking/Model/StoreOnboardingTask.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/StoreOnboardingPaymentsSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
  Yosemite/YosemiteTests/Stores/StoreOnboardingTasksStoreTests.swift
Labels: type: task

#10576 Store onboarding: Dismiss payment setup web view when setup completes
  WooCommerce/Classes/Authentication/AuthenticatedWebViewModel.swift
  WooCommerce/Classes/Authentication/WPAdminWebViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/StoreOnboardingPaymentsSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/WooPaymentSetupWebViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/WooPaymentSetupWebViewModelTests.swift
Labels: type: task

#10568 [Manual Taxes M2] Add "Set New Tax Rate" section to Editable Order Details
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
Labels: type: task, feature: order creation

#10591 Store onboarding: Update analytics for WCPay setup
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreOnboarding.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/StoreOnboardingPaymentsSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
Labels: type: task, category: analytics

#10593 Store onboarding: Update different priorities for wcpay and payment tasks
  Networking/Networking/Model/StoreOnboardingTask.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
  Yosemite/YosemiteTests/Stores/StoreOnboardingTasksStoreTests.swift
Labels: type: task

#10594 Store onboarding: WCPay setup celebration view
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/StoreOnboardingPaymentsSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/WooPaymentSetupCelebrationView.swift.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/Payments/WooPaymentSetupWebViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Resources/Images.xcassets/woo-payments-badge.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/woo-payments-badge.imageset/woo-payments-badge-dark.pdf
  WooCommerce/Resources/Images.xcassets/woo-payments-badge.imageset/woo-payments-badge-light.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#10597 [Manual Taxes M2] Add TaxRate to model
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/TaxRate+CoreDataClass.swift
  Storage/Storage/Model/TaxRate+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 95.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
Labels: type: task, feature: order creation
