Repository woocommerce/woocommerce-ios, pull requests merged in 2023-03, with the labels that each got.

#9001 REST API: Check passwordless account for the input WPCom email
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Extensions/WordPressAuthenticator+Woo.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/JetpackSetupCoordinatorTests.swift
Labels: status: feature-flagged, feature: REST API

#8967 Store onboarding > custom domains task: navigate to custom domains
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+DomainSettings.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinatorTests.swift
Labels: type: task

#8991 [Store Onboarding] Polish store setup card UI
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
Labels: type: task

#9005 [Store Onboarding] Feedback for store setup
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreSetupProgressView.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyViewControllerTests.swift
Labels: type: task

#8984 SPE: Remove downloadable setting from product settings
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsSections.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsSectionsTests.swift
Labels: feature: add/edit products, status: feature-flagged

#9012 Update GitHub issue templates.
  .github/ISSUE_TEMPLATE/Enhancement.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: type: task

#9004 SPE: Add Simplified Product Editing experiment
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/DefaultFeatureFlagService.swift
Labels: feature: add/edit products, category: experiments

#8989 [Product Multi-selection] Adapt UI tests for `test_create_new_order`
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift
  WooCommerce/UITestsFoundation/Screens/Orders/AddProductScreen.swift
  WooCommerce/UITestsFoundation/Screens/Orders/UnifiedOrderScreen.swift
  WooCommerce/WooCommerceUITests/Tests/OrdersTests.swift
Labels: type: task, category: ui tests, feature: order creation

#9019 Track `signed_in` event during site credentials login
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: type: bug

#9020 Merge 12.4.1 hotfix into `release/12.5`
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: Releases

#9009 REST API: Integrate authentication link request
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Extensions/WordPressAuthenticator+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/JetpackSetupCoordinatorTests.swift
Labels: status: feature-flagged, feature: REST API

#9008 [Support Request] Add site URL request in support form
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportForm.swift
Labels: type: enhancement, feature: support

#9013 [Mobile Payments] Prepare Manage card reader code for reuse
  WooCommerce/Classes/ViewRelated/Dashboard/Dashboard.storyboard
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BluetoothCardReaderSettingsConnectedViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsConnectedViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsSearchingViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsSearchingViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsViewModelPresenter.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsViewModelsOrderedList.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowHint.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowPresentedViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowPresentingViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowPrioritizedViewModelsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowViewModelPresenter.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: mobile payments

#9023 [Mobile Payments] Enable Tap to Pay for all users
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Model/BetaFeature.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
Labels: type: task, feature: mobile payments

#9006 Support Request: Update Zendesk Routing
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormsDataSources.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/Tools/Support/SupportDataSourcesTests.swift
  WooCommerce/WooCommerceTests/Tools/ZendeskManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyCoordinatorControllerTests.swift
Labels: feature: support

#8995 [Product Multi-selection] Hide clear selection button for product multi-selection
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductVariationSelector.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductVariationSelectorViewModel.swift
Labels: type: task, feature: order creation

#9017 [Store onboarding] Network and Yosemite to fetch tasks
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/StoreOnboardingTaskListMapper.swift
  Networking/Networking/Model/StoreOnboardingTask.swift
  Networking/Networking/Remote/StoreOnboardingTasksRemote.swift
  Networking/NetworkingTests/Mapper/StoreOnboardingTaskListMapperTests.swift
  Networking/NetworkingTests/Remote/StoreOnboardingTasksRemoteTests.swift
  Networking/NetworkingTests/Responses/store-onboarding-tasks-without-data.json
  Networking/NetworkingTests/Responses/store-onboarding-tasks.json
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/StoreOnboardingTasksAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/StoreOnboardingTasksStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockStoreOnboardingTasksRemote.swift
  Yosemite/YosemiteTests/Stores/StoreOnboardingTasksStoreTests.swift
Labels: type: task

#9021 REST API: UI for magic link screen
  Podfile.lock
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComMagicLinkView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComMagicLinkViewModel.swift
  WooCommerce/Resources/Images.xcassets/email.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/email.imageset/email.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/WPComLogin/WPComMagicLinkViewModelTests.swift
Labels: status: feature-flagged, feature: REST API

#9022 REST API: Password login UI
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComPasswordLoginView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComPasswordLoginViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/ButtonStyles.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/WPComLogin/WPComPasswordLoginViewModelTests.swift
Labels: status: feature-flagged, feature: REST API

#9030 Added release notes for 12.6
  CHANGELOG.md
Labels: Releases

#9025 [Product Bundles] Add ProductBundleItem model for items in a product bundle
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductBundle/ProductBundleItem.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/product-bundle.json
  WooCommerce/Classes/Extensions/Product+SwiftUIPreviewHelpers.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/ProductFactory.swift
  WooCommerce/WooCommerceTests/Mocks/MockReviews.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
  Yosemite/Yosemite/Model/Mocks/MockObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: category: woo extensions

#9026 [Product Bundles] Add bundle type to ProductType model
  Networking/Networking/Model/Product/ProductType.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductTypeBottomSheetListSelectorCommand.swift
Labels: category: woo extensions

#9039 Set woocommerce-payment tag for IPP tickets
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormsDataSources.swift
  WooCommerce/WooCommerceTests/Tools/Support/SupportDataSourcesTests.swift
Labels: feature: support

#9038 Merge 12.5 final into trunk
  .configure
  .configure-files/woo_app_credentials.json.enc
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8982 [Shipping Label] Add condition checks before showing "Email" and "Message" actions
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/PhoneHelper.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift
Labels: feature: shipping labels

#9041 Merge 12.6 code freeze into trunk
  Podfile.lock
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#9015 [Mobile Payments] Add tap to pay setup screen
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsConnectedViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayViewModelsOrderedList.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Resources/Images.xcassets/built-in-reader-set-up.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-set-up.imageset/illustration - Set up Tap to Pay - dark.png
  WooCommerce/Resources/Images.xcassets/built-in-reader-set-up.imageset/illustration - Set up Tap to Pay - dark@2x.png
  WooCommerce/Resources/Images.xcassets/built-in-reader-set-up.imageset/illustration - Set up Tap to Pay - dark@3x.png
  WooCommerce/Resources/Images.xcassets/built-in-reader-set-up.imageset/illustration - Set up Tap to Pay - light.png
  WooCommerce/Resources/Images.xcassets/built-in-reader-set-up.imageset/illustration - Set up Tap to Pay - light@2x.png
  WooCommerce/Resources/Images.xcassets/built-in-reader-set-up.imageset/illustration - Set up Tap to Pay - light@3x.png
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: mobile payments

#9036 [Mobile Payments] Add cancel button on Tap to Pay set up screen
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowHint.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsLearnMore.swift
Labels: type: enhancement, feature: mobile payments

#9035 [Product Bundles] Add "Bundled products" row to product details
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
Labels: category: woo extensions, status: feature-flagged

#9037 [Product Bundles] Add and navigate to a Bundled Products list view
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Addons/ProductAddOnsListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/FooterNotice.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: category: woo extensions, status: feature-flagged

#9049 Only authenticate wp-admin if site is wpcom or if logged in with site credentials
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift
Labels: type: bug, feature: hub menu

#9069 Widget: Load revenue and orders when logged in with site credentials
  WooCommerce/Classes/Authentication/Keychain+Entries.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/StoreWidgets/StoreInfoDataService.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
Labels: type: bug, feature: stats, feature: REST API

#9050 Replace "No ratings" with "No (approved) reviews" in Product Detail
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
Labels: type: enhancement, feature: product details, category: parity

#9046 HACK Week: Handle account closing without WPKit
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/AccountRemote.swift
  Networking/Networking/Remote/Remote.swift
  Networking/NetworkingTests/Remote/AccountRemoteTests.swift
  Networking/NetworkingTests/Responses/close-account.json
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Stores/AccountStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockAccountRemote.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDotcomAccountRemote.swift
  Yosemite/YosemiteTests/Stores/AccountStoreTests.swift
Labels: type: technical debt

#9072 Pods update: Kingfisher to version 7.6.2 and Wormholy to 1.6.6
  Podfile
  Podfile.lock
Labels: category: tooling

#9078 Merge 12.6.0.1 into trunk
  WooCommerce/Classes/Authentication/Keychain+Entries.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/StoreWidgets/StoreInfoDataService.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#9042 [Simple Payment] Dismiss Take Payment popup after sharing the payment link to another app
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsHostingController.swift
Labels: feature: simple payments

#9059 HACK week: Replace WPKit Announcement with another model in the app to remove the dependency
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/AnnouncementListMapper.swift
  Networking/Networking/Model/Announcement.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Remote/AnnouncementsRemote.swift
  Networking/NetworkingTests/Mapper/AnnouncementListMapperTests.swift
  Networking/NetworkingTests/Remote/AnnouncementsRemoteTests.swift
  Networking/NetworkingTests/Responses/announcements.json
  Podfile
  Podfile.lock
  WooCommerce/WooCommerceTests/ViewRelated/WhatsNew/WhatsNewFactoryTests.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/AnnouncementsStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockAnnouncementsRemote.swift
  Yosemite/YosemiteTests/Stores/AnnouncementsStoreTests.swift
Labels: type: technical debt

#9087 Update all instances of bash-cache to ci-toolkit
  .buildkite/cache-builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: category: tooling

#9088 Remove magic link emphasis during the WPCom login flow
  Experiments/Experiments/DefaultFeatureFlagService.swift
Labels: type: enhancement, feature: login

#9083 [Stats] Prevent crash when parsing a date as Daylight Saving Time begins
  RELEASE-NOTES.txt
  Yosemite/Yosemite/Model/Extensions/OrderStatsV4Interval+Date.swift
  Yosemite/YosemiteTests/Model/Extensions/OrderStatsV4Interval+DateTests.swift
Labels: type: crash, feature: stats

#9086 [Orders] Track analytics event when orders list fails to load
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
Labels: feature: order list, category: analytics

#9082 [HACK Week] Spotlight activities
  RELEASE-NOTES.txt
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Extensions/String+Helpers.swift
  WooCommerce/Classes/Spotlight/SearchableActivityConvertable.swift
  WooCommerce/Classes/Spotlight/SpotlightManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController+Activity.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController+Activity.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController+Activity.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController+Activity.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#9091 Fix: password encoding in application passwords login
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/CookieNonce/CookieNonceAuthenticator.swift
  Networking/NetworkingTests/ApplicationPassword/CookieNonceAuthenticatorTests.swift
  RELEASE-NOTES.txt
Labels: type: bug, feature: login, feature: REST API

#9092 [HACK Week] Spotlight activities tracking
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+Spotlight.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Spotlight/SpotlightManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#9062 HACK week: Remove WPKit from Networking and UI layers
  Networking/Networking/ApplicationPassword/ApplicationPasswordUseCase.swift
  Networking/Networking/Remote/JetpackConnectionRemote.swift
  Podfile
  Podfile.lock
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/Bulk Edit Price/BulkUpdatePriceViewController.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockAuthentication.swift
Labels: type: technical debt

#9104 Merge 12.6 final into trunk
  Podfile
  Podfile.lock
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
Labels: Releases

#9089 HACK week: Add coupon to Order [1/2]
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Networking/Networking/Model/OrderCouponLine.swift
  Networking/Networking/Remote/OrdersRemote.swift
  Networking/NetworkingTests/Remote/OrdersRemoteTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  Yosemite/Yosemite/Stores/Order/OrderFactory.swift
  Yosemite/Yosemite/Stores/OrderStore.swift
  Yosemite/YosemiteTests/Stores/OrderStoreTests.swift
Labels: type: task, feature: order creation

#9094 Products: using `context=edit` parameter to load products for editing to enable updates with shortcodes in description
  Networking/Networking/Remote/ProductsRemote.swift
Labels: type: bug

#9099 Separate `NavigationView` from `ProductSelectorView` to `ProductSelectorNavigationView`
  WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift
  WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/UsageDetails/CouponRestrictions.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorNavigationView.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#9031 Refactor `DashboardViewController` to have one top-level scroll view instead of multiple scroll views for stats
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardUI.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.xib
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v3/DeprecatedStatsDashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#9029 REST API: 2FA UI and WPCom login integration
  WooCommerce/Classes/Authentication/Jetpack Setup/Site Credential Login/SiteCredentialLoginView.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/Classes/ViewRelated/Authentication/AuthenticationFormFieldView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPCom2FALoginView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPCom2FALoginViewModel.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComPasswordLoginView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComPasswordLoginViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/WPComLogin/WPCom2FALoginViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/WPComLogin/WPComPasswordLoginViewModelTests.swift
Labels: status: feature-flagged, feature: REST API

#9090 HACK week: Add coupon to Order [2/2]
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/OrderCouponLine.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/CouponLineDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/CouponLineDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/CouponInputTransformer.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/OrderSynchronizer.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizer.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/CouponLineDetailsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/CouponInputTransformerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizerTests.swift
Labels: type: task, feature: order creation

#9040 REST API: Updated UI and logic for the email login screen
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockWordPressComAccountService.swift
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginViewModelTests.swift
Labels: status: feature-flagged, feature: REST API

#9033 [Store onboarding] Show onboarding tasks using `onboarding/tasks` endpoint.
  Networking/Networking/Model/StoreOnboardingTask.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreSetupProgressView.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewHostingControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
Labels: type: task

#9112 REST API: Update an icon on Jetpack benefit modal
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackConnectionPackageSites/JetpackBenefitItem.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackConnectionPackageSites/JetpackBenefitsView.swift
  WooCommerce/Resources/Images.xcassets/multiple-stores.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/multiple-stores.imageset/multiple-stores.pdf
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: status: feature-flagged, feature: REST API

#9053 Added line break between "Address 1" and "Address 2" in Order Detail
  WooCommerce/Classes/Model/Address+Woo.swift
Labels: type: enhancement, feature: order details, category: parity

#9106 Merge 12.7 code freeze into trunk
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#9073 [Support Request] Remove `systemStatusReportInSupportRequest` feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
Labels: feature: support

#9116 [Product Bundles] Add support for product bundles in Storage layer
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Product+CoreDataProperties.swift
  Storage/Storage/Model/ProductBundleItem+CoreDataClass.swift
  Storage/Storage/Model/ProductBundleItem+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 81.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
Labels: category: woo extensions

#9093 [Support Request] Decouple ZendeskManager from support request metada
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormMetadataProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormsDataSources.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/Support/SupportDataSourcesTests.swift
Labels: feature: support

#9117 [Free Trial] Adds feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: feature: free trial

#9096 [Support Request] Remove `SupportRequest` Feature Flag and unused code.
  Experiments/Experiments/DefaultFeatureFlagService.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerError.swift
  WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Notifications/PushNotificationsConfiguration.swift
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/Notifications/SupportManagerAdapter.swift
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JCPJetpackInstall/JCPJetpackInstallView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CloseAccountCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveyCoordinatingController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockSupportManager.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
  WooCommerce/WooCommerceTests/Testing/MockZendeskManager.swift
  WooCommerce/WooCommerceTests/Tools/ZendeskManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyCoordinatorControllerTests.swift
Labels: feature: support

#9119 [Product Bundles] Remove unused product bundle properties
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductBundle/ProductBundleFormLocation.swift
  Networking/Networking/Model/Product/ProductBundle/ProductBundleItem.swift
  Networking/Networking/Model/Product/ProductBundle/ProductBundleItemGrouping.swift
  Networking/Networking/Model/Product/ProductBundle/ProductBundleLayout.swift
  Networking/Networking/Model/Product/ProductBundle/ProductBundleSoldIndividuallyContext.swift
  Networking/Networking/Model/Product/ProductBundleItem.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  WooCommerce/Classes/Extensions/Product+SwiftUIPreviewHelpers.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/ProductFactory.swift
  WooCommerce/WooCommerceTests/Mocks/MockReviews.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
  Yosemite/Yosemite/Model/Mocks/MockObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: category: woo extensions

#9077 [Product Multi-Selection] Update plural for OrderForm’s `Add Product` string
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
Labels: type: task, feature: order creation

#9097 [Product Multi-Selection] Add debug experimental toggle
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Storage/Storage/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/GeneralAppSettings.swift
  Storage/StorageTests/Model/AppSettings/GeneralAppSettingsTests.swift
  WooCommerce/Classes/Model/BetaFeature.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
  WooCommerce/WooCommerceTests/Model/BetaFeaturesTests.swift
  Yosemite/Yosemite/Actions/AppSettingsAction.swift
  Yosemite/Yosemite/Stores/AppSettingsStore.swift
  Yosemite/YosemiteTests/Stores/AppSettings/InAppFeedbackCardVisibilityUseCaseTests.swift
  Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Labels: type: task, feature: order creation

#9079 [Product Multi-Selection] Decouple clear selection from toggle variations
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift
Labels: type: task, feature: order creation

#9109 [Store onboarding] Handle `woocommerce-payments` task
  Networking/Networking/Model/StoreOnboardingTask.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
Labels: type: task

#9115 [Store onboarding] Use Menu instead of action sheet to match UI design.
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreSetupProgressView.swift
Labels: type: task

#9114 [Store onboarding] Pull to refresh store onboarding list
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
Labels: type: task

#9110 Store onboarding > add product action handling
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewHostingControllerTests.swift
Labels: type: task, status: feature-flagged

#9121 Dashboard: always show onboarding card, invalidate child SwiftUI hosting controller view's intrinsic content size to fit content height
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SelfSizingHostingController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: bug, type: task

#9047 Fix issues preventing app building under Catalyst
  Hardware/Hardware.xcodeproj/project.pbxproj
  Hardware/Hardware/CardReader/CardReaderDiscoveryMethod.swift
  Hardware/Hardware/CardReader/StripeCardReader/CardReaderDiscoveryMethod+Stripe.swift
Labels: type: task, feature: support, feature: mobile payments

#9103 [HACK Week] App Intents
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+AppIntents.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/App Intents/CollectPaymentAppIntent.swift
  WooCommerce/Classes/App Intents/CreateOrderAppIntent.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#9118 [Mobile Payments] Update StripeTerminal to 2.18
  Hardware/Hardware/CardReader/Charge.swift
  Hardware/Hardware/CardReader/PaymentIntentParameters.swift
  Hardware/Hardware/CardReader/StripeCardReader/Charge+Stripe.swift
  Hardware/Hardware/CardReader/StripeCardReader/PaymentIntent+Stripe.swift
  Hardware/Hardware/Model/Copiable/Models+Copiable.generated.swift
  Hardware/HardwareTests/ChargeTests.swift
  Hardware/HardwareTests/Mocks/MockStripeCharge.swift
  Hardware/HardwareTests/Mocks/MockStripePaymentIntent.swift
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: type: task, feature: mobile payments

#9123 Store onboarding > launch store: present a modal with a no-op CTA to publish store
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, status: feature-flagged

#9140 Store onboarding > launch store: Networking & Yosemite layer changes
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Remote/SiteRemoteTests.swift
  Networking/NetworkingTests/Responses/site-launch-error-already-launched.json
  Networking/NetworkingTests/Responses/site-launch-error-unauthorized.json
  Networking/NetworkingTests/Responses/site-launch-success.json
  Yosemite/Yosemite/Actions/SiteAction.swift
  Yosemite/Yosemite/Stores/SiteStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockSiteRemote.swift
  Yosemite/YosemiteTests/Stores/SiteStoreTests.swift
Labels: type: task

#9124 [Product Bundles] Support product bundles in Yosemite layer
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/product-update.json
  Networking/NetworkingTests/Responses/products-batch-update.json
  Networking/NetworkingTests/Responses/products-load-all.json
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductBundleItem+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: category: woo extensions

#9131 [Product Bundles] Show actual bundled product count in product details
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductVariationModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormDataModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
Labels: category: woo extensions, status: feature-flagged

#9129 [Store onboarding] Hide task list if all tasks are completed
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/System/SessionManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewHostingControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
  WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift
Labels: type: task

#9132 [Product Bundle] Show actual bundled products in product details
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/ProductBundleItemStockStatus+UI.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
Labels: category: woo extensions, status: feature-flagged

#9125 REST API: Update SiteCredentialLoginUseCase to handle direct login
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/SiteCredentialLoginUseCase.swift
  WooCommerce/Classes/Extensions/String+HTML.swift
  WooCommerce/WooCommerceTests/Authentication/SiteCredentialLoginUseCaseTests.swift
Labels: feature: login

#9150 REST API: Add support tag for application password login error
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
Labels: feature: login, feature: support

#9139 [Free trial] Fetch site plan details.
  Networking/Networking/Remote/PaymentRemote.swift
  Networking/NetworkingTests/Remote/PaymentRemoteTests.swift
  WooCommerce/Classes/Model/WPComSitePlan+FreeTrial.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: free trial

#9151 [Store onboarding] Add "PRIVATE" label to launch store task.
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskView.swift
Labels: type: task

#9153 [Store onboarding] "View all" button visibility and task tap action
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
Labels: type: task

#9169 Fix crash when a `UIStackView`'s subview is removed while a constraint is activated from `layoutIfNeeded`
  WooCommerce/Classes/ViewRelated/FilterTabBar/TabbedViewController.swift
Labels: type: crash

#9145 Store onboarding > launch store: UI integration
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreViewModelTests.swift
Labels: type: task

#9148 Store onboarding > launch store: show launched store UI
  WooCommerce/Classes/Authentication/Store Creation/Installations/StoreCreationSuccessView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingStoreLaunchedView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/SitePreviewView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#9166 REST API: Add support tag for site credential login failure
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormMetadataProvider.swift
Labels: feature: support

#9135 [Mobile Payments] Show cancel on TTP Setup for all screen sizes
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
Labels: type: task, feature: mobile payments, status: feature-flagged

#9152 [Mobile Payments] Block setup button when in progress
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift
Labels: type: enhancement, feature: mobile payments, status: feature-flagged

#9156 [App Intents] Add a constant to reuse the same value for the navigation delay.
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
Labels: type: task, feature: mobile payments

#9158 [Product Bundles] Display product images in bundled products list
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Bundled Products/BundledProductsListViewModelTests.swift
Labels: category: woo extensions, status: feature-flagged

#9162 [Product Bundles] Track when the Bundled Products row is tapped
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: category: woo extensions, category: analytics, status: feature-flagged

#9165 [Free Trial] Add Free Trial Banner UI
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialBanner.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooFoundation/WooFoundation/Colors/UIColor+SemanticColors.swift
Labels: feature: free trial

#9167 [Free Trial] Populate Free Trial Banner
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialBannerViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Free Trial/FreeTrialBannerViewModelTests.swift
Labels: feature: free trial

#9138 [Product Bundles] Show product bundle stock status or quantity in product list
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductVariationModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormDataModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/View Models/ProductFormDataModel+ProductsTabProductViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/View Models/ProductsTabProductViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductRowViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Bundled Products/BundledProductsListViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductsTabProductViewModelTests.swift
Labels: category: woo extensions, status: feature-flagged

#9174 [Store onboarding] Show all tasks if view all button is not displayed in collapsed mode.
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
Labels: type: task

#9144 [Product Multi-selection] Redirect to variations view on checkbox toggle tap
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift
Labels: type: task, feature: order creation

#9002 [In-Person Payments] Cache onboarding state
  Storage/Storage/Model/Copiable/Models+Copiable.generated.swift
  Storage/Storage/Model/GeneralAppSettings.swift
  Storage/StorageTests/Model/AppSettings/GeneralAppSettingsTests.swift
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift
  WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
  WooCommerce/Classes/ViewModels/Order Details/CardPresentPaymentsReadinessUseCase.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/BuiltInCardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentOnboardingStateCache.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingIPPUsersRefresher.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CardPresentPaymentsOnboardingPresenter.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyCollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingIPPUsersRefresherTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/MockCardPresentPaymentsOnboardingUseCase.swift
  Yosemite/Yosemite/Actions/AppSettingsAction.swift
  Yosemite/Yosemite/Stores/AppSettingsStore.swift
  Yosemite/YosemiteTests/Stores/AppSettings/InAppFeedbackCardVisibilityUseCaseTests.swift
  Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Labels: type: task, feature: mobile payments

#9173 [Product Multi-Selection] Add `RemoteOrderSynchronizer` support for multiple products
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/OrderSynchronizer.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/ProductInputTransformer.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizer.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/ProductInputTransformerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizerTests.swift
Labels: type: task, feature: order creation

#9200 [Product Bundles] Sync bundled products if needed, to get missing product images
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Bundled Products/BundledProductsListViewModelTests.swift
Labels: category: woo extensions, status: feature-flagged

#9197 Added release notes for 12.8
  CHANGELOG.md
Labels: Releases

#9168 [Free Trial] Launch upgrade Web View from banner CTA
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: feature: free trial

#9177 [Product Bundles] Release read-only support for product bundles
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewModel.swift
Labels: category: woo extensions, feature: hosted woo support

#9204 Merge 12.7 final into trunk
  WooCommerce/Classes/ViewRelated/FilterTabBar/TabbedViewController.swift
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
Labels: Releases

#9212 Merge 12.8 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#9188 Store onboarding > get paid
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingPaymentsSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingPaymentsSetupView.swift
  WooCommerce/Resources/Images.xcassets/icon-currency.imageset/icon-currency.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#9187 REST API: Web view for application password authorization
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/WordPressSite.swift
  Networking/NetworkingTests/Responses/wordpress-site-info-with-auth-url.json
  Networking/NetworkingTests/Responses/wordpress-site-info.json
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/Application Password/ApplicationPasswordAuthorizationViewModel.swift
  WooCommerce/Classes/Authentication/Application Password/ApplicationPasswordAuthorizationWebViewController.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Extensions/WordPressAuthenticator+Woo.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+UnifiedLogin.swift
  WooCommerce/Classes/Yosemite/DeauthenticatedState.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/PostSiteCredentialLoginCheckerTests.swift
  Yosemite/Yosemite/Actions/WordPressSiteAction.swift
  Yosemite/Yosemite/Stores/WordPressSiteStore.swift
  Yosemite/YosemiteTests/Stores/WordPressSiteStore.swift
Labels: type: task, feature: login, status: feature-flagged

#9154 [Mobile Payments] Disconnect other readers when setting up TTP
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionAnalyticsTracker.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsSearchingViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayViewModelsOrderedList.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CardPresentPaymentAlertsPresenter.swift
Labels: type: enhancement, feature: mobile payments, category: analytics, status: feature-flagged

#9198 [Mobile Payments] Tap to Pay on iPhone – Setup complete screen
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayCompleteViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayCompleteViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayViewModelsOrderedList.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: mobile payments, status: feature-flagged

#9203 [Product Multi-Selection ] Add and remove products and variations
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizer.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizerTests.swift
Labels: type: task, feature: order creation

#9185 [Store onboarding] Remove task list when no tasks are available.
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewHostingControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
Labels: type: task

#9220 [Composite Products] Add support for composite products in Networking layer
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductCompositeComponent.swift
  Networking/Networking/Model/Product/ProductType.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/product-composite.json
  Networking/NetworkingTests/Responses/product.json
  WooCommerce/Classes/Extensions/Product+SwiftUIPreviewHelpers.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/ProductFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductTypeBottomSheetListSelectorCommand.swift
  WooCommerce/WooCommerceTests/Mocks/MockReviews.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
  Yosemite/Yosemite/Model/Mocks/MockObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: category: woo extensions

#9233 [Products] Decoding error handling for permalink
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductVariation.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductVariationMapperTests.swift
  Networking/NetworkingTests/Responses/product-alternative-types.json
  Networking/NetworkingTests/Responses/product-variation-alternative-types.json
  RELEASE-NOTES.txt
Labels: feature: variation list

#9230 [Free Trial] Fill subscription view with real site plan data
  Networking/Networking/Remote/PaymentRemote.swift
  Networking/NetworkingTests/Remote/PaymentRemoteTests.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/UpgradesViewModelTests.swift
Labels: feature: free trial

#9217 Store onboarding > get paid: support admin links in self-hosted sites
  WooCommerce/Classes/Authentication/AuthenticatedWebViewController.swift
  WooCommerce/Classes/Authentication/AuthenticatedWebViewModel.swift
  WooCommerce/Classes/Authentication/WPAdminWebViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingPaymentsSetupCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/WPAdminWebViewModelTests.swift
Labels: type: task

#9225 [Mobile Payments] Fix connection loop for external readers after Set up Tap to Pay
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift
Labels: type: bug, feature: mobile payments

#9218 REST API: New credential type for application password
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/ApplicationPassword/ApplicationPasswordUseCase.swift
  Networking/Networking/ApplicationPassword/OneTimeApplicationPasswordUseCase.swift
  Networking/Networking/ApplicationPassword/RequestAuthenticator.swift
  Networking/Networking/ApplicationPassword/RequestConverter.swift
  Networking/Networking/Model/ApplicationPassword/ApplicationPassword.swift
  Networking/Networking/Settings/Credentials.swift
  Networking/NetworkingTests/Network/DefaultRequestAuthenticatorTests.swift
  Networking/NetworkingTests/Network/RequestConverterTests.swift
  WooCommerce/Classes/AppDelegate.swift
  WooCommerce/Classes/Authentication/Application Password/ApplicationPasswordAuthorizationWebViewController.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/PostSiteCredentialLoginChecker.swift
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/StoreWidgets/StoreInfoDataService.swift
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/StoreWidgetsExtension.xcscheme
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Internal/SessionManager+Internal.swift
  WooCommerce/WooCommerceTests/System/SessionManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift
  WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift
  Yosemite/Yosemite/Base/StoresManager.swift
  Yosemite/Yosemite/Model/Mocks/Graphs/ScreenshotsObjectGraph.swift
  Yosemite/Yosemite/Model/Mocks/MockStoresManager.swift
Labels: status: feature-flagged, feature: REST API

#9215 [Store onboarding] Hide other upsells from dashboard
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: type: task

#9221 [Composite Products] Add support for composite products in Storage layer
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Product+CoreDataProperties.swift
  Storage/Storage/Model/ProductCompositeComponent+CoreDataClass.swift
  Storage/Storage/Model/ProductCompositeComponent+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 82.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
Labels: category: woo extensions

#9222 [Composite Products] Add support for composite products in Yosemite layer
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Model/Storage/ProductCompositeComponent+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: category: woo extensions

#9249 [Store onboarding] Reload task list on task completed
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinatorTests.swift
Labels: type: task

#9253 Merge 12.8.0.2 into trunk
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Create Shipping Label/ShippingLabelAddressFormViewModelTests.swift
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#9223 [Mobile Payments] Tap to Pay Try a Payment flow
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowPresentingViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayCompleteViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayCompleteViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayTryPaymentPromptViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayTryPaymentPromptViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayViewModelsOrderedList.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: mobile payments

#9179 [Speedy IPP] Product Local Search
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: type: task, feature: mobile payments

#9247 [Free Trial] Upgrade Plan from Upgrades screen
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradePlanCoordinatingController.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: free trial

#9250 [Free Trial] Upgrades View - Error Handling
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/UpgradesViewModelTests.swift
Labels: feature: free trial

#9263 [Free Trial] Launch support from upgrades view
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
Labels: feature: free trial

#9265 [Free Trial] Release 1st Iteration
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
Labels: feature: free trial

#9255 Remove `XLPagerTabStrip` dependency from the app
  Podfile
  Podfile.lock
  WooCommerce/Classes/Extensions/XLPagerStrip+AccessibilityIdentifier.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/XLPagerStrip+AccessibilityIdentifierTests.swift
Labels: type: technical debt

#9254 Store onboarding: design polishes
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreSetupProgressView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainPurchaseSuccessView.swift
Labels: type: enhancement

#9231 [UI Tests] - Add load card reader manual test
  WooCommerce/UITestsFoundation/Screens/Menu/MenuScreen.swift
  WooCommerce/UITestsFoundation/Screens/Payments/CardReaderManualsScreen.swift
  WooCommerce/UITestsFoundation/Screens/Payments/PaymentsScreen.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceUITests/README.md
  WooCommerce/WooCommerceUITests/Tests/PaymentsTests.swift
Labels: type: task, category: ui tests

#9260 REST API: Analytics and feature flag enabling for application password authorization in web view
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Networking/Networking/Model/WordPressSite.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Application Password/ApplicationPasswordAuthorizationWebViewController.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: type: task, feature: login, category: analytics

#9264 [Composite Products] Add support for component description and default option ID
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Product/ProductCompositeComponent.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Storage/Storage/Model/ProductCompositeComponent+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 82.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
  Yosemite/Yosemite/Model/Storage/ProductCompositeComponent+ReadOnlyConvertible.swift
Labels: category: woo extensions

#9262 [Product Bundles] Accessibility improvements in bundled products list
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Bundled Products/Bundled Product List/BundledProductsListViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/FooterNotice.swift
Labels: category: woo extensions

#9242 [Mobile Payments] Move Tap to Pay to payment method screen
  Hardware/Hardware.xcodeproj/project.pbxproj
  Hardware/Hardware/CardReader/StripeCardReader/CardReader+CardReaderDiscoveryType.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewModels/Order Details/CardPresentPaymentsReadinessUseCase.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/BuiltInCardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CardPresentPaymentsOnboardingPresenter.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsView.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/YosemiteTests/Stores/OrderCardPresentPaymentEligibilityStoreTests.swift
Labels: type: enhancement, feature: mobile payments

#9268 Store onboarding: analytics
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreOnboarding.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductCoordinatorTests.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
Labels: type: task, category: analytics

#9266 [Store onboarding] Store details task
  Networking/Networking/Model/StoreOnboardingTask.swift
  Networking/NetworkingTests/Mapper/StoreOnboardingTaskListMapperTests.swift
  Networking/NetworkingTests/Remote/StoreOnboardingTasksRemoteTests.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreOnboarding.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreDetails/StoreOnboardingStoreDetailsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  WooCommerce/Resources/Images.xcassets/icon-store-details.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/icon-store-details.imageset/icon-store-details.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskViewModel.swift
  Yosemite/YosemiteTests/Stores/StoreOnboardingTasksStoreTests.swift
Labels: type: task

#9259 [Composite Products] Add and navigate to Components list
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Composite Product Components/ComponentsList.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Composite Product Components/ComponentsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Composite Products/ComponentsListViewModelTests.swift
Labels: category: woo extensions

#9275 [Store onboarding] Start in redacted state
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
Labels: type: bug

#9285 Store onboarding: feature release
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: type: task

#9283 [Store onboarding] Retry launch store from error alert
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreView.swift
Labels: type: task

#9287 Added release notes for 12.9
  CHANGELOG.md
Labels: Releases

#9279 [Mobile Payments] Set visibility and enabled state for Set up Tap to Pay on iPhone
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModelTests.swift
Labels: type: task, feature: mobile payments

#9280 [Mobile Payments] Reveal Set up Tap to Pay on iPhone flow from behind feature flag
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
Labels: type: task, feature: mobile payments

#9286 Store onboarding: hide `view all` CTA when there are 3 tasks that are incomplete
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
Labels: type: enhancement

#9277 [Mobile Payments] Set up Tap to Pay analytics
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayCompleteViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayTryPaymentPromptViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayTryPaymentPromptViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Simple Payments/Summary/SimplePaymentsSummaryViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModelTests.swift
Labels: type: task, feature: mobile payments, category: analytics

#9291 Merge 12.8 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
Labels: Releases
