Repository woocommerce/woocommerce-ios, pull requests merged in 2023-07, with the labels that each got.

#10146 Merge 14.2 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10147 Merge 14.3 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#10125 [IAP] Extract Upgrades model and view into different components
  WooCommerce/Classes/ViewModels/InAppPurchases/InAppPurchasesError.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradeViewState.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/WooWPComPlan.swift
  WooCommerce/Classes/ViewRelated/Upgrades/CompletedUpgradeView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/CurrentPlanDetailsView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/PrePurchaseUpgradesErrorView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/PurchaseUpgradeErrorView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradeTopBarView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradeWaitingView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, type: task, feature: in-app purchases

#10155 Fix typo on Coupon validation error notice
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/CouponLineDetailsViewModel.swift
Labels: type: bug, feature: coupons

#10141 [Performance] Remove unused Leaderboards support
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/LeaderboardListMapper.swift
  Networking/Networking/Model/Stats/Leaderboard.swift
  Networking/Networking/Model/Stats/LeaderboardRow.swift
  Networking/Networking/Model/Stats/LeaderboardRowContent.swift
  Networking/Networking/Remote/LeaderboardsRemote.swift
  Networking/NetworkingTests/Mapper/LeaderboardListMapperTests.swift
  Networking/NetworkingTests/Remote/LeaderboardsRemoteTests.swift
  Networking/NetworkingTests/Responses/leaderboards-products.json
  Networking/NetworkingTests/Responses/leaderboards-year-alt.json
  Networking/NetworkingTests/Responses/leaderboards-year-without-data.json
  Networking/NetworkingTests/Responses/leaderboards-year.json
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc-analytics/reports_leaderboards_stats_day.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc-analytics/reports_leaderboards_stats_month.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc-analytics/reports_leaderboards_stats_week.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc-analytics/reports_leaderboards_stats_year.json
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/Enums/StatsTimeRangeV4.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Tools/Stats/LeaderboardStatsConverter.swift
  Yosemite/YosemiteTests/Tools/Stats/LeaderboardStatsConverterTests.swift
Labels: feature: stats, category: performance

#10161 [Shipping Labels] Fix print shipping labels from order search
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Print Shipping Label/PrintShippingLabelCoordinator.swift
  WooCommerce/WooCommerceTests/ViewRelated/Shipping Label/Reprint Shipping Label/PrintShippingLabelCoordinatorTests.swift
Labels: type: bug, feature: shipping labels

#10140 [IAP] Changes CTA dynamically based on IAP support
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialBannerPresenter.swift
Labels: type: task, feature: in-app purchases

#10135 Blaze: Add highlight banner on the product list
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+Blaze.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Blaze/BlazeBanner.swift
  WooCommerce/Classes/Blaze/BlazeWebViewModel.swift
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Resources/Images.xcassets/blaze.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/blaze.imageset/blaze.pdf
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
Labels: type: task, feature: product list

#10160 Blaze: Add banner on My Store tab
  WooCommerce/Classes/Blaze/BlazeBanner.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: type: task

#10166 Blaze: Update entry point analytic name to align with Android
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+Blaze.swift
  WooCommerce/Classes/Blaze/BlazeBanner.swift
  WooCommerce/Classes/Blaze/BlazeWebViewModel.swift
Labels: category: analytics

#10171 Blaze: Update logic checks for banner visibility
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/UserDefaultWooTests.swift
Labels: type: bug, category: unit tests

#10163 [IAP] Simplify check for existing Subscriptions, and improve unit test coverage
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/UpgradesViewModelTests.swift
Labels: type: task, feature: in-app purchases

#10175 [IAP] Fix: Apply lower-case to product_id prop
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
Labels: type: task, feature: in-app purchases

#10145 [Tracking]Improve SKU search tracking
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModelTracker.swift
  WooCommerce/Classes/ViewRelated/Products/SKU Scanner/BarcodeSKUScannerItemFinder.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/SKU Scanner/BarcodeSKUScannerProductFinderTests.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
Labels: type: task, category: analytics

#10173 Blaze: Disable Blaze in product creation form
  RELEASE-NOTES.txt
  WooCommerce/Classes/Blaze/BlazeBanner.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: type: bug

#10169 Identify language using a separate AI prompt
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/GenerativeContentRemote.swift
  Networking/NetworkingTests/Remote/GenerativeContentRemoteTests.swift
  Networking/NetworkingTests/Responses/identify-language-failure.json
  Networking/NetworkingTests/Responses/identify-language-success.json
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/AI/ProductDescriptionGenerationView.swift
  WooCommerce/Classes/ViewRelated/Products/AI/ProductDescriptionGenerationViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductDescriptionGenerationViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockGenerativeContentRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: type: bug, type: task

#10172 Blaze: Only show entry point if store has at least 1 published product
  Networking/Networking/Remote/ProductsRemote.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: type: bug

#10177 [AI generation] Reset identified language if user downvotes
  WooCommerce/Classes/ViewRelated/Products/AI/ProductDescriptionGenerationViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductDescriptionGenerationViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModelTests.swift
Labels: type: task

#10167 [IAP] Draft of new upgrades screen
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradeViewState.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/WooWPComPlan.swift
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/UpgradesViewModelTests.swift
  Yosemite/Yosemite/Model/WooPlans/WooPlan.swift
Labels: type: task, feature: in-app purchases

#10179 [AI generation] Identify ISO language code and track it
  Networking/Networking/Remote/GenerativeContentRemote.swift
  Networking/NetworkingTests/Remote/GenerativeContentRemoteTests.swift
  Networking/NetworkingTests/Responses/identify-language-success.json
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ProductFormAI.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ProductSharingAI.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/AI/ProductDescriptionGenerationViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductDescriptionGenerationViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModelTests.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: type: bug

#10181 Add unit tests for `LocalAnnouncementViewModel` actions
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/LocalAnnouncements/LocalAnnouncementViewModelTests.swift
Labels: type: technical debt

#10184 Add product from image: barebone flow
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageEligibilityChecker.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockAddProductFromImageEligibilityChecker.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageEligibilityCheckerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
Labels: type: task

#10183 Add product from image: Yosemite action to generate product details from scanned texts
  Networking/Networking/Remote/GenerativeContentRemote.swift
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: type: task

#10193 Merge 14.3 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10191 Added release notes for 14.4
  CHANGELOG.md
Labels: Releases

#10195 Merge 14.4 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#10185 [IAP] Update event when tracking plan details
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Upgrades/WooPlanFeatureBenefitsView.swift
Labels: type: task, feature: in-app purchases

#10197 [IAP] Update plan selection UI to M2
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  Yosemite/Yosemite/Model/WooPlans/WooPlan.swift
Labels: type: task, feature: in-app purchases

#10196 Add product from image: media picker in SwiftUI
  WooCommerce/Classes/Extensions/UIViewController+Navigation.swift
  WooCommerce/Classes/View Modifiers/View+MediaSourceActionSheet.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageFormImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Media/CameraCaptureCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Media/DefaultProductUIImageLoader.swift
  WooCommerce/Classes/ViewRelated/Products/Media/MediaPickingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductUIImageLoader.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/EditableImageView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
Labels: type: task, status: feature-flagged

#10207 [Orders with Coupons M4]Add feature flag for the Orders w/ Coupons Milestone 4
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: task, feature: coupons, feature: order creation

#10209 [Orders with Coupons M4] Add discount to product - UI
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/FeeOrDiscountLineDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/FeeOrDiscountLineDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrder.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrderViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/FeeOrDiscountLineDetailsViewModelTests.swift
Labels: type: task, feature: coupons, feature: order creation

#10211 [Orders with Coupons M4] Add discount to product business logic
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/FeeOrDiscountLineDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/FeeOrDiscountLineDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrder.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/OrderSynchronizer.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/ProductInputTransformer.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/FeeOrDiscountLineDetailsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/ProductInputTransformerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizerTests.swift
Labels: type: task, feature: order creation

#10212 Add product from image: scan text from the image and generate product details
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageFormImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
Labels: type: task

#10208 Add product from image: update entry point
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ProductCreation.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageEligibilityChecker.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductCoordinatorTests.swift
Labels: type: task

#10216 Product form: Update share button to use text instead of icon
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: type: enhancement, feature: product details

#10219 [IAP] M2 expandable card feature details
  WooCommerce/Classes/ViewModels/InAppPurchases/LegacyUpgradesViewModel.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/WooWPComPlan.swift
  WooCommerce/Classes/ViewRelated/Upgrades/LegacyUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/WooPlanCardView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/WooPlanFeatureBenefitsView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Model/WooPlans/LegacyWooPlan.swift
  Yosemite/Yosemite/Model/WooPlans/WooPlan.swift
Labels: type: task, feature: in-app purchases

#10220 Add product from image: show a list of selectable & editable scanned texts
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageScannedTextView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#10221 Store creation: Update timeout view to align with Android
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreCreation.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationTimeoutView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement

#10222 Fix for 'Unable to Add a New Note' Issue in Order
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/ReusableViews/TextViewTableViewCell.swift
Labels: type: bug

#10228 Requirements Checker: Remove check for isWordPressComStore before checking site plan
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/RequirementsChecker.swift
  WooCommerce/WooCommerceTests/Tools/RequirementsCheckerTests.swift
Labels: type: bug

#10227 Add product from image: extract image text-scanning logic for unit testing
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/ImageTextScanner.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockImageTextScanner.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/ImageTextScannerTests.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
Labels: type: technical debt

#10225 Add product from image: update text field to support AI-generated suggestion
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageTextFieldView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageTextFieldViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageTextFieldViewModelTests.swift
Labels: type: task

#10235 Merge 14.4 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10239 Merge 14.5 code freeze into trunk
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#10238 Add product from image: show error from generating product details
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
Labels: type: task

#10236 Add product from image: fix media picker interactive dismissal issue
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Downloadable Files/File List/ProductDownloadListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/DeviceMediaLibraryPicker.swift
  WooCommerce/Classes/ViewRelated/Products/Media/MediaPickingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryImagePickerCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/WordPressMediaLibraryImagePickerCoordinatorTests.swift
Labels: type: task

#10237 Add product from image: add a dismiss CTA to allow dismissal in landscape mode
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
Labels: type: task

#10223 [Orders with Coupons M4] Remove/edit discounts on products
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrder.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/OrderSynchronizer.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/OrderTotalsCalculator.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/ProductInputTransformer.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/OrderTotalsCalculatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/ProductInputTransformerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizerTests.swift
Labels: type: task, feature: order details, feature: order creation

#10224 [Order with Coupons M4] Product discounts tracking
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/FeeOrDiscountLineDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/FeeOrDiscountLineDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrder.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrderViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/FeeOrDiscountLineDetailsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrderViewModelTests.swift
Labels: category: analytics, feature: order creation

#10232 [Coupons in Orders M4] Improve product discounts coupons interaction
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrder.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrderViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrderViewModelTests.swift
Labels: type: task, feature: coupons, feature: order creation

#10234 [Order with Coupons M4] Show product discount on the Editable Order Details Product Row
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductRowViewModelTests.swift
Labels: feature: coupons, feature: order creation

#10243 [IAP] Add `InAppPurchasesTransactionMapper`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/InAppPurchasesTransactionMapper.swift
  Networking/Networking/Remote/InAppPurchasesRemote.swift
  Networking/NetworkingTests/Remote/InAppPurchasesRemoteTests.swift
  Networking/NetworkingTests/Responses/iap-transaction-handled.json
  Networking/NetworkingTests/Responses/iap-transaction-not-handled.json
Labels: type: task, feature: in-app purchases

#10244 [Orders with Coupons M4] Enable Feature Flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: feature: order creation

#10218 Update AI endpoint to enable measuring costs
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/GenerativeContentRemote.swift
  Networking/NetworkingTests/Remote/GenerativeContentRemoteTests.swift
  Networking/NetworkingTests/Responses/generative-text-invalid-token.json
  Networking/NetworkingTests/Responses/generative-text-success.json
  Networking/NetworkingTests/Responses/identify-language-invalid-token.json
  Networking/NetworkingTests/Responses/identify-language-success.json
  Networking/NetworkingTests/Responses/jwt-token-failure.json
  Networking/NetworkingTests/Responses/jwt-token-success.json
  RELEASE-NOTES.txt
Labels: type: task

#10241 Add product from image: Add analytics
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+AddProductFromImage.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ProductCreation.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEventPropertyType.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageFormImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageTextFieldViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Media/MediaPickingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageTextFieldViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Media/MediaPickingCoordinatorTests.swift
Labels: feature: add/edit products, category: analytics

#10245 [Orders with Coupons M4] Expand text background to screen edges
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/ProductsSection/ProductInOrder.swift
Labels: type: task, feature: coupons, feature: order creation

#10248 [Orders with Coupons M5]Decouple Coupons extra logic from the list so it can be easily reused.
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewController.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewModel.swift
  WooCommerce/Classes/ViewRelated/Coupons/EnhancedCouponListView.swift
  WooCommerce/Classes/ViewRelated/Coupons/EnhancedCouponListViewController.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: coupons

#10252 [Resilience] Improve error banner message when orders can't load due to parsing error
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Top Banner/ErrorTopBannerFactory.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/TopBanner/ErrorTopBannerFactoryTests.swift
Labels: feature: order list, category: reliability

#10253 [Add product from image] Check ABTest variation
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageEligibilityChecker.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageEligibilityCheckerTests.swift
Labels: type: task

#10255 [Orders with Coupons M5] Add coupon selector to the order creation
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Coupons/CouponListView.swift
  WooCommerce/Classes/ViewRelated/Coupons/CouponListViewController.swift
  WooCommerce/Classes/ViewRelated/Coupons/EnhancedCouponListViewController.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewController.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/CouponLineDetails.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/CouponLineDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/CouponLineDetailsViewModelTests.swift
Labels: feature: coupons, feature: order creation

#10261 [Orders with Coupons M5]Tap on Go to Coupons tracking
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/PaymentSection/OrderPaymentSection.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/EditableOrderViewModelTests.swift
Labels: category: analytics, feature: coupons, feature: order creation

#10260 [Resilience] Customize error banner message when data can't be loaded due to parsing errors
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewModel.swift
  WooCommerce/WooCommerceTests/Reviews/ReviewsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Reviews/ReviewsViewControllerTests.swift
Labels: feature: review list, feature: product list, category: reliability

#10262 [My store] Fix error banner so it appears when stats data can't be loaded
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/DashboardViewModelTests.swift
Labels: feature: stats, category: reliability

#10263 [Resilience] Customize dashboard error message for parsing errors
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardUI.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v3/DeprecatedStatsDashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc-analytics/reports_products.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_summary_day.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_summary_month.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_summary_week.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_summary_year.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_visits_day.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_visits_month.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_visits_week.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/stats/stats_visits_year.json
Labels: feature: stats, category: reliability

#10254 Fix Crash in `BottomSheetViewController`
  Podfile.lock
  RELEASE-NOTES.txt
Labels: type: crash

#10274 My store tab: remove duplicate analytics API requests on app launch
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
Labels: type: task

#10242 [UI Tests] - Add note to existing order test
  WooCommerce/UITestsFoundation/Screens/Orders/CustomerNoteScreen.swift
  WooCommerce/WooCommerceUITests/Tests/OrdersTests.swift
Labels: type: task, feature: order details, category: ui tests

#10271 Product details from image: Disable generate button if all texts are either empty or not selected
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageFormImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
Labels: type: enhancement

#10281 [UI Tests] - Update header text in documentation WebView
  WooCommerce/UITestsFoundation/Screens/Payments/PaymentsScreen.swift
Labels: type: task, category: ui tests

#10273 Order details: only make shipping label API requests if the order contains non-virtual products
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift
Labels: type: task

#10279 [AI endpoint] Add `_fields` parameter
  Networking/Networking/Remote/GenerativeContentRemote.swift
  Networking/NetworkingTests/Remote/GenerativeContentRemoteTests.swift
  Networking/NetworkingTests/Responses/generative-text-success.json
  Networking/NetworkingTests/Responses/identify-language-success.json
Labels: type: task

#10277 [Local notifications] Track IAP eligibility in tracks events
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+LocalNotification.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/Notifications/LocalNotificationScheduler.swift
  WooCommerce/Classes/Notifications/PushNotificationsManager.swift
  WooCommerce/Classes/Notifications/UserNotificationsCenterAdapter.swift
  WooCommerce/Classes/ServiceLocator/PushNotesManager.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockUserNotificationsCenterAdapter.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
Labels: type: task

#10282 [Photo to Product] Show message when no text detected
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageFormImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
Labels: type: task

#10275 [Resilience] Customize error banner message when Jetpack connection is broken
  Networking/Networking/Model/DotcomError.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Top Banner/ErrorTopBannerFactory.swift
  WooCommerce/WooCommerceTests/ViewRelated/TopBanner/ErrorTopBannerFactoryTests.swift
  Yosemite/Yosemite/Stores/StatsStoreV4.swift
Labels: category: jetpack, category: reliability

#10284 Added release notes for 14.6
  CHANGELOG.md
Labels: Releases

#10285 Merge 14.5 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10287 Merge 14.6 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#10290 Zendesk tag if user eligible to add product from image
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormMetadataProvider.swift
  WooCommerce/WooCommerceTests/Tools/Support/SupportDataSourcesTests.swift
Labels: type: task

#10288 Order details: only make shipment tracking API request if the order contains non-virtual products
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift
Labels: category: performance

#10268 Local notification: Notification to purchase plan 6 hour after trial subscription
  RELEASE-NOTES.txt
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
Labels: type: task, feature: notifications

#10296 [IAP] Use production plan ids
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
  WooCommerce/Resources/WooCommerceTestSynced.storekit
  Yosemite/Yosemite/Model/WooPlans/LegacyWooPlan.swift
Labels: type: task, feature: in-app purchases

#10297 [Photo to Product] Reset details from previous image when no text detected
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockImageTextScanner.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
Labels: type: task

#10247 [IAP] Check whether transactions in `Transaction.Updates` queue have been handled
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/InAppPurchasesTransactionMapper.swift
  Networking/Networking/Remote/InAppPurchasesRemote.swift
  Networking/NetworkingTests/Mapper/InAppPurchasesTransactionMapperTests.swift
  Networking/NetworkingTests/Remote/InAppPurchasesRemoteTests.swift
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
Labels: type: task, feature: in-app purchases

#10303 [IAP] Address dark mode in Full Feature View
  WooCommerce/Classes/ViewRelated/Upgrades/FullFeatureListView.swift
Labels: type: bug, feature: in-app purchases

#10276 [Mobile Payments] Use reference instead of name when retrieving IPP Plugins
  Networking/Networking/Model/SystemPlugin.swift
  WooCommerce/Classes/Tools/CardPresentPluginsDataProvider.swift
  WooCommerce/WooCommerceTests/Tools/CardPresentPluginsDataProviderTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift
  Yosemite/Yosemite/Model/Enums/CardPresentPaymentsPlugin.swift
Labels: type: task, feature: mobile payments

#10315 Add Privacy Policy and Terms of Service links to App Store description
  WooCommerce/Resources/AppStoreStrings.pot
  fastlane/appstoreres/metadata/source/description.txt
Labels: Releases

#10300 Track path and entity name in API JSON parsing error events `api_json_parsing_error`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Extensions/URLRequestConvertible+Path.swift
  Networking/Networking/Remote/Remote.swift
  Networking/NetworkingTests/Extensions/URLRequestConvertible+PathTests.swift
  Networking/NetworkingTests/Remote/RemoteTests.swift
  WooCommerce/Classes/Analytics/TrackEventRequestNotificationHandler.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/WooCommerceTests/Yosemite/TrackEventRequestNotificationHandlerTests.swift
Labels: type: task, category: analytics

#10305 Update `WCPayAccount.isLive`'s expected API value to be optional based on backend implementation
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Model/WCPayAccount.swift
  Networking/NetworkingTests/Remote/WCPayRemoteTests.swift
  Networking/NetworkingTests/Responses/wcpay-account-null-isLive.json
Labels: type: task

#10301 Networking: Update site model with new property `wasEcommerceTrial`
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/Site.swift
  Networking/Networking/Model/WordPressSite.swift
  Networking/Networking/Remote/SiteRemote.swift
  Networking/NetworkingTests/Mapper/AccountMapperTests.swift
  Networking/NetworkingTests/Responses/sites-malformed.json
  Networking/NetworkingTests/Responses/sites.json
  WooCommerce/WooCommerceUITests/Mocks/mappings/me/rest_v11_me_sites.json
  Yosemite/Yosemite/Model/Mocks/Graphs/ScreenshotsObjectGraph.swift
  Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
Labels: type: task

#10304 Storage: Add new attribute `wasEcommerceTrial` to Site entity.
  Storage/Storage.xcodeproj/project.pbxproj
  Storage/Storage/Model/MIGRATIONS.md
  Storage/Storage/Model/Site+CoreDataProperties.swift
  Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
  Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 92.xcdatamodel/contents
  Storage/StorageTests/CoreData/MigrationTests.swift
  Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
Labels: type: task

#10318 Order list: Add entry point to create test order
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Orders/CreateTestOrderView.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Resources/Images.xcassets/create-order.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/create-order.imageset/illustration-testStore-dark.svg
  WooCommerce/Resources/Images.xcassets/create-order.imageset/illustration-testStore-light.svg
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task, feature: order list

#10320 [IAP] Disable plan selection while purchasing
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
Labels: type: bug, feature: in-app purchases

#10322 [IAP] Apply loading state to view all features button
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
Labels: type: task, feature: in-app purchases

#10323 [IAP] Prevent view reload when purchase plan tapped
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradeViewState.swift
  WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift
  WooCommerce/Classes/ViewRelated/Upgrades/OwnerUpgradesView.swift
  WooCommerce/Classes/ViewRelated/Upgrades/UpgradesView.swift
Labels: type: enhancement, feature: in-app purchases

#10319 [Free trial survey] Survey screen
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+FreeTrialSurvey.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Store Creation/Free Trial/FreeTrialSurveyCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyViewModel.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/ButtonStyles.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: free trial

#10324 Local notification: Notification for Free trial survey
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
Labels: type: task

#10329 Create test order: update logic for entry point
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
Labels: type: task, feature: order list

#10330 Test order: Add analytics
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+TestOrder.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: order list, category: analytics

#10328 [Free trial survey] Show survey upon tapping local notification
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+FreeTrialSurvey.swift
  WooCommerce/Classes/Authentication/Store Creation/Free Trial/FreeTrialSurveyCoordinator.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyCoordinatorTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyViewModelTests.swift
Labels: type: task

#10321 Update “manage button” logic to cover all plans
  WooCommerce/Classes/Authentication/Store Creation/Plan/WebPurchasesForWPComPlans.swift
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesForWPComPlansManager.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/Classes/ViewRelated/Upgrades/SubscriptionsViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockInAppPurchasesForWPComPlansManager.swift
  Yosemite/Yosemite/Actions/InAppPurchaseAction.swift
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
Labels: type: task, feature: in-app purchases

#10326 Adds a feature flag for the Better Customer Selection logic in Orders.
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: task, feature: order creation

#10340 [IAP] Enable IAP for plans M2 feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: type: task, feature: in-app purchases

#10333 Product description AI: Make product name field more prominent
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/AI/ProductDescriptionGenerationView.swift
  WooCommerce/Classes/ViewRelated/Products/AI/ProductDescriptionGenerationViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductDescriptionGenerationViewModelTests.swift
Labels: type: enhancement, feature: add/edit products

#10331 [Free trial survey] Notify after 3 days if still exploring
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyViewModel.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Free Trial/FreeTrialSurvey/FreeTrialSurveyViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/AddProductFromImage/AddProductFromImageViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
Labels: type: task

#10325 [Order Creation - Better Customer Selection] Retrieve a paginated list of all customers
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/WCAnalyticsCustomer.swift
  Networking/Networking/Remote/WCAnalyticsCustomerRemote.swift
  Networking/NetworkingTests/Remote/WCAnalyticsCustomerRemoteTests.swift
  Storage/Storage/Tools/StorageType+Deletions.swift
  Storage/Storage/Tools/StorageType+Extensions.swift
  Yosemite/Yosemite/Actions/CustomerAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Model/Storage/Customer+ReadOnlyConvertible.swift
  Yosemite/Yosemite/Stores/CustomerStore.swift
  Yosemite/YosemiteTests/Stores/CustomerStoreTests.swift
Labels: type: task, feature: order creation

#10343 Analytics: Track was_ecommerce_trial as a default property
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalytics.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+TestOrder.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
Labels: type: enhancement, category: analytics

#10332 Data/track order event properties for extensions
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchUICommand.swift
Labels: category: analytics

#10344 [Free trial survey] Release free trial survey local notification
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: type: task

#10346 Create test order: Release feature
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
Labels: type: task, feature: order list

#10352 Merge 14.6 final into trunk
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormMetadataProvider.swift
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerceTests/Tools/Support/SupportDataSourcesTests.swift
  config/Version.Public.xcconfig
  fastlane/appstoreres/metadata/source/description.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#10258 [React Native] Integrate Shipping Zones
  RELEASE-NOTES.txt
  WooCommerce.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WooCommerce/Classes/Analytics/ReactNativeAnalyticsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement

#10354 Merge 14.7 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#10345 [Local notification] Removes deprecated 24h after Free trial subscribed local notification
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Notifications/LocalNotification.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Upgrades/StorePlanSynchronizer.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationSchedulerTests.swift
  WooCommerce/WooCommerceTests/Notifications/LocalNotificationTests.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Upgrades/StorePlanSynchronizerTests.swift
Labels: type: task

#10361 Test order: Fix incorrect page number for synching products on the order list screen
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
Labels: type: bug, feature: order list

#10357 Store creation: Remove feature flag `storeCreationMVP`
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/NotWPAccountViewModel.swift
  WooCommerce/Classes/Extensions/WordPressAuthenticator+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerceTests/Authentication/NotWPAccountViewModelTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
Labels: type: technical debt

#10351 [Better Customer Selector] Show customer list UI
  Experiments/Experiments/DefaultFeatureFlagService.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CustomerSelectorViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/OrderCustomerSection.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Search/SearchUICommand.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
  WooCommerce/Classes/ViewRelated/Search/SearchViewController.xib
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewRelated/Search/Customer/CustomerSearchUICommandTests.swift
Labels: type: task, feature: order creation

#10367 Merge 14.7.0.1 into trunk
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/description.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/description.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/description.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/description.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/description.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases
