Repository woocommerce/woocommerce-ios, pull requests merged in 2023-01, with the labels that each got.

#8473 REST API: Check application password availability after logging in
  Networking/Networking/ApplicationPassword/ApplicationPasswordUseCase.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ApplicationPasswordDisabledViewModel.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+UnifiedLogin.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/RoleEligibilityUseCaseTests.swift
  WooCommerce/WooCommerceTests/Internal/SessionManager+Internal.swift
  WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
  WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift
  Yosemite/Yosemite/Base/StoresManager.swift
  Yosemite/Yosemite/Model/Mocks/MockStoresManager.swift
Labels: type: task, feature: login, status: feature-flagged

#8505 Variations: Fetch all variations before generating variations
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductVariationSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductVariationSelectorViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/Bulk Update/BulkUpdateViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductVariationAction.swift
  Yosemite/Yosemite/Stores/ProductVariationStore.swift
  Yosemite/YosemiteTests/Stores/ProductVariationStoreTests.swift
Labels: feature: variation list

#8503 Fixes gaps on the Dashboard header
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: category: analytics

#8504 Widgets: Query data for configured store
  WooCommerce/StoreWidgets/StoreInfoProvider.swift
  WooCommerce/StoreWidgetsIntentsExtension/IntentHandler.swift
Labels: feature: widgets

#8515 [REST API] Add unit tests for `RequestProcessor`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/ApplicationPassword/RequestAuthenticator.swift
  Networking/Networking/ApplicationPassword/RequestProcessor.swift
  Networking/Networking/Network/AlamofireNetwork.swift
  Networking/NetworkingTests/ApplicationPassword/RequestProcessorTests.swift
  Networking/NetworkingTests/Network/DefaultRequestAuthenticatorTests.swift
Labels: type: task, feature: login

#8501 [REST API] Migrate Coupons Jetpack tunnel endpoints to REST API
  Networking/Networking/Remote/CouponsRemote.swift
Labels: type: task

#8502 [REST API] Delete application password upon logout
  Networking/Networking/ApplicationPassword/ApplicationPasswordStorage.swift
  Networking/Networking/ApplicationPassword/ApplicationPasswordUseCase.swift
  Networking/Networking/Settings/WooConstants.swift
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/WooCommerceTests/System/SessionManagerTests.swift
  WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift
  Yosemite/Yosemite/Base/SessionManagerProtocol.swift
  Yosemite/Yosemite/Model/Mocks/MockSessionManager.swift
Labels: type: task

#8509 Store creation M3: store country profiler question UI (not integrated to the flow)
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryButton.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountrySectionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/RequiredStoreCreationProfilerQuestionView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationCountryQuestionViewModelTests.swift
Labels: type: task

#8510 Store creation M3: store country profiler question - integration to the flow
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationSummaryView.swift
Labels: type: task

#8518 REST API: Update title and URL and hide Switch store button on Hub menu
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift
Labels: type: task, status: feature-flagged, feature: hub menu

#8478 REST API: Check role eligibility after authentication without WPCom
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/UserMapper.swift
  Networking/Networking/Remote/UserRemote.swift
  Networking/Networking/Requests/RESTRequest.swift
  Networking/NetworkingTests/Mapper/UserMapperTests.swift
  Networking/NetworkingTests/Responses/user-complete-without-data.json
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewController.xib
  WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift
  WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+UnifiedLogin.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/ButtonActivityIndicator.swift
  WooCommerce/WooCommerceTests/Authentication/RoleEligibilityUseCaseTests.swift
  WooCommerce/WooCommerceTests/Authentication/RoleErrorViewModelTests.swift
Labels: type: task, feature: login, status: feature-flagged

#8531 Simplified login: Remove A/B test
  Experiments/Experiments/ABTest.swift
  WooCommerce/Classes/Authentication/AuthenticationConstants.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Prologue/LoginProloguePages.swift
  WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
Labels: type: task, feature: login

#8525 REST API: Check for Woo after authentication
  Networking/Networking/Model/WordPressSite.swift
  Networking/NetworkingTests/Mapper/WordPressSiteMapperTests.swift
  Networking/NetworkingTests/Responses/wordpress-site-info.json
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/PostSiteCredentialLoginChecker.swift
  WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+UnifiedLogin.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/PostSiteCredentialLoginCheckerTests.swift
  Yosemite/YosemiteTests/Stores/WordPressSiteStore.swift
Labels: type: task, feature: login, status: feature-flagged

#8533 Conclude native Jetpack install experiment
  Experiments/Experiments/ABTest.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: type: task, feature: login

#8529 [IPPInAppFeedback] Add feature flag for IPP in-app feedback banner
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: enhancement, feature: mobile payments

#8526 Bulk Editing: Add feature flag and button
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Resources/Images.xcassets/icon-multiselect.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/icon-multiselect.imageset/icon-multiselect.pdf
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: feature: product list, status: feature-flagged

#8537 Variations: Generates all variations locally
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationGenerator.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationGeneratorTests.swift
Labels: feature: variation list

#8541 Variations: Stop generation if there are more than 100 variations to generate
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationGenerator.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationsViewModelTests.swift
Labels: feature: variation list

#8540 Reset Auto Layout constraint that pins to a view that is being removed to fix a crash
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Labels: type: crash

#8543 REST API: Show alert for inaccessible login or admin URL
  Networking/Networking/ApplicationPassword/ApplicationPasswordUseCase.swift
  Networking/NetworkingTests/ApplicationPassword/DefaultApplicationPasswordUseCaseTests.swift
  WooCommerce/Classes/Authentication/PostSiteCredentialLoginChecker.swift
  WooCommerce/WooCommerceTests/Authentication/PostSiteCredentialLoginCheckerTests.swift
Labels: type: task, feature: login, status: feature-flagged

#8546 REST API: Migrate leaderboards endpoint
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/LeaderboardListMapper.swift
  Networking/Networking/Remote/LeaderboardsRemote.swift
  Networking/NetworkingTests/Mapper/LeaderboardListMapperTests.swift
  Networking/NetworkingTests/Responses/leaderboards-year-without-data.json
Labels: type: task, feature: stats, status: feature-flagged

#8547 REST API: Migrate order stats
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/OrderStatsV4Mapper.swift
  Networking/Networking/Remote/OrderStatsRemoteV4.swift
  Networking/NetworkingTests/Mapper/OrderStatsMapperV4Tests.swift
  Networking/NetworkingTests/Responses/order-stats-v4-year-without-data.json
Labels: type: task, feature: stats, status: feature-flagged

#8545 Store creation: add support CTA to applicable screens
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryButton.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountryQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Country/StoreCreationCountrySectionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/RequiredStoreCreationProfilerQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Store name/StoreNameForm.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationSummaryView.swift
  WooCommerce/Classes/Authentication/Store Creation/SupportButton.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationCountryQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task, feature: support

#8552 Variations: Generate All Variations Remotely
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductVariationsBulkCreateMapper.swift
  Networking/Networking/Remote/ProductVariationsRemote.swift
  Networking/NetworkingTests/Remote/ProductVariationsRemoteTests.swift
  Networking/NetworkingTests/Responses/product-variations-bulk-create.json
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationsViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductVariationAction.swift
  Yosemite/Yosemite/Stores/ProductVariationStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductVariationsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductVariationStoreTests.swift
Labels: feature: variation list

#8562 IPP Menu: Handle not supported country case properly
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
Labels: type: task, feature: mobile payments

#8559 [REST API] Update Product endpoint mappers
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/EntityIDMapper.swift
  Networking/Networking/Mapper/ProductIDMapper.swift
  Networking/Networking/Mapper/ProductListMapper.swift
  Networking/Networking/Mapper/ProductMapper.swift
  Networking/Networking/Mapper/ProductSkuMapper.swift
  Networking/NetworkingTests/Mapper/EntityIDMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductIDMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductSkuMapperTests.swift
  Networking/NetworkingTests/Responses/product-id-only-without-data.json
  Networking/NetworkingTests/Responses/product-search-sku-without-data.json
  Networking/NetworkingTests/Responses/product-without-data.json
  Networking/NetworkingTests/Responses/products-ids-only-without-data.json
  Networking/NetworkingTests/Responses/products-load-all-without-data.json
Labels: type: task, feature: REST API

#8553 [REST API] Merge `WordPressOrgRequest` into `RESTRequest`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/ApplicationPassword/ApplicationPasswordUseCase.swift
  Networking/Networking/Remote/JetpackConnectionRemote.swift
  Networking/Networking/Requests/RESTRequest.swift
  Networking/Networking/Requests/WordPressOrgRequest.swift
  Networking/NetworkingTests/Remote/RemoteTests.swift
  Networking/NetworkingTests/Requests/RESTRequestTests.swift
  Networking/NetworkingTests/Requests/WordPressOrgRequestTests.swift
  docs/NETWORKING.md
Labels: type: task, feature: REST API

#8557 Store creation M3: update category question options with the full list of industries from web & Stripe
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionOptions.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationCategoryQuestionViewModelTests.swift
Labels: type: task

#8560 Variations: Refactor how we access all variations.
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationsViewModelTests.swift
  Yosemite/Yosemite/Actions/ProductVariationAction.swift
  Yosemite/Yosemite/Stores/ProductVariationStore.swift
Labels: feature: variation list

#8565 Variations: Ask for user confirmation before creating variations
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationsViewModelTests.swift
Labels: feature: variation list

#8571 Added release notes for 11.8
  CHANGELOG.md
Labels: Releases

#8576 Merge 11.7 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8579 Merge 11.8 code freeze into trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8554 REST API: Migrate orders endpoint
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/OrderListMapper.swift
  Networking/Networking/Mapper/OrderMapper.swift
  Networking/Networking/Mapper/OrderNoteMapper.swift
  Networking/Networking/Mapper/OrderNotesMapper.swift
  Networking/Networking/Mapper/ReportOrderTotalsMapper.swift
  Networking/Networking/Remote/OrdersRemote.swift
  Networking/Networking/Remote/ReportRemote.swift
  Networking/NetworkingTests/Mapper/OrderListMapperTests.swift
  Networking/NetworkingTests/Mapper/OrderMapperTests.swift
  Networking/NetworkingTests/Mapper/OrderNotesMapperTests.swift
  Networking/NetworkingTests/Mapper/ReportOrderTotalsMapperTests.swift
  Networking/NetworkingTests/Responses/order-notes-without-data.json
  Networking/NetworkingTests/Responses/order-without-data.json
  Networking/NetworkingTests/Responses/orders-load-all-without-data.json
  Networking/NetworkingTests/Responses/report-orders-total-without-data.json
  Networking/NetworkingTests/Responses/report-orders-total.json
Labels: type: task, feature: order details, feature: order list, status: feature-flagged, feature: order creation

#8569 REST API: Migrate refund endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/RefundListMapper.swift
  Networking/Networking/Mapper/RefundMapper.swift
  Networking/Networking/Remote/RefundsRemote.swift
  Networking/NetworkingTests/Mapper/RefundListMapperTests.swift
  Networking/NetworkingTests/Mapper/RefundMapperTests.swift
  Networking/NetworkingTests/Responses/refund-single-without-data.json
  Networking/NetworkingTests/Responses/refunds-all-without-data.json
Labels: type: task, feature: refunds, feature: REST API

#8570 Configure `WordPressAuthenticator` in `AppCoordinator` initialization to fix crash from deep links before login onboarding is complete
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
Labels: type: crash

#8590 Make `RESTRequest` work with both WooCommerce and WordPress API.
  Networking/Networking/Requests/RESTRequest.swift
  Networking/NetworkingTests/Requests/JetpackRequestTests.swift
  Networking/NetworkingTests/Requests/RESTRequestTests.swift
Labels: type: task, feature: REST API

#8358 [Mobile Payments] update tap on mobile designs
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInConnectingToReader.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInFollowReaderInstructions.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInReaderCheckingDeviceSupport.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInReaderProcessing.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInSuccess.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInSuccessWithoutEmail.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalSelectSearchType.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentsModalViewController.xib
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/built-in-reader-payment-success-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/built-in-reader-payment-success-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/built-in-reader-preparing-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/built-in-reader-preparing-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/built-in-reader-processing-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/built-in-reader-processing-light.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/card-payments-select-reader-type-dark.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/card-payments-select-reader-type-light.pdf
  WooCommerce/Resources/Images.xcassets/temp-woo-tap-on-mobile-check.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/temp-woo-tap-on-mobile-check.imageset/temp-woo-tap-on-mobile-check~universal.pdf
  WooCommerce/Resources/Images.xcassets/temp-woo-tap-on-mobile-prepare.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/temp-woo-tap-on-mobile-prepare.imageset/temp-woo-tap-on-mobile-prepare~universal.pdf
  WooCommerce/Resources/Images.xcassets/temp-woo-tap-on-mobile.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/temp-woo-tap-on-mobile.imageset/temp-woo-tap-on-mobile~universal.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: enhancement, feature: mobile payments, status: feature-flagged

#8581 Domain settings: feature flag, entry point from settings, barebone UI
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Networking/Networking/Remote/DomainRemote.swift
  Networking/Networking/Remote/PaymentRemote.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/FreeStagingDomainView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainSelectorViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
  Yosemite/Yosemite/Actions/DomainAction.swift
  Yosemite/Yosemite/Actions/PaymentAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/Yosemite/Stores/PaymentStore.swift
Labels: type: task, status: feature-flagged

#8599 Temporarily disable two flaky `InAppPurchaseStoreTests` test cases
  WooCommerce/WooCommerceTests/UnitTests.xctestplan
  WooCommerce/WooCommerceTests/Yosemite/InAppPurchaseStoreTests.swift
Labels: category: unit tests

#8587 REST API: Migrate payment gateway endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/PaymentGatewayListMapper.swift
  Networking/Networking/Mapper/PaymentGatewayMapper.swift
  Networking/Networking/Remote/PaymentGatewayRemote.swift
  Networking/NetworkingTests/Mapper/PaymentGatewayListMapperTests.swift
  Networking/NetworkingTests/Mapper/PaymentGatewayMapperTests.swift
  Networking/NetworkingTests/Responses/payment-gateway-cod-without-data.json
  Networking/NetworkingTests/Responses/payment-gateway-list-without-data.json
Labels: type: task, feature: REST API

#8600 Domain settings: networking layer changes for 2 endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/DomainRemote.swift
  Networking/Networking/Remote/PaymentRemote.swift
  Networking/Networking/Requests/DotcomRequest.swift
  Networking/Networking/Settings/WordPressAPIVersion.swift
  Networking/NetworkingTests/Remote/DomainRemoteTests.swift
  Networking/NetworkingTests/Remote/PaymentRemoteTests.swift
  Networking/NetworkingTests/Responses/load-site-current-plan-success.json
  Networking/NetworkingTests/Responses/load-site-plans-no-current-plan.json
  Networking/NetworkingTests/Responses/site-domains.json
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  Yosemite/Yosemite/Stores/PaymentStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDomainRemote.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockPaymentRemote.swift
Labels: type: task

#8573 Variations: Show loading indicators
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Progress/InProgressViewController.swift
Labels: feature: variation list

#8578 Variations: Completion notices
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationsViewModelTests.swift
Labels: feature: variation list

#8596 [Unit Tests] Set default currency settings in AnalyticsHubViewModelTests test setup
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubViewModelTests.swift
Labels: category: unit tests

#8563 Bulk Editing: Add selection state to products list
  Networking/Networking/Model/Product/Product.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: product list, status: feature-flagged

#8609 Bulk Editing: Update Networking/Yosemite
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductsBulkUpdateMapper.swift
  Networking/Networking/Remote/ProductsRemote.swift
  Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
  Networking/NetworkingTests/Responses/products-batch-update.json
  Yosemite/Yosemite/Actions/ProductAction.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: feature: product list

#8610 Variations: Error handling
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationsViewModelTests.swift
Labels: feature: variation list

#8612 Variations: Update product variation count after generating variations
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
Labels: feature: variation list

#8614 Variations: Create all variations from no variations empty state screen
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateAllVariationsPresenter.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateVariationsOptionPresenter.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: variation list

#8595 [Mobile Payments] Check built in card reader requirements
  Hardware/Hardware/CardReader/CardReaderService.swift
  Hardware/Hardware/CardReader/StripeCardReader/CardReaderType+Stripe.swift
  Hardware/Hardware/CardReader/StripeCardReader/NoOpCardReaderService.swift
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
  WooCommerce/Classes/Model/BetaFeature.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  Yosemite/Yosemite/Actions/CardPresentPaymentAction.swift
  Yosemite/Yosemite/Stores/CardPresentPaymentStore.swift
  Yosemite/YosemiteTests/Mocks/CardPresentPayments/MockCardReaderService.swift
  Yosemite/YosemiteTests/Stores/CardPresentPaymentStoreTests.swift
Labels: type: enhancement, feature: mobile payments, status: feature-flagged

#8567 Do not force `try` instantiating `TabNavComponent` in UI tests
  WooCommerce/UITestsFoundation/Screens/Orders/SingleOrderScreen.swift
  WooCommerce/UITestsFoundation/Screens/Products/ProductsScreen.swift
  WooCommerce/UITestsFoundation/Screens/Reviews/ReviewsScreen.swift
Labels: category: ui tests

#8617 Bulk Editing: Add bottom toolbar to the products list
  WooCommerce/Classes/Extensions/UIButton+Helpers.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.xib
  WooCommerce/Classes/ViewRelated/Toolbar/ToolbarView.swift
Labels: feature: product list, status: feature-flagged

#8616 Variations: Create all variations from no attributes empty state screen.
  WooCommerce/Classes/ViewRelated/Products/Variations/Edit Attributes/EditAttributesViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/Edit Attributes/EditAttributesViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateAllVariationsPresenter.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateAllVariationsUseCase.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/GenerateAllVariationsUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Variations/ProductVariationsViewModelTests.swift
Labels: feature: variation list

#8628 [Mobile Payments] Update card reader manual URLs
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardReaderType+Manual.swift
Labels: type: bug, feature: mobile payments

#8613 Analytics Hub: Fix range generation structure
  Networking/Networking/Extensions/DateFormatter+Woo.swift
  WooCommerce/Classes/Extensions/Date+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/AnalyticsTimeRangeCard.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/AnalyticsHubTimeRange.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/AnalyticsHubTimeRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/AnalyticsHubTimeRangeSelection.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubCustomRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubLastMonthRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubLastQuarterRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubLastWeekRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubLastYearRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubMonthToDateRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubQuarterToDateRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubTodayRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubWeekToDateRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubYearToDateRangeData.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubYesterdayRangeData.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubTimeRangeSelectionTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Analytics Hub/AnalyticsHubTimeRangeTests.swift
Labels: feature: stats

#8618 Variations: Add track events
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateAllVariationsUseCase.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateVariationsOptionPresenter.swift
Labels: feature: variation list

#8619 Variations: Remove feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateAllVariationsUseCase.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/GenerateVariationsOptionPresenter.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
  Yosemite/Yosemite/Stores/ProductVariationStore.swift
Labels: feature: variation list

#8631 Correct title in the Payments Menu
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewController.swift
Labels: type: enhancement

#8626 [Mobile Payments] Add metadata to payment intent for TTPoI
  Hardware/Hardware/CardReader/CardReaderType.swift
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
Labels: type: task, feature: mobile payments

#8632 Merge 11.8 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/copyright.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8601 Domain settings: Yosemite layer changes for 2 actions
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/Yosemite/Stores/PaymentStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDomainRemote.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockPaymentRemote.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
  Yosemite/YosemiteTests/Stores/PaymentStoreTests.swift
Labels: type: task

#8634 Merge 11.9 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8604 REST API: Migrate system status endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/SystemPluginMapper.swift
  Networking/Networking/Mapper/SystemStatusMapper.swift
  Networking/Networking/Remote/SystemStatusRemote.swift
  Networking/NetworkingTests/Mapper/SystemPluginMapperTests.swift
  Networking/NetworkingTests/Mapper/SystemStatusMapperTests.swift
  Networking/NetworkingTests/Responses/systemStatus-without-data.json
  Networking/NetworkingTests/Responses/systemStatusWithPluginsOnly-without-data.json
Labels: type: task, feature: REST API

#8607 REST API: Update WordPress site info fetching task to run on main thread
  Yosemite/Yosemite/Stores/WordPressSiteStore.swift
Labels: type: bug, status: feature-flagged, feature: REST API

#8638 REST API: Migrate site settings endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/SiteSettingMapper.swift
  Networking/Networking/Mapper/SiteSettingsMapper.swift
  Networking/Networking/Remote/SiteSettingsRemote.swift
  Networking/NetworkingTests/Mapper/SiteSettingMapperTests.swift
  Networking/NetworkingTests/Mapper/SiteSettingsMapperTests.swift
  Networking/NetworkingTests/Responses/setting-coupon-without-data.json
  Networking/NetworkingTests/Responses/settings-general-without-data.json
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
Labels: type: task, feature: REST API

#8641 REST API: Migrate inbox note endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/InboxNoteListMapper.swift
  Networking/Networking/Mapper/InboxNoteMapper.swift
  Networking/Networking/Remote/InboxNotesRemote.swift
  Networking/NetworkingTests/Mapper/InboxNoteListMapperTests.swift
  Networking/NetworkingTests/Mapper/InboxNoteMapperTests.swift
  Networking/NetworkingTests/Responses/inbox-note-list-without-data.json
  Networking/NetworkingTests/Responses/inbox-note-without-data.json
Labels: type: task, feature: REST API

#8606 Domain settings: show a list of domains with a CTA to add a domain
  WooCommerce/Classes/View Modifiers/View+DividerStyle.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsListView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#8635 Added release notes for 11.9
  CHANGELOG.md
Labels: Releases

#8620 [Mobile Payments] Built-in reader disconnection during payment error message
  Hardware/Hardware/CardReader/UnderlyingError.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsView.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Simple Payments/MockCollectOrderPaymentUseCase.swift
Labels: type: task, feature: mobile payments, status: feature-flagged

#8651 Merge 11.9 release notes into trunk
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
Labels: Releases

#8642 Domain selector for paid domains: Networking layer changes
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/DomainRemote.swift
  Networking/NetworkingTests/Remote/DomainRemoteTests.swift
  Networking/NetworkingTests/Responses/domain-products.json
  Networking/NetworkingTests/Responses/domain-suggestions-paid.json
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDomainRemote.swift
Labels: type: task

#8549 [IPPInAppFeedback] Banner business logic and merchant eligibility in Orders screen
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
Labels: type: enhancement, feature: mobile payments

#8647 Migrate the telemetry endpoint to use REST API
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/SiteAPIMapper.swift
  Networking/Networking/Remote/SiteAPIRemote.swift
  Networking/Networking/Remote/TelemetryRemote.swift
  Networking/NetworkingTests/Mapper/SiteAPIMapperTests.swift
  Networking/NetworkingTests/Remote/TelemetryRemoteTests.swift
  Networking/NetworkingTests/Responses/site-api-without-data.json
Labels: type: task, feature: REST API

#8652 Bulk Editing: Add status picker
  Networking/Networking/Model/Product/Product.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/List Selector Data Source/ProductStatusSettingListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
Labels: feature: product list, status: feature-flagged

#8653 Configure code signing for Widgets Intents target
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: category: tooling

#8658 Improve provisioning profiles update workflow from Fastlane
  fastlane/Fastfile
  fastlane/Matchfile
Labels: category: tooling

#8660 Domain selector for paid domains: Yosemite layer changes
  Yosemite/Yosemite/Actions/DomainAction.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDomainRemote.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
Labels: type: task

#8656 Store creation: send a Tracks event with profiler answers when reaching store summary screen
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreCreation.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Category/StoreCreationCategoryQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingPlatformsQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingPlatformsQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingStatusQuestionContainerView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingStatusQuestionView.swift
  WooCommerce/Classes/Authentication/Store Creation/Profiler/Selling Status/StoreCreationSellingStatusQuestionViewModel.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationCategoryQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationSellingPlatformsQuestionViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Store Creation/Profiler/StoreCreationSellingStatusQuestionViewModelTests.swift
Labels: type: task, category: analytics

#8659 REST API: Custom cookie nonce authenticator
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/ApplicationPassword/ApplicationPasswordAuthenticator.swift
  Networking/Networking/ApplicationPassword/ApplicationPasswordRequestProcessor.swift
  Networking/Networking/ApplicationPassword/ApplicationPasswordUseCase.swift
  Networking/Networking/CookieNonce/CookieNonceAuthenticator.swift
  Networking/Networking/Network/AlamofireNetwork.swift
  Networking/Networking/Network/WordPressOrgNetwork.swift
  Networking/NetworkingTests/ApplicationPassword/ApplicationPasswordRequestProcessorTests.swift
  Networking/NetworkingTests/Network/DefaultRequestAuthenticatorTests.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Site Credential Login/SiteCredentialLoginViewModel.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/WrongAccountErrorViewModel.swift
  WooCommerce/Classes/Authentication/WordPressOrgCredentials+Authenticator.swift
  WooCommerce/WooCommerceTests/Extensions/WordPressOrgCredentialsAuthenticatorTests.swift
Labels: type: enhancement, feature: REST API

#8669 WPAuthenticator - Config flag to enable custom step value for get started screen.
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: feature: login

#8665 REST API: Skip setting up push notification if authenticated without WPCom
  WooCommerce/Classes/AppDelegate.swift
Labels: type: task, feature: REST API

#8663 Domain selector for paid domains: UI integration
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainRowView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorDataProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainSelectorViewModelTests.swift
  Yosemite/Yosemite/Actions/DomainAction.swift
Labels: type: task, status: feature-flagged

#8667 Store creation: release profiler questions
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+StoreCreation.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
Labels: type: task, category: analytics

#8633 [Mobile Payments] Fix Tap to Pay on iPhone setup failures on second account
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
  WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Stores/CardPresentPaymentStore.swift
  Yosemite/Yosemite/Tools/CommonReaderConfigProvider.swift
  Yosemite/YosemiteTests/Mocks/CardPresentPayments/MockCommonReaderConfigProviding.swift
  Yosemite/YosemiteTests/Stores/CardPresentPaymentStoreTests.swift
Labels: type: bug, feature: mobile payments

#8650 [Mobile Payments] Fix connection loop when Tap To Pay terms acceptance is cancelled
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/BuiltInCardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
Labels: type: task, feature: mobile payments, category: analytics, status: feature-flagged

#8666 [Mobile Payments] Disconnect built-in reader when Manage card readers is tapped
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BluetoothCardReaderSettingsConnectedViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsConnectedViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsViewModelsOrderedList.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockCardPresentPaymentsStoresManager.swift
  WooCommerce/WooCommerceTests/Mocks/MockCardReader.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/CardReaderSettings/BluetoothCardReaderSettingsConnectedViewModelTests.swift
Labels: type: enhancement, feature: mobile payments, status: feature-flagged

#8640 [IPPInAppFeedback] Orders screen banner placement
  Storage/Storage/Model/FeedbackType.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
  Yosemite/Yosemite/Stores/AppSettings/InAppFeedbackCardVisibilityUseCase.swift
Labels: type: enhancement, feature: mobile payments

#8682 [REST API] Avail `DotcomRequest` as `RESTRequest`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/ApplicationPassword/RequestConverter.swift
  Networking/Networking/Requests/DotcomRequest.swift
  Networking/Networking/Requests/JetpackRequest.swift
  Networking/Networking/Requests/RESTRequestConvertible.swift
  Networking/Networking/Settings/WordPressAPIVersion.swift
  Networking/NetworkingTests/Requests/DotcomRequestTests.swift
  Networking/NetworkingTests/Settings/WordPressAPIVersionTests.swift
Labels: type: task, feature: REST API

#8693 REST API: Revert naming to `RequestProcessor` and `RequestAuthenticator`
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/ApplicationPassword/RequestAuthenticator.swift
  Networking/Networking/ApplicationPassword/RequestProcessor.swift
  Networking/Networking/Network/AlamofireNetwork.swift
  Networking/NetworkingTests/ApplicationPassword/RequestProcessorTests.swift
  Networking/NetworkingTests/Network/DefaultRequestAuthenticatorTests.swift
Labels: feature: REST API

#8686 [REST API] Migrate MediaRemote endpoints
  Networking/Networking/Remote/MediaRemote.swift
  Networking/Networking/Settings/WooConstants.swift
  Yosemite/Yosemite/Stores/MediaStore.swift
  Yosemite/YosemiteTests/Stores/MediaStoreTests.swift
Labels: type: task, feature: REST API

#8684 REST API: Update login flow for AB testing the REST API project
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Navigation Exceptions/ApplicationPasswordDisabledViewModel.swift
  WooCommerce/Classes/Authentication/PostSiteCredentialLoginChecker.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/ApplicationPasswordDisabledViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift
Labels: type: task, feature: login, feature: REST API

#8687 [REST API] Migrate Jetpack requests in `ProductsRemote`
  Networking/Networking/Remote/ProductsRemote.swift
Labels: type: task, feature: REST API

#8691 Bulk Editing: Add price picker
  WooCommerce/Classes/ViewRelated/Products/PriceInputViewController.swift
  WooCommerce/Classes/ViewRelated/Products/PriceInputViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Edit Price/Bulk Edit Price/PriceInputViewControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Edit Price/Bulk Edit Price/PriceInputViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
Labels: feature: product list, status: feature-flagged

#8698 Bulk Editing: Add select all action
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
Labels: feature: product list, status: feature-flagged

#8699 Bulk Editing: Warn about variations in price flow
  WooCommerce/Classes/ViewRelated/Products/PriceInputViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
Labels: feature: product list, status: feature-flagged

#8690 [Mobile Payments] Receipt Printing Controller is not shown
  WooCommerce/Classes/ViewModels/CardPresentPayments/ReceiptActionCoordinator.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/ReceiptViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyCollectOrderPaymentUseCaseTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/ReceiptActionCoordinatorTests.swift
Labels: type: bug, feature: mobile payments

#8701 Bulk Editing: Tracks
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: feature: product list, category: analytics, status: feature-flagged

#8689 [IPPInAppFeedback] Make banner content and surveys change dynamically
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
Labels: feature: mobile payments

#8704 Bulk Editing: Remove feature flag and release
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: feature: product list

#8649 REST API: Migrate Stripe and WCPay endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ReaderConnectionTokenMapper.swift
  Networking/Networking/Mapper/RemotePaymentIntentMapper.swift
  Networking/Networking/Mapper/RemoteReaderLocationMapper.swift
  Networking/Networking/Mapper/StripeAccountMapper.swift
  Networking/Networking/Mapper/WCPayAccountMapper.swift
  Networking/Networking/Mapper/WCPayChargeMapper.swift
  Networking/Networking/Model/WordPressSite.swift
  Networking/Networking/Remote/StripeRemote.swift
  Networking/Networking/Remote/WCPayRemote.swift
  Networking/NetworkingTests/Mapper/WCPayChargeMapperTests.swift
  Networking/NetworkingTests/Responses/wcpay-charge-card-present-without-data.json
  Yosemite/YosemiteTests/Stores/WordPressSiteStore.swift
Labels: type: task, feature: REST API

#8662 REST API: Migrate JITM endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/DataBoolMapper.swift
  Networking/Networking/Mapper/JustInTimeMessageListMapper.swift
  Networking/Networking/Remote/JustInTimeMessagesRemote.swift
  Networking/NetworkingTests/Mapper/JustInTimeMessageListMapperTests.swift
  Networking/NetworkingTests/Responses/just-in-time-message-list-without-data.json
Labels: type: task, feature: REST API

#8703 REST API: Hide password protected option on product visibility screen for users authenticated without WPCom
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Visibility/ProductVisibilityViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormRemoteActionUseCase.swift
Labels: type: task, feature: REST API

#8670 REST API: Migrate product add-ons
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/AddOnGroupMapper.swift
  Networking/Networking/Remote/AddOnGroupRemote.swift
  Networking/NetworkingTests/Mapper/AddOnGroupMapperTests.swift
  Networking/NetworkingTests/Responses/add-on-groups-without-data.json
Labels: type: task, feature: REST API

#8676 REST API: Migrate shipping label endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/OrderShippingLabelListMapper.swift
  Networking/Networking/Mapper/ShippingLabelAccountSettingsMapper.swift
  Networking/Networking/Mapper/ShippingLabelAddressValidationSuccessMapper.swift
  Networking/Networking/Mapper/ShippingLabelCarriersAndRatesMapper.swift
  Networking/Networking/Mapper/ShippingLabelCreationEligibilityMapper.swift
  Networking/Networking/Mapper/ShippingLabelPackagesMapper.swift
  Networking/Networking/Mapper/ShippingLabelPrintDataMapper.swift
  Networking/Networking/Mapper/ShippingLabelPurchaseMapper.swift
  Networking/Networking/Mapper/ShippingLabelRefundMapper.swift
  Networking/Networking/Mapper/ShippingLabelStatusMapper.swift
  Networking/Networking/Mapper/SuccessDataResultMapper.swift
  Networking/Networking/Remote/ShippingLabelRemote.swift
  Networking/NetworkingTests/Mapper/OrderShippingLabelListMapperTests.swift
  Networking/NetworkingTests/Mapper/ShippingLabelAccountSettingsMapperTests.swift
  Networking/NetworkingTests/Mapper/ShippingLabelCreationEligibilityMapperTests.swift
  Networking/NetworkingTests/Mapper/ShippingLabelPackagesMapperTests.swift
  Networking/NetworkingTests/Mapper/ShippingLabelPurchaseMapperTests.swift
  Networking/NetworkingTests/Mapper/ShippingLabelStatusMapperTests.swift
  Networking/NetworkingTests/Responses/order-shipping-labels-without-data.json
  Networking/NetworkingTests/Responses/shipping-label-account-settings-without-data.json
  Networking/NetworkingTests/Responses/shipping-label-eligibility-failure-without-data.json
  Networking/NetworkingTests/Responses/shipping-label-eligibility-success-without-data.json
  Networking/NetworkingTests/Responses/shipping-label-packages-success-without-data.json
  Networking/NetworkingTests/Responses/shipping-label-purchase-success-without-data.json
  Networking/NetworkingTests/Responses/shipping-label-status-success-without-data.json
Labels: type: task, feature: REST API

#8678 REST API: Migrate site plugin fetching endpoint
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/SitePluginsMapper.swift
  Networking/Networking/Remote/SitePluginsRemote.swift
  Networking/NetworkingTests/Mapper/SitePluginsMapperTests.swift
  Networking/NetworkingTests/Responses/plugins-without-data.json
Labels: type: task, feature: REST API

#8697 REST API: Track login events
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
  WooCommerce/Classes/Authentication/PostSiteCredentialLoginChecker.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
Labels: type: task, feature: login, category: analytics, feature: REST API

#8716 REST API: Migrate product review endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductReviewListMapper.swift
  Networking/Networking/Mapper/ProductReviewMapper.swift
  Networking/Networking/Remote/ProductReviewsRemote.swift
  Networking/NetworkingTests/Mapper/ProductReviewListMapperTests.swift
  Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift
  Networking/NetworkingTests/Responses/reviews-all-without-data.json
  Networking/NetworkingTests/Responses/reviews-single-without-data.json
  WooCommerce/Classes/ViewRelated/Reviews/ReviewDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewModel.swift
Labels: type: task, feature: REST API

#8708 [Mobile Payments] Update error image for Tap to Pay on iPhone
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailed.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectionFailedUpdateAddress.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalError.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalScanningFailed.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalUpdateFailed.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalUpdateFailedNonRetryable.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentRetryableError.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInReaderConnectionAlertsProvider.swift
  WooCommerce/Resources/Images.xcassets/built-in-reader-error.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-error.imageset/illustration - error-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-error.imageset/illustration - error-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/built-in-reader-payment-success-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/built-in-reader-payment-success-light.pdf
Labels: type: task, feature: mobile payments, status: feature-flagged

#8709 [Mobile Payments] Temporary update to images for Tap to Pay
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/illustration - Payment successful-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/illustration - Payment successful-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/built-in-reader-preparing-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/built-in-reader-preparing-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/illustration - Preparing for payment-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/illustration - Preparing for payment-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/built-in-reader-processing-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/built-in-reader-processing-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/illustration - Processing payment-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/illustration - Processing payment-light.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/illustration - reader type-dark.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/illustration - reader type-light.pdf
Labels: type: task, feature: mobile payments, status: feature-flagged

#8657 [IPPInAppFeedback] Banner dismiss logic
  Storage/Storage/Model/Feature Announcements/FeatureAnnouncementCampaign.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/FeatureAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/ProductsOnboardingAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  Yosemite/Yosemite/Actions/AppSettingsAction.swift
  Yosemite/Yosemite/Stores/AppSettingsStore.swift
  Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Labels: feature: mobile payments

#8705 [Mobile Payments] Additional analytics events for Tap to Pay on iPhone
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardPresentPaymentPreflightController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionAnalyticsTracker.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BluetoothCardReaderSettingsConnectedViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/CardReaderSettings/BluetoothCardReaderSettingsConnectedViewModelTests.swift
Labels: type: task, feature: mobile payments, category: analytics, status: feature-flagged

#8713 Added release notes for 12.0
  CHANGELOG.md
Labels: Releases

#8720 Bulk Editing: Fix disappearing separators
  WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift
Labels: feature: product list

#8719 Bulk Editing: Tweak products toolbar
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.xib
  WooCommerce/Classes/ViewRelated/Toolbar/ToolbarView.swift
Labels: feature: product list

#8723 Bulk Editing: Fix margins on iPad
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: feature: product list

#8726 Merge 12.0 code freeze into trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8718 Products & Product Variation: Allow alternative type for purchasable
  Networking/Networking/Extensions/KeyedDecodingContainer+Woo.swift
  Networking/Networking/Model/Product/Product.swift
  Networking/Networking/Model/Product/ProductVariation.swift
  Networking/NetworkingTests/Mapper/ProductMapperTests.swift
  Networking/NetworkingTests/Responses/product-alternative-types.json
  RELEASE-NOTES.txt
Labels: type: enhancement, feature: product list

#8721 [Mobile Payments] Minor changes from Tap to Pay Test Charter 2
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInConnectingToReader.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlertsProtocol.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BluetoothCardReaderPaymentAlertsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTransactionAlertsProviding.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift
  WooCommerce/WooCommerceTests/Mocks/MockOrderDetailsPaymentAlerts.swift
Labels: type: task, feature: mobile payments, status: feature-flagged

#8717 REST API: Migrate product category endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductCategoryListMapper.swift
  Networking/Networking/Mapper/ProductCategoryMapper.swift
  Networking/Networking/Remote/ProductCategoriesRemote.swift
  Networking/NetworkingTests/Mapper/ProductCategoryMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductCategoyListMapperTests.swift
  Networking/NetworkingTests/Responses/categories-all-without-data.json
  Networking/NetworkingTests/Responses/category-without-data.json
Labels: type: task, feature: REST API

#8724 [Mobile Payments] Move IPP Learn More Link to Menu
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInReaderCheckingDeviceSupport.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalScanningForReader.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
Labels: type: bug, feature: mobile payments

#8734 [Mobile Payments] Use built-in reader images with transparency
  WooCommerce/Resources/Images.xcassets/built-in-reader-error.imageset/illustration - error-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-error.imageset/illustration - error-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/illustration - Payment successful-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/illustration - Payment successful-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/illustration - Preparing for payment-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/illustration - Preparing for payment-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/illustration - Processing payment-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/illustration - Processing payment-light.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/illustration - reader type-dark.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/illustration - reader type-light.pdf
Labels: type: task, feature: mobile payments, status: feature-flagged

#8714 [IPPInAppFeedback] Add In-Person Payments feedback banner track events
  Storage/Storage/Model/Feature Announcements/FeatureAnnouncementCampaign.swift
  Storage/Storage/Model/FeedbackType.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
  Yosemite/Yosemite/Stores/AppSettings/InAppFeedbackCardVisibilityUseCase.swift
Labels: type: task, feature: mobile payments, category: analytics

#8732 [REST API] Track application password events
  Networking/Networking/ApplicationPassword/RequestProcessor.swift
  Networking/NetworkingTests/ApplicationPassword/RequestProcessorTests.swift
  WooCommerce/Classes/Analytics/TrackEventRequestNotificationHandler.swift
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ApplicationPassword.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/PostSiteCredentialLoginChecker.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Yosemite/TrackEventRequestNotificationHandlerTests.swift
Labels: type: task, category: analytics, feature: REST API

#8730 [IPPInAppFeedback] Update and save feedback status upon merchant submission
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
Labels: type: task, feature: mobile payments

#8736 [REST API] Migrate product variations and attributes
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductAttributeListMapper.swift
  Networking/Networking/Mapper/ProductAttributeMapper.swift
  Networking/Networking/Mapper/ProductAttributeTermListMapper.swift
  Networking/Networking/Mapper/ProductAttributeTermMapper.swift
  Networking/Networking/Mapper/ProductVariationListMapper.swift
  Networking/Networking/Mapper/ProductVariationMapper.swift
  Networking/Networking/Mapper/ProductVariationsBulkCreateMapper.swift
  Networking/Networking/Mapper/ProductVariationsBulkUpdateMapper.swift
  Networking/Networking/Mapper/ProductsBulkUpdateMapper.swift
  Networking/Networking/Remote/ProductAttributeTermRemote.swift
  Networking/Networking/Remote/ProductAttributesRemote.swift
  Networking/Networking/Remote/ProductVariationsRemote.swift
  Networking/NetworkingTests/Mapper/ProductAttributeListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductAttributeMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductAttributeTermListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductAttributeTermMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductVariationListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductVariationMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductVariationsBulkCreateMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductVariationsBulkUpdateMapperTests.swift
  Networking/NetworkingTests/Responses/attribute-term-without-data.json
  Networking/NetworkingTests/Responses/product-attribute-create-without-data.json
  Networking/NetworkingTests/Responses/product-attribute-terms-without-data.json
  Networking/NetworkingTests/Responses/product-attributes-all-without-data.json
  Networking/NetworkingTests/Responses/product-variation-update-without-data.json
  Networking/NetworkingTests/Responses/product-variations-bulk-create-without-data.json
  Networking/NetworkingTests/Responses/product-variations-bulk-update-without-data.json
  Networking/NetworkingTests/Responses/product-variations-load-all-without-data.json
Labels: type: task, feature: REST API

#8739 [REST API] Migrate product shipping class endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/ProductShippingClassListMapper.swift
  Networking/Networking/Mapper/ProductShippingClassMapper.swift
  Networking/Networking/Remote/ProductShippingClassRemote.swift
  Networking/NetworkingTests/Mapper/ProductShippingClassListMapperTests.swift
  Networking/NetworkingTests/Mapper/ProductShippingClassMapperTests.swift
  Networking/NetworkingTests/Responses/product-shipping-classes-load-all-without-data.json
  Networking/NetworkingTests/Responses/product-shipping-classes-load-one-without-data.json
Labels: type: task, feature: REST API

#8738 Issue/8397 ipp learn more link payment methods
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/LearnMoreViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsView.swift
Labels: type: task, feature: mobile payments

#8728 [IPPInAppFeedback] UI banner component design tweaks
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/Extensions/UIView+Border.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
  WooCommerce/Resources/Images.xcassets/icon-comment-content.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/icon-comment-content.imageset/icon-comment-content.pdf
Labels: type: enhancement, feature: mobile payments

#8741 [REST API] Migrate product tax class endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/TaxClassListMapper.swift
  Networking/Networking/Remote/TaxClassRemote.swift
  Networking/NetworkingTests/Mapper/TaxClassListMapperTest.swift
  Networking/NetworkingTests/Responses/taxes-classes-without-data.json
Labels: type: task, feature: REST API

#8743 [REST API] Migrate shipment tracking provider endpoints
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Mapper/NewShipmentTrackingMapper.swift
  Networking/Networking/Mapper/ShipmentTrackingListMapper.swift
  Networking/Networking/Mapper/ShipmentTrackingProviderListMapper.swift
  Networking/Networking/Remote/ShipmentsRemote.swift
  Networking/NetworkingTests/Mapper/NewShipmentTrackingMapperTests.swift
  Networking/NetworkingTests/Mapper/ShipmentTrackingListMapperTests.swift
  Networking/NetworkingTests/Mapper/ShipmentTrackingProviderListMapperTests.swift
  Networking/NetworkingTests/Responses/shipment_tracking_new-without-data.json
  Networking/NetworkingTests/Responses/shipment_tracking_new.json
  Networking/NetworkingTests/Responses/shipment_tracking_providers_without_data.json
  Networking/NetworkingTests/Responses/shipment_tracking_single_without_data.json
Labels: type: task, feature: REST API

#8748 [IPPInAppFeedback] Workaround to survey content UI glitch
  WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
Labels: type: bug, feature: mobile payments

#8731 [IPPInAppFeedback] Prepare for release
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: feature: mobile payments

#8757 [Mobile Payments] Start search again when Try Again tapped on Built-in reader connection errors
  Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailed.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/BuiltInCardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BluetoothReaderConnectionAlertsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInReaderConnectionAlertsProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderConnectionAlertsProviding.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderSettingsAlerts.swift
  WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedTests.swift
Labels: type: bug, feature: mobile payments

#8744 [REST API] Introduce A/B test and remove feature flag
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: type: task, feature: REST API

#8753 [REST API] Track assigned A/B test variant
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ApplicationPassword.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
Labels: type: task, category: analytics, feature: REST API

#8761 [REST API] Release notes entry
  RELEASE-NOTES.txt
Labels: type: task, feature: REST API

#8762 Added release notes for 12.1
  CHANGELOG.md
Labels: Releases

#8763 [REST API] Logout if application password authentication fails
  Networking/Networking/CookieNonce/CookieNonceAuthenticator.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
  WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift
Labels: type: task, feature: REST API

#8759 Beta fix: Update bulk editing flow to remove toolbar
  WooCommerce/Classes/ViewRelated/Products/PriceInputViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.xib
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
Labels: feature: product list

#8765 Merge 12.0 final into trunk
  WooCommerce/Classes/ViewRelated/Products/PriceInputViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsListViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.xib
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerceTests/ViewRelated/Products/ProductListViewModelTests.swift
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8696 Domain web checkout flow with cart creation and a barebone success view
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/DomainRemote.swift
  Networking/Networking/Remote/PaymentRemote.swift
  Networking/Networking/Requests/DotcomRequest.swift
  Networking/NetworkingTests/Remote/PaymentRemoteTests.swift
  Networking/NetworkingTests/Responses/create-doman-cart-success.json
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainPurchaseSuccessView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorDataProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/DomainAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockPaymentRemote.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
Labels: type: task

#8766 Merge 12.1 code freeze into trunk
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8710 Domain selector: show attributed price info
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorDataProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/Domains/FreeDomainSelectorViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewModels/Domains/PaidDomainSelectorDataProviderTests.swift
  WooFoundation/WooFoundation/Colors/UIColor+SemanticColors.swift
Labels: type: enhancement

#8769 [REST API] `ABTestVariationProvider` for unit testing
  Experiments/Experiments.xcodeproj/project.pbxproj
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/ABTestVariationProvider.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockABTestVariationProvider.swift
Labels: type: bug, feature: REST API

#8764 [Mobile Payments] Measure Order Creation IPP Flows
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/LegacyCollectOrderPaymentUseCase.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/DurationRecorder/OrderDurationRecorder.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/EditableOrderViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/ReviewAgeTests.swift
Labels: type: task

#8772 [Variable Product] - Variation name input should start with uppercase
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Variations/Add Attributes/AddAttributeViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift
Labels: feature: variation details

#8775 REST API: Use generic error message for when application password generation is unauthorized
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/PostSiteCredentialLoginChecker.swift
Labels: type: bug, feature: login

#8771 Domain credit redemption without contact information
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/PaymentRemote.swift
  Networking/NetworkingTests/Remote/PaymentRemoteTests.swift
  Networking/NetworkingTests/Responses/checkout-doman-cart-with-domain-credit-success.json
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorDataProvider.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/WooCommerceTests/ViewModels/Domains/PaidDomainSelectorDataProviderTests.swift
  Yosemite/Yosemite/Actions/DomainAction.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockPaymentRemote.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
Labels: type: task

#8752 Allow production iap test.
  WooCommerce/Classes/ViewRelated/InAppPurchases/InAppPurchasesDebugView.swift
Labels: feature: in-app purchases
