Repository woocommerce/woocommerce-ios, pull requests merged in 2023-02, with the labels that each got.

#8783 [Variable Product] Variation list order shouldn't change on refresh
  WooCommerce/Classes/ViewRelated/Products/Variations/Add Attributes/AddAttributeOptionsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
Labels: feature: variation list

#8785 Polish domain purchase success UI
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainPurchaseSuccessView.swift
  WooCommerce/Resources/Images.xcassets/domain-purchase-success.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/domain-purchase-success.imageset/domain-purchase-success.pdf
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task

#8784 Domain contact information form before redeeming domain credit
  Fakes/Fakes/Networking.generated.swift
  Networking/Networking/Remote/DomainRemote.swift
  Networking/Networking/Remote/PaymentRemote.swift
  Networking/NetworkingTests/Remote/PaymentRemoteTests.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Actions/DomainAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockPaymentRemote.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
Labels: type: task

#8807 REST API: Clear login error notification after successful login with site credentials
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
Labels: type: bug, feature: login

#8790 REST API: Remove XMLRPC check for site address login
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/SiteCredentialLoginUseCase.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/SiteCredentialLoginUseCaseTests.swift
Labels: type: enhancement, feature: login

#8789 Tracks: Add error code to networking error tracking
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalytics.swift
Labels: type: enhancement, status: draft

#8813 Adds .supportRequest Feature Flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: feature: support

#8803 Load/validate domain contact info before/after the form
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/DomainRemote.swift
  Networking/NetworkingTests/Remote/DomainRemoteTests.swift
  Networking/NetworkingTests/Responses/domain-contact-info.json
  Networking/NetworkingTests/Responses/validate-domain-contact-info-failure.json
  Networking/NetworkingTests/Responses/validate-domain-contact-info-success.json
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModelProtocol.swift
  Yosemite/Yosemite/Actions/DomainAction.swift
  Yosemite/Yosemite/Model/Model.swift
  Yosemite/Yosemite/Stores/DomainStore.swift
  Yosemite/YosemiteTests/Mocks/Networking/Remote/MockDomainRemote.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
Labels: type: task

#8809 Address a few warnings in the tests targets
  Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Labels: category: unit tests

#8817 REST API: Disable credential auto-fill for site address login only
  Podfile.lock
Labels: type: bug, feature: login

#8819 Domain settings > domain selector: UI updates - title, subtitle, no contact support CTA
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSelectorViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/WooCommerceTests/ViewModels/Domains/FreeDomainSelectorViewModelTests.swift
Labels: type: task

#8820 REST API: Update reply comment endpoint to use the REST API
  Networking/Networking/Remote/CommentRemote.swift
  Networking/NetworkingTests/Remote/CommentRemoteTests.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewDetailsViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewReplyViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Reviews/ReviewReplyViewModelTests.swift
  Yosemite/Yosemite/Actions/CommentAction.swift
  Yosemite/Yosemite/Stores/CommentStore.swift
  Yosemite/YosemiteTests/Stores/CommentStoreTests.swift
Labels: type: enhancement, feature: review details

#8806 [ABTesting] Cache variations of logged out context experiments
  Experiments/Experiments.xcodeproj/project.pbxproj
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/ABTestVariationProvider.swift
  Experiments/Experiments/CachedABTestVariationProvider.swift
  Experiments/Experiments/VariationCache.swift
  Experiments/ExperimentsTests/CachedABTestVariationProviderTests.swift
  Experiments/ExperimentsTests/VariationCacheTests.swift
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockABTestVariationProvider.swift
  WooCommerce/WooCommerceTests/UnitTests.xctestplan
Labels: type: bug, feature: login

#8781 [Error handling] Improve logging when fetching Order details from Storage
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsResultsControllers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderLoaderViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift
  WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchUICommand.swift
Labels: type: technical debt

#8811 Use load_file instead of safe_load in Rakefile
  Rakefile
Labels: type: task, category: tooling

#8824 Added release notes to 12.2
  CHANGELOG.md
Labels: Releases

#8825 Merge 12.1 final into trunk
  Experiments/Experiments.xcodeproj/project.pbxproj
  Experiments/Experiments/ABTest.swift
  Experiments/Experiments/ABTestVariationProvider.swift
  Experiments/Experiments/CachedABTestVariationProvider.swift
  Experiments/Experiments/VariationCache.swift
  Experiments/ExperimentsTests/CachedABTestVariationProviderTests.swift
  Experiments/ExperimentsTests/VariationCacheTests.swift
  Podfile
  Podfile.lock
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/System/WooConstantsTests.swift
  WooCommerce/WooCommerceTests/UnitTests.xctestplan
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8826 Merge 12.2 code freeze into trunk
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#8827 Update the AppCenter Fastlane plugin to `2.0.0`
  Gemfile
  Gemfile.lock
Labels: category: tooling

#8832 Update the Buildkite CI image to Xcode 14.2
  .buildkite/cache-builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: category:tooling

#8833 [Mobile Payments] Update built-in reader images with drop shadows
  WooCommerce/Resources/Images.xcassets/built-in-reader-error.imageset/illustration - error-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-error.imageset/illustration - error-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/illustration - Payment successful-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-payment-success.imageset/illustration - Payment successful-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/illustration - Preparing for payment-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-preparing.imageset/illustration - Preparing for payment-light.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/illustration - Processing payment-dark.pdf
  WooCommerce/Resources/Images.xcassets/built-in-reader-processing.imageset/illustration - Processing payment-light.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/illustration - reader type-dark.pdf
  WooCommerce/Resources/Images.xcassets/card-payments-select-reader-type.imageset/illustration - reader type-light.pdf
Labels: type: task, feature: mobile payments

#8834 Add higher CI priority to release builds
  .buildkite/release-builds.yml
Labels: category: tooling

#8814 [Mobile Payments] Reveal TTP feature toggle in release builds
  Experiments/Experiments/DefaultFeatureFlagService.swift
  WooCommerce/Classes/Model/BetaFeature.swift
Labels: type: task, feature: mobile payments

#8843 Merge 12.2 final into trunk
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8821 Domain settings: minimal loading UI
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsViewModel.swift
Labels: type: task

#8822 REST API: Authenticate web view with site credentials if possible
  WooCommerce/Classes/Authentication/AuthenticatedWebViewController.swift
  WooCommerce/Classes/Extensions/WKWebView+Authenticated.swift
  WooCommerce/Classes/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModel.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenu.swift
  WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/AuthenticatedWebView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/WebViewSheet.swift
  WooCommerce/WooCommerceTests/ViewModels/Feature Announcement Cards/JustInTimeMessageAnnouncementCardViewModelTests.swift
Labels: type: enhancement, type: technical debt, feature: hub menu

#8851 [Mobile Payments] Update RELEASE-NOTES.txt with Tap to Pay
  RELEASE-NOTES.txt
Labels: feature: mobile payments

#8844 Merge 12.3 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#8846 REST API: Remove A/B test and update login flow
  Experiments/Experiments/ABTest.swift
  Podfile.lock
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+ApplicationPassword.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Prologue/LoginProloguePages.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/UITestsFoundation/Screens/Login/PrologueScreen.swift
  WooCommerce/WooCommerceTests/AppCoordinatorTests.swift
  WooCommerce/WooCommerceTests/Authentication/AuthenticationManagerTests.swift
  WooCommerce/WooCommerceUITests/Flows/LoginFlow.swift
  WooCommerce/WooCommerceUITests/Tests/LoginTests.swift
  WooCommerce/WooCommerceUITests/Tests/OrdersTests.swift
  WooCommerce/WooCommerceUITests/Tests/ProductsTests.swift
  WooCommerce/WooCommerceUITests/Tests/ReviewsTests.swift
  WooCommerce/WooCommerceUITests/Tests/StatsTests.swift
Labels: type: task, feature: login

#8850 REST API: Add new tag for users authenticated with application password
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
Labels: type: enhancement, feature: support

#8848 Update domain settings data
  Networking/Networking/Remote/DomainRemote.swift
  Networking/NetworkingTests/Remote/DomainRemoteTests.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainSettingsViewModelTests.swift
  Yosemite/YosemiteTests/Stores/DomainStoreTests.swift
Labels: type: task

#8855 Domain settings: add a learn more footnote
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/LearnMoreAttributedText.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task

#8852 [Support Request] Expose Zendesk CreateIdentity method
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/WooCommerceTests/Testing/MockZendeskManager.swift
Labels: feature: support

#8856 [Support Requests] Adds new Support Requests UI
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: feature: support

#8859 Domain contact info: replace phone field with country code and number fields
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/CustomerSection/CreateOrderAddressFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModelProtocol.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressForm.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/EditOrderAddressFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainContactInfoFormViewModelTests.swift
Labels: type: task

#8857 [Mobile Payments] Add tracking to the IPP Learn more link tap event.
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/LearnMoreViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsView.swift
Labels: type: task, feature: mobile payments

#8860 Settings: update domain settings CTA
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
Labels: type: task

#8858 [Support Requests] Add Support Areas Tags & Form IDs
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormsDataSources.swift
  WooCommerce/WooCommerceTests/Tools/Support/SupportDataSourcesTests.swift
Labels: feature: support

#8862 [Mobile Payments]Update docs according to Stripe.
  Networking/Networking/Model/WCPayCardPresentReceiptDetails.swift
Labels: type: task, feature: mobile payments

#8874 [Bulk Editing] Fix bulk editing crash when ProductsViewController disappears
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Labels: type: crash, feature: product list

#8861 Use anonymous ID to track logged-out users with Sentry
  RELEASE-NOTES.txt
  WooCommerce/Classes/Tools/Logging/WooCrashLoggingStack.swift
Labels: type: bug, category: analytics

#8865 [Support Requests] Integrate UI with ViewModel
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Tools/Support/SupportFormViewModelTests.swift
Labels: feature: support

#8867 [Support Request] Migrate Analytics
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormViewModel.swift
Labels: feature: support

#8877 [Support Request] Replace old support chat with the new Support Form
  WooCommerce/Classes/Authentication/AuthenticationManager.swift
  WooCommerce/Classes/Authentication/Epilogue/StorePickerError.swift
  WooCommerce/Classes/Authentication/Store Creation/StoreCreationCoordinator.swift
  WooCommerce/Classes/ViewRelated/AppCoordinator.swift
  WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackInstall/JetpackInstallView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/CloseAccountCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportForm+Presentation.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift
  WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift
  WooCommerce/Classes/ViewRelated/Survey/SurveyCoordinatingController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewControllerTests.swift
Labels: feature: support

#8882 [SPE] Add Simplify Product Editing feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: feature: product details, status: feature-flagged

#8878 [Support Request] Hide redundant sections
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
Labels: feature: support

#8853 [Mobile Payments] Move Payment Gateway and Reader state to analytics
  WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift
  WooCommerce/Classes/ViewModels/CardPresentPayments/ReceiptActionCoordinator.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentAnalytics.swift
  WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: mobile payments

#8870 Domain settings analytics & release
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/Analytics/WooAnalyticsEvent+DomainSettings.swift
  WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoForm.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainContactInfoFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewModels/Domains/DomainContactInfoFormViewModelTests.swift
Labels: type: task, category: analytics

#8884 [Support Request] Push & Analytics Leftovers
  WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
Labels: feature: support

#8886 Support Request: Enable Feature
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: feature: support

#8883 Merge 12.3 final into trunk
  .buildkite/commands/release-build.sh
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8889 Merge 12.4 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#8880 Domain settings: reuse `BadgeView` for the primary domain badge
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/FreeStagingDomainView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/BadgeView.swift
Labels: type: technical debt

#8895 SPE: Always display category on product details
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
Labels: feature: add/edit products

#8887 Remove Buildkite commands that are included in the VM
  .buildkite/commands/release-build.sh
  .buildkite/commands/run-ui-tests.sh
Labels: category: tooling

#8894 SPE: Move "Product type" option to product settings
  Experiments/Experiments/DefaultFeatureFlagService.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsSections.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+UpdatesTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsRowsTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsSectionsTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsViewModelTests.swift
  Yosemite/Yosemite/Model/Products/ProductSettings.swift
Labels: feature: add/edit products

#8896 SPE: Hide the reviews option from product details, when there are none
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormBottomSheetAction.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
Labels: feature: add/edit products

#8897 SPE: Show "Add product variations" in more details action sheet
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormBottomSheetAction.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
Labels: feature: add/edit products

#8879 Settings: only show Domains row for admin users
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/SettingsViewModelTests.swift
Labels: type: task

#8910 Store onboarding: feature flag, barebone UI and navigation
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Labels: type: task, status: feature-flagged

#8898 SPE: Show "Add options" button in the bottom of product details
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormActionsFactoryProtocol.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductVariationFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
Labels: feature: add/edit products

#8899 Update product form notice to display status-based feedback
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController+Helpers.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: feature: add/edit products

#8925 [Product Multi-selection] Add product multi-selection feature flag
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
Labels: type: task, feature: order creation

#8924 REST API: Add feature flag and show Jetpack benefit banner for users authenticated with application password
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  Networking/Networking/Model/Site.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewModel.swift
Labels: type: task, status: feature-flagged, feature: REST API

#8926 [Product Multi-selection] Enable multi-selection in the Order's Configuration properties
  Experiments/Experiments/DefaultFeatureFlagService.swift
  WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift
  WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/UsageDetails/CouponRestrictions.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRow.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift
  WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: order creation

#8933 REST API: Rename Jetpack install related files and types
  WooCommerce/Classes/Authentication/Jetpack Setup/LoginJetpackSetupCoordinator.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/JetpackSetupInterruptedView.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/JetpackSetupView.swift
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/JetpackSetupViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JCPJetpackInstall/JCPJetpackInstallIntroView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JCPJetpackInstall/JCPJetpackInstallStepsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JCPJetpackInstall/JCPJetpackInstallStepsViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JCPJetpackInstall/JCPJetpackInstallView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JCPJetpackInstall/JetpackInstallSteps.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/JetpackSetupViewModelTests.swift
  WooCommerce/WooCommerceTests/Authentication/Jetpack Setup/LoginJetpackSetupHostingControllerTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/JetpackInstall/JCPJetpackInstallStepsViewModelTests.swift
Labels: feature: REST API

#8931 SPE: Restrict "Add options" button visibility
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactory+ReadonlyProductTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Actions Factory/ProductFormActionsFactoryTests.swift
Labels: feature: add/edit products

#8940 SPE: Clean up grouped product created from template
  Networking/Networking/Model/Product/ProductStatus.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/ProductFactory.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/ProductFactoryTests.swift
  Yosemite/Yosemite/Stores/ProductStore.swift
  Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Labels: feature: add/edit products

#8969 Disable profiler questions feature flag to reduce friction in the store creation flow
  Experiments/Experiments/DefaultFeatureFlagService.swift
Labels: type: task

#8944 REST API: Fetch Jetpack connection status before starting the Jetpack setup flow
  Networking/Networking/ApplicationPassword/RequestConverter.swift
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackConnectionPackageSites/JetpackBenefitsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackConnectionPackageSites/JetpackBenefitsViewModel.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Mocks/MockCardPresentPaymentsStoresManager.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/JetpackInstall/JetpackBenefitsViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/JetpackSetupCoordinatorTests.swift
  Yosemite/Yosemite/Stores/JetpackConnectionStore.swift
Labels: status: feature-flagged, feature: REST API

#8976 Switch off feature flag for `productMultiSelectionM1` temporarily
  Experiments/Experiments/DefaultFeatureFlagService.swift
Labels: type: task, feature: order creation

#8977 Beta Fix: Disable Support Request Feature
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: feature: support

#8948 [Store onboarding] Polish store setup card
  WooCommerce/Classes/Extensions/UIImage+Woo.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingTaskView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreSetupProgressView.swift
  WooCommerce/Resources/Images.xcassets/icon-launch-store.imageset/Contents.json
  WooCommerce/Resources/Images.xcassets/icon-launch-store.imageset/icon-launch-store.pdf
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModelTests.swift
Labels: type: task

#8942 Dashboard stats: replace XLPagerTabStrip with WPiOS implementation
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
  WooCommerce/Classes/ViewRelated/FilterTabBar/FilterTabBar.swift
  WooCommerce/Classes/ViewRelated/FilterTabBar/TabbedViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/UITestsFoundation/Screens/MyStore/MyStoreScreen.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: technical debt

#8981 Merge 12.4 final into trunk
  Experiments/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
  WooCommerce/Resources/ar.lproj/Localizable.strings
  WooCommerce/Resources/de.lproj/Localizable.strings
  WooCommerce/Resources/es.lproj/Localizable.strings
  WooCommerce/Resources/fr.lproj/Localizable.strings
  WooCommerce/Resources/he.lproj/Localizable.strings
  WooCommerce/Resources/id.lproj/Localizable.strings
  WooCommerce/Resources/it.lproj/Localizable.strings
  WooCommerce/Resources/ja.lproj/Localizable.strings
  WooCommerce/Resources/ko.lproj/Localizable.strings
  WooCommerce/Resources/nl.lproj/Localizable.strings
  WooCommerce/Resources/pt-BR.lproj/Localizable.strings
  WooCommerce/Resources/ru.lproj/Localizable.strings
  WooCommerce/Resources/sv.lproj/Localizable.strings
  WooCommerce/Resources/tr.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hans.lproj/Localizable.strings
  WooCommerce/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#8979 Added release notes for 12.5
  CHANGELOG.md
Labels: Releases

#8986 Merge 12.5 code freeze into trunk
  Gemfile
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/Resources/AppStoreStrings.pot
  WooCommerce/Resources/en.lproj/Localizable.strings
  WooCommerce/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Fastfile
Labels: Releases

#8964 SPE: Present product form modally with feature flag enabled
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
Labels: feature: add/edit products, status: feature-flagged

#8965 SPE: Save new product as draft
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/ProductFactory.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductModel.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Add Product/ProductFactoryTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: add/edit products, status: feature-flagged

#8972 REST API: Update Jetpack benefit modal for non-Jetpack sites
  WooCommerce/Classes/ViewRelated/Dashboard/JetpackConnectionPackageSites/JetpackBenefitsView.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift
Labels: status: feature-flagged, feature: REST API

#8946 [In-App Purchases] Adapt to the new MobilePay create order request with original_transaction_id
  Networking/Networking.xcodeproj/project.pbxproj
  Networking/Networking/Remote/InAppPurchasesRemote.swift
  Networking/NetworkingTests/Remote/InAppPurchasesRemoteTests.swift
  Networking/NetworkingTests/Responses/iap-sample-receipt.json
  Yosemite/Yosemite.xcodeproj/project.pbxproj
  Yosemite/Yosemite/Stores/InAppPurchaseStore.swift
  Yosemite/Yosemite/Tools/InAppPurchases/InAppPurchaseReceiptRefreshRequest.swift
Labels: type: task, feature: in-app purchases

#8983 [Mobile Payments] Add feature flag and Tap to Pay on iPhone row for TTP M2
  Experiments/Experiments/DefaultFeatureFlagService.swift
  Experiments/Experiments/FeatureFlag.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewController.swift
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Settings/In-Person Payments/InPersonPaymentsMenuViewModelTests.swift
Labels: type: task, feature: mobile payments

#8990 REST API: Check user role and show error modal if needed
  Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
  Networking/Networking/Model/User.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/AdminRole/AdminRoleRequiredView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/AdminRole/AdminRoleRequiredViewModel.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/AdminRoleRequiredViewModelTests.swift
Labels: status: feature-flagged, feature: REST API

#8993 REST API: UI for the custom WPCom email login screen of the Jetpack Setup flow
  WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginView.swift
  WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/JetpackSetup/WPComLogin/WPComEmailLoginViewModelTests.swift
Labels: status: feature-flagged, feature: REST API

#8966 SPE: Dismiss modal and navigate to product details after new product is saved
  WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModelTests.swift
Labels: feature: add/edit products, status: feature-flagged

#8978 SPE: Update placeholder when no product category selected
  WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
Labels: feature: add/edit products

#8987 [Product Multi-selection] Adapt "done" button configuration for multiple products selection
  WooCommerce/Classes/ViewRelated/Orders/Order Creation/OrderForm.swift
Labels: type: task, feature: order creation

#8980 [Products] Show disclosure indicators in product detail rows when row is actionable
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
Labels: feature: add/edit products

#8994 [Mobile Payments] Fix IPP feedback survey banner display logic
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/OrderListViewModelTests.swift
Labels: type: bug, feature: mobile payments
