Repository woocommerce/woocommerce-ios, pull requests merged in 2025-09, with the labels that each got.

#16050 [Woo POS][Local Catalog] Update full sync remote layer to paginated products/variations API requests
  Modules/Sources/Networking/Remote/POSCatalogSyncRemote.swift
  Modules/Tests/NetworkingTests/Remote/POSCatalogSyncRemoteTests.swift
Labels: type: task, feature: POS

#16064 [Woo POS][Local Catalog] Tests for saving pos models
  Modules/Sources/Storage/GRDB/Model/PersistedProduct.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductAttribute.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductImage.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductVariation.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductVariationAttribute.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductVariationImage.swift
  Modules/Sources/Storage/GRDB/Model/PersistedSite.swift
  Modules/Sources/Storage/Protocols/Object.swift
  Modules/Sources/Yosemite/Model/Model.swift
  Modules/Sources/Yosemite/Model/Storage/PersistedProduct+Conversions.swift
  Modules/Sources/Yosemite/Model/Storage/PersistedProductVariation+Conversions.swift
  Modules/Tests/YosemiteTests/Storage/PersistedProductConversionsTests.swift
  Modules/Tests/YosemiteTests/Storage/PersistedProductTests.swift
  Modules/Tests/YosemiteTests/Storage/PersistedProductVariationConversionsTests.swift
  Modules/Tests/YosemiteTests/Storage/PersistedProductVariationTests.swift
Labels: type: task, status: feature-flagged, feature: POS

#16069 [POS Settings] Update link to barcode scanner docs
  WooCommerce/Classes/POS/Presentation/PointOfSaleBarcodeScannerInformationModal.swift
  WooCommerce/Classes/POS/Presentation/PointOfSaleDashboardView.swift
  WooCommerce/Classes/POS/Presentation/Settings/PointOfSaleSettingsHardwareDetailView.swift
  WooCommerce/Classes/POS/Presentation/Settings/PointOfSaleSettingsHelpDetailView.swift
  WooCommerce/Classes/POS/Utils/POSConstants.swift
  WooCommerce/Classes/System/WooConstants.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: POS

#16061 [Woo POS][Local catalog] Add persistence classes
  Modules/Sources/Storage/GRDB/Model/PersistedProduct.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductAttribute.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductImage.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductVariation.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductVariationAttribute.swift
  Modules/Sources/Storage/GRDB/Model/PersistedProductVariationImage.swift
  Modules/Sources/Storage/GRDB/Model/PersistedSite.swift
  Modules/Sources/Storage/Protocols/Object.swift
  Modules/Sources/Yosemite/Model/Model.swift
  Modules/Sources/Yosemite/Model/Storage/PersistedProduct+Conversions.swift
  Modules/Sources/Yosemite/Model/Storage/PersistedProductVariation+Conversions.swift
  Modules/Tests/YosemiteTests/Storage/PersistedProductTests.swift
  Modules/Tests/YosemiteTests/Storage/PersistedProductVariationTests.swift
Labels: type: task, status: feature-flagged, feature: POS

#16071 [Local Catalog] Create full sync service that syncs catalog with batches of paginated products/variations requests
  Modules/Sources/Networking/Remote/POSCatalogSyncRemote.swift
  Modules/Sources/NetworkingCore/Network/AlamofireNetwork.swift
  Modules/Sources/Yosemite/Tools/POS/POSCatalogFullSyncService.swift
  Modules/Tests/NetworkingTests/Network/AlamofireNetworkTests.swift
  Modules/Tests/YosemiteTests/Tools/POS/POSCatalogFullSyncServiceTests.swift
Labels: type: task

#16068 [POS Settings] Accessibility improvements
  WooCommerce/Classes/POS/Presentation/PointOfSaleModalHeader.swift
  WooCommerce/Classes/POS/Presentation/Settings/PointOfSaleSettingsHardwareDetailView.swift
  WooCommerce/Classes/POS/Presentation/Settings/PointOfSaleSettingsHelpDetailView.swift
  WooCommerce/Classes/POS/Presentation/Settings/PointOfSaleSettingsView.swift
Labels: type: task, category: accessibility, feature: POS

#16070 [POS Settings] Store section design updates
  WooCommerce/Classes/POS/Presentation/Settings/PointOfSaleSettingsStoreDetailView.swift
  WooCommerce/Classes/POS/Presentation/Settings/PointOfSaleSettingsView.swift
Labels: type: task, feature: POS

#16067 [POS Settings] Enable feature flag
  Modules/Sources/Experiments/DefaultFeatureFlagService.swift
  RELEASE-NOTES.txt
Labels: type: task, feature: POS

#16072 [Woo POS][Historical Orders] Order Details (Wireframe UI)
  Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrder.swift
  Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderItem.swift
  Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderMapper.swift
  Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderRefund.swift
  Modules/Sources/Yosemite/PointOfSale/OrderList/PointOfSaleOrderListFetchStrategyFactory.swift
  Modules/Sources/Yosemite/PointOfSale/OrderList/PointOfSaleOrderListService.swift
  Modules/Sources/Yosemite/Stores/Order/Order+CurrencyFormattedValues.swift
  Modules/Tests/YosemiteTests/PointOfSale/POSOrderMapperTests.swift
  Modules/Tests/YosemiteTests/PointOfSale/PointOfSaleOrderServiceTests.swift
  WooCommerce/Classes/POS/Controllers/PointOfSaleOrderListController.swift
  WooCommerce/Classes/POS/Models/POSOrdersViewState.swift
  WooCommerce/Classes/POS/Presentation/Orders/PointOfSaleOrderDetailsEmptyView.swift
  WooCommerce/Classes/POS/Presentation/Orders/PointOfSaleOrderDetailsLoadingView.swift
  WooCommerce/Classes/POS/Presentation/Orders/PointOfSaleOrderDetailsView.swift
  WooCommerce/Classes/POS/Presentation/Orders/PointOfSaleOrderListView.swift
  WooCommerce/Classes/POS/Presentation/Orders/PointOfSaleOrdersView.swift
  WooCommerce/Classes/POS/Presentation/PointOfSaleEntryPointView.swift
  WooCommerce/Classes/POS/Presentation/Reusable Views/POSPageHeaderView.swift
  WooCommerce/Classes/POS/TabBar/POSTabCoordinator.swift
  WooCommerce/Classes/POS/Utils/PreviewHelpers.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
  WooCommerce/Classes/ViewModels/Order Details/OrderPaymentDetailsViewModel.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/POS/Mocks/MockPointOfSaleOrderListService.swift
Labels: type: task, feature: POS

#16073 [Woo POS][Historical Orders] Order Details - Load product images
  Modules/Sources/Fakes/NetworkingCore.generated.swift
  Modules/Sources/Networking/Model/Copiable/Models+Copiable.generated.swift
  Modules/Sources/NetworkingCore/Model/Copiable/Models+Copiable.generated.swift
  Modules/Sources/NetworkingCore/Model/OrderItem.swift
  Modules/Sources/Yosemite/Model/Mocks/MockObjectGraph.swift
  Modules/Sources/Yosemite/Model/Storage/OrderItem+ReadOnlyConvertible.swift
  Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderItem.swift
  Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderMapper.swift
  Modules/Sources/Yosemite/Stores/Order/ProductInputTransformer.swift
  Modules/Tests/NetworkingTests/Mapper/OrderListMapperTests.swift
  Modules/Tests/NetworkingTests/Responses/order-item-image.json
  Modules/Tests/YosemiteTests/PointOfSale/POSOrderMapperTests.swift
  Modules/Tests/YosemiteTests/Stores/Order/OrdersUpsertUseCaseTests.swift
  Modules/Tests/YosemiteTests/Stores/OrderStoreTests.swift
  Modules/Tests/YosemiteTests/Stores/ProductVariationStoreTests.swift
  Modules/Tests/YosemiteTests/Stores/ReceiptStoreTests.swift
  WooCommerce/Classes/POS/Presentation/Orders/PointOfSaleOrderDetailsView.swift
  WooCommerce/Classes/POS/Utils/PreviewHelpers.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/Multi-package/ShippingLabelPackagesFormViewModel.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Package Details/ShippingLabelSampleData.swift
  WooCommerce/WooCommerceTests/POS/Mocks/MockPointOfSaleOrderListService.swift
  WooCommerce/WooCommerceTests/Tools/MockOrderItem.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/ProductDetailsCellViewModelTests.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/Product Loader/ProductLoaderViewControllerModelTests.swift
Labels: feature: POS

#16081 Shipping Labels: Display correct HAZMAT category on purchased label
  Modules/Sources/Fakes/NetworkingCore.generated.swift
  Modules/Sources/Networking/Mapper/WooShippingConfigMapper.swift
  Modules/Sources/Networking/Model/ShippingLabel/Shipments/WooShippingConfigResponse.swift
  Modules/Sources/Networking/Model/ShippingLabel/Shipments/WooShippingLabelData+mapDestinations.swift
  Modules/Sources/NetworkingCore/Model/Copiable/Models+Copiable.generated.swift
  Modules/Sources/NetworkingCore/Model/ShippingLabel/ShippingLabel.swift
  Modules/Sources/Storage/Model/MIGRATIONS.md
  Modules/Sources/Storage/Model/ShippingLabel+CoreDataProperties.swift
  Modules/Sources/Storage/Resources/WooCommerce.xcdatamodeld/.xccurrentversion
  Modules/Sources/Storage/Resources/WooCommerce.xcdatamodeld/Model 125.xcdatamodel/contents
  Modules/Sources/Yosemite/Model/Mocks/ActionHandlers/MockShippingLabelActionHandler.swift
  Modules/Sources/Yosemite/Model/Storage/ShippingLabel+ReadOnlyConvertible.swift
  Modules/Tests/NetworkingTests/Mapper/OrderShippingLabelListMapperTests.swift
  Modules/Tests/StorageTests/CoreData/MigrationTests.swift
  Modules/Tests/YosemiteTests/Mocks/MockShippingLabel.swift
  Modules/Tests/YosemiteTests/Stores/ShippingLabelStoreTests.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/WooShipping Create Shipping Labels/Refund/WooShippingRefundView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/WooShipping Create Shipping Labels/ShipmentDetails/WooShippingShipmentDetailsViewModel.swift
  WooCommerce/WooCommerceTests/Tools/MockShippingLabel.swift
Labels: feature: shipping labels, Bug

#16082 Treat coupons as expired when we reach expiry date
  Modules/Sources/Yosemite/PointOfSale/Coupons/POSCoupon.swift
Labels: type: task, Tests (new)

#16091 Update release notes for 23.2
  CHANGELOG.md
  WooCommerce/Resources/release_notes.txt
Labels: category: releases, Releases

#16088 Update gems to fix CI reporting of Swift Testing failures
  Gemfile
  Gemfile.lock
  WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleOrderControllerTests.swift
  WooCommerce/WooCommerceTests/POS/Mocks/MockPOSCollectOrderPaymentAnalyticsTracker.swift
  WooCommerce/WooCommerceTests/POS/Models/PointOfSaleAggregateModelTests.swift
Labels: type: task

#16083 [Woo POS] Fix two failing analytics tests
  Gemfile
  Gemfile.lock
  WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleOrderControllerTests.swift
  WooCommerce/WooCommerceTests/POS/Mocks/MockPOSCollectOrderPaymentAnalyticsTracker.swift
  WooCommerce/WooCommerceTests/POS/Models/PointOfSaleAggregateModelTests.swift
Labels: type: task, Tests (new)

#16087 [Woo POS][Local Catalog] Save parsed full catalog into database
  Modules/Sources/Storage/GRDB/Migrations/V001InitialSchema.swift
  Modules/Sources/Yosemite/Tools/POS/POSCatalogFullSyncService.swift
  Modules/Sources/Yosemite/Tools/POS/POSCatalogPersistenceService.swift
  Modules/Tests/YosemiteTests/Tools/POS/POSCatalogFullSyncServiceTests.swift
  Modules/Tests/YosemiteTests/Tools/POS/POSCatalogPersistenceServiceTests.swift
Labels: type: task, status: feature-flagged

#16076 [WCiOS17] Use `registerForTraitChanges` in refund views
  Modules/Sources/Networking/Model/POSProductVariation.swift
  Modules/Sources/Networking/Model/Product/ProductVariation.swift
  WooCommerce/Classes/POS/Presentation/Reusable Views/POSFullScreenCover.swift
  WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/Cells/RefundItemTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/Cells/RefundShippingDetailsTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewController.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Filters/FilteredOrdersHeaderBar.swift
Labels: type: task

#16080 [WCiOS17] Update `.onchange()` usage to iOS17 API v2
  RELEASE-NOTES.txt
  WooCommerce/Classes/Authentication/Jetpack Setup/Native Jetpack Setup/JetpackSetupView.swift
  WooCommerce/Classes/View Modifiers/View+Measurements.swift
  WooCommerce/Classes/ViewRelated/Authentication/AccountCreationForm.swift
  WooCommerce/Classes/ViewRelated/Blaze/AdDestination/BlazeAddParameterView.swift
  WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationForm.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/WooShipping Create Shipping Labels/WooShipping Package and Rate Selection/WooAddCustomPackageView.swift
  WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/WooShipping Create Shipping Labels/WooShippingAddresses/WooShippingEditAddressView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductWithAI/Preview/ProductDetailPreviewView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductWithAI/StartingInfo/ProductCreationAIStartingInfoView.swift
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductWithAI/StartingInfo/PromptProgressBar/ProductCreationAIPromptProgressBar.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/FormattableAmountTextField.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/TopTabView.swift
Labels: type: task

#16094 Watch app: Fix crash when authenticated with site credentials
  Modules/Sources/NetworkingCore/ApplicationPassword/ApplicationPasswordUseCase.swift
Labels: type: crash, feature: apple watch

#16079 Application password experiment: Fall back to Jetpack proxy after app password generation fails
  Modules/Sources/NetworkingCore/ApplicationPassword/RequestProcessor.swift
  Modules/Sources/NetworkingCore/Network/AlamofireNetwork.swift
  Modules/Sources/NetworkingCore/Network/AlamofireNetworkErrorHandler.swift
  Modules/Tests/NetworkingTests/ApplicationPassword/RequestProcessorTests.swift
  Modules/Tests/NetworkingTests/Network/AlamofireNetworkErrorHandlerTests.swift
  Modules/Tests/NetworkingTests/Network/AlamofireNetworkTests.swift
Labels: type: task

#16104 [iPadOS 26][Woo POS] Flexible width and height for card present modals
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Connection Alerts/PointOfSaleCardPresentPaymentBluetoothRequiredAlertView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Connection Alerts/PointOfSaleCardPresentPaymentConnectingFailedChargeReaderView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Connection Alerts/PointOfSaleCardPresentPaymentConnectingFailedLocationRequiredAlertView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Connection Alerts/PointOfSaleCardPresentPaymentConnectingFailedUpdatePostalCodeView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Connection Alerts/PointOfSaleCardPresentPaymentConnectingFailedView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Connection Alerts/PointOfSaleCardPresentPaymentFoundReaderView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Connection Alerts/PointOfSaleCardPresentPaymentReaderUpdateFailedView.swift
  WooCommerce/Classes/POS/Presentation/Reusable Views/POSModalSizing.swift
  WooCommerce/Classes/POS/Presentation/Reusable Views/POSModalViewModifier.swift
Labels: type: task, iOS 26

#16107 Application password experiment: Clear flagged sites after 14 days
  Modules/Sources/NetworkingCore/Network/AlamofireNetwork.swift
  Modules/Sources/NetworkingCore/Network/AlamofireNetworkErrorHandler.swift
  Modules/Tests/NetworkingTests/Network/AlamofireNetworkErrorHandlerTests.swift
  Modules/Tests/NetworkingTests/Network/AlamofireNetworkTests.swift
Labels: type: task

#16100 [POS][Local Catalog] Ensure we only run one sync at a time per site
  Modules/Sources/Yosemite/Base/StoresManager.swift
  Modules/Sources/Yosemite/Model/Mocks/MockStoresManager.swift
  Modules/Sources/Yosemite/Tools/POS/POSCatalogSyncCoordinator.swift
  Modules/Tests/YosemiteTests/Tools/POS/POSCatalogSyncCoordinatorTests.swift
  WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
  WooCommerce/Classes/ViewRelated/MainTabBarController.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
  WooCommerce/Classes/Yosemite/DefaultStoresManager.swift
Labels: type: task, status: feature-flagged, feature: POS

#16095 [CIAB] Distinguish between Garden/CIAB and regular sites
  WooCommerce/Classes/CIAB/CIABAffectedFeature.swift
  WooCommerce/Classes/CIAB/CIABEligibilityChecker.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, feature: CIAB Mobile Experience

#16121 [Woo POS] Don't ignore safe area at the root of POS modal
  WooCommerce/Classes/POS/Presentation/Reusable Views/POSModalViewModifier.swift
Labels: feature: POS, Bug

#16123 Add new support tag when using app passwords for jetpack sites
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SupportForm/SupportFormMetadataProvider.swift
Labels: type: task

#16130 [CIAB] Hide grouped and variable products types from selector
  WooCommerce/Classes/ViewRelated/Products/Add Product/AddProductCoordinator.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductTypeBottomSheetListSelectorCommand.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
  WooCommerce/WooCommerceTests/Mocks/MockCIABEligibilityChecker.swift
  WooCommerce/WooCommerceTests/ViewRelated/Products/BottomSheetListSelector/ProductTypeBottomSheetListSelectorCommandTests.swift
Labels: type: task, feature: CIAB Mobile Experience

#16131 [CIAB] Integrate garden sites API fields
  Modules/Sources/Fakes/Networking.generated.swift
  Modules/Sources/Networking/Model/Copiable/Models+Copiable.generated.swift
  Modules/Sources/Networking/Model/Site.swift
  Modules/Sources/Networking/Model/WordPressSite.swift
  Modules/Sources/Networking/Remote/SiteRemote.swift
  Modules/Sources/Storage/Model/MIGRATIONS.md
  Modules/Sources/Storage/Model/Site+CoreDataProperties.swift
  Modules/Sources/Storage/Resources/WooCommerce.xcdatamodeld/.xccurrentversion
  Modules/Sources/Storage/Resources/WooCommerce.xcdatamodeld/Model 126.xcdatamodel/contents
  Modules/Sources/Yosemite/Model/Mocks/Graphs/ScreenshotsObjectGraph.swift
  Modules/Sources/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
  WooCommerce/Classes/CIAB/CIABEligibilityChecker.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/ViewRelated/CIAB/CIABEligibilityCheckerTests.swift
Labels: type: task, feature: CIAB Mobile Experience

#16140 [WCiOS17] Update trait update API for product flows
  WooCommerce/Classes/Extensions/UICollectionViewCell+Helpers.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/AddProductImageCollectionViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/ProductImageCollectionViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift
  WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Labels: type: task

#16139 CIAB Bookings: Add eligibility check for Bookings tab
  Modules/Sources/Experiments/DefaultFeatureFlagService.swift
  Modules/Sources/Experiments/FeatureFlag.swift
  Modules/Sources/Networking/Remote/ProductsRemote.swift
  Modules/Sources/Storage/Tools/StorageType+Extensions.swift
  Modules/Sources/Yosemite/Actions/ProductAction.swift
  Modules/Sources/Yosemite/Stores/ProductStore.swift
  Modules/Tests/YosemiteTests/Mocks/Networking/Remote/MockProductsRemote.swift
  Modules/Tests/YosemiteTests/Stores/ProductStoreTests.swift
  WooCommerce/Classes/Bookings/BookingsTabEligibilityChecker.swift
  WooCommerce/Classes/Extensions/UserDefaults+Woo.swift
  WooCommerce/Classes/System/SessionManager.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
  WooCommerce/WooCommerceTests/Bookings/BookingsTabEligibilityCheckerTests.swift
  WooCommerce/WooCommerceTests/Mocks/MockFeatureFlagService.swift
  WooCommerce/WooCommerceTests/System/SessionManagerTests.swift
Labels: type: task

#16126 Use remote feature flag to use application passwords for Jetpack Sites
  Modules/Sources/Experiments/DefaultFeatureFlagService.swift
  Modules/Sources/Experiments/FeatureFlag.swift
  Modules/Sources/Networking/Remote/FeatureFlagRemote.swift
  RELEASE-NOTES.txt
  WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/ApplicationPasswordsExperimentState.swift
  WooCommerce/WooCommerceTests/ViewRelated/Settings/ApplicationPasswordsExperimentAvailabilityCheckerTests.swift
Labels: type: task

#16155 Fix UI Test Failures by updating Site API mock parameters
  WooCommerce/WooCommerceUITests/Mocks/mappings/me/rest_v11_me_sites.json
Labels: iOS

#16156 [Release] Update release notes 23.3
  CHANGELOG.md
  WooCommerce/Resources/release_notes.txt
Labels: category: releases

#16170 Bookings: Update Yosemite layer to support syncing bookings
  Modules/Sources/Networking/Model/Bookings/Booking.swift
  Modules/Sources/Storage/Tools/StorageType+Deletions.swift
  Modules/Sources/Storage/Tools/StorageType+Extensions.swift
  Modules/Sources/Yosemite/Actions/BookingAction.swift
  Modules/Sources/Yosemite/Model/Model.swift
  Modules/Sources/Yosemite/Stores/BookingStore.swift
  Modules/Tests/YosemiteTests/Mocks/MockBookingsRemote.swift
  Modules/Tests/YosemiteTests/Stores/BookingStoreTests.swift
  WooCommerce/Classes/Yosemite/AuthenticatedState.swift
Labels: type: task

#16103 Remove `pointOfSaleReceipts` feature flag
  Modules/Sources/Experiments/DefaultFeatureFlagService.swift
  Modules/Sources/Experiments/FeatureFlag.swift
  WooCommerce/Classes/POS/TabBar/POSTabCoordinator.swift
  WooCommerce/Classes/POS/Utils/POSReceiptSender.swift
  WooCommerce/WooCommerceTests/POS/Tools/POSReceiptSenderTests.swift
Labels: type: task, feature: POS

#16129 [iPadOS 26][Woo POS] Adjust Checkout view layout for smaller window heights
  WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentPreviewService.swift
  WooCommerce/Classes/POS/Models/PointOfSaleAggregateModel.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Reader Messages/POSCardPresentPaymentMessageViewImage.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Reader Messages/PointOfSaleCardPresentPaymentCardInsertedMessageView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Reader Messages/PointOfSaleCardPresentPaymentDisconnectedMessageView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Reader Messages/PointOfSaleCardPresentPaymentLayout.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Reader Messages/PointOfSaleCardPresentPaymentTapSwipeInsertCardMessageView.swift
  WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/Reader Messages/PointOfSaleCardPresentPaymentValidatingOrderErrorMessageView.swift
  WooCommerce/Classes/POS/Presentation/TotalsView.swift
  WooCommerce/Classes/POS/Utils/PointOfSalePreviewOrderController.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task, iOS 26

#16166 [Local Catalog] POS Settings: add POSCatalogSettingsService for Yosemite layer
  Modules/Sources/Yosemite/Tools/POS/POSCatalogSettingsService.swift
  Modules/Tests/YosemiteTests/Tools/POS/POSCatalogSettingsServiceTests.swift
Labels: type: task, status: feature-flagged, feature: POS

#16178 [Bookings][Part 2] Booking details screen
  WooCommerce/Classes/View Modifiers/View+Tappable.swift
  WooCommerce/Classes/ViewModels/Booking Details/AppointmentDetailsContent.swift
  WooCommerce/Classes/ViewModels/Booking Details/AttendanceContent.swift
  WooCommerce/Classes/ViewModels/Booking Details/BookingDetailsViewModel+Section.swift
  WooCommerce/Classes/ViewModels/Booking Details/BookingDetailsViewModel+SectionContent.swift
  WooCommerce/Classes/ViewModels/Booking Details/BookingDetailsViewModel+Status.swift
  WooCommerce/Classes/ViewModels/Booking Details/BookingDetailsViewModel.swift
  WooCommerce/Classes/ViewModels/Booking Details/CustomerContent.swift
  WooCommerce/Classes/ViewModels/Booking Details/HeaderContent.swift
  WooCommerce/Classes/ViewModels/Booking Details/PaymentContent.swift
  WooCommerce/Classes/ViewRelated/Bookings/Booking Details/BookingDetailsView.swift
  WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI Components/TitleAndValueRow.swift
  WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Labels: type: task
